#pragma once

namespace pnc {
namespace lateral_planning {

enum StateID {
  X = 0,
  Y = 1,
  THETA = 2,
  DELTA = 3,
  // VEL = 4,
  // ACC = 5,
  STATE_SIZE
};

enum ControlID {
  OMEGA = 0,
  // JERK = 1,
  CONTROL_SIZE
};

enum CostID {
  REFERENCE_PATH_COST = 0,
  FRONT_REFERENCE_PATH_COST = 1,
  CONTINUITY_COST = 2,
  VIRTUAL_REFERENCE_PATH_COST = 3,
  LATERAL_ACC_COST = 4,
  LATERAL_JERK_COST = 5,
  LATERAL_ACC_BOUND_COST = 6,
  LATERAL_JERK_BOUND_COST = 7,
  PATH_FIRST_SOFT_CORRIDOR_COST = 8,
  PATH_SECOND_SOFT_CORRIDOR_COST = 9,
  PATH_HARD_CORRIDOR_COST = 10,
  LATERAL_SNAP_COST = 11,
  LATERAL_ACC_HARD_BOUND_COST = 12,
  LATERAL_JERK_HARD_BOUND_COST = 13,
  PATH_CORRIDOR_COST = 14,
  COST_SIZE,
};

enum iLQRConfigID {
  REF_X = 0,
  REF_Y,
  REF_THETA,
  FRONT_REF_X,
  FRONT_REF_Y,
  REF_VEL,
  CONTINUITY_X,
  CONTINUITY_Y,
  CONTINUITY_THETA,
  VIRTUAL_REF_X,
  VIRTUAL_REF_Y,
  VIRTUAL_REF_THETA,
  EXPECTEDE_DELTA,
  DELTA_UPPER_BOUND,
  DELTA_LOWER_BOUND,
  OMEGA_UPPER_BOUND,
  OMEGA_LOWER_BOUND,
  FIRST_SOFT_UPPER_BOUND_X0,
  FIRST_SOFT_UPPER_BOUND_Y0,
  FIRST_SOFT_UPPER_BOUND_X1,
  FIRST_SOFT_UPPER_BOUND_Y1,
  FIRST_SOFT_LOWER_BOUND_X0,
  FIRST_SOFT_LOWER_BOUND_Y0,
  FIRST_SOFT_LOWER_BOUND_X1,
  FIRST_SOFT_LOWER_BOUND_Y1,
  SECOND_SOFT_UPPER_BOUND_X0,
  SECOND_SOFT_UPPER_BOUND_Y0,
  SECOND_SOFT_UPPER_BOUND_X1,
  SECOND_SOFT_UPPER_BOUND_Y1,
  SECOND_SOFT_LOWER_BOUND_X0,
  SECOND_SOFT_LOWER_BOUND_Y0,
  SECOND_SOFT_LOWER_BOUND_X1,
  SECOND_SOFT_LOWER_BOUND_Y1,
  HARD_UPPER_BOUND_X0,
  HARD_UPPER_BOUND_Y0,
  HARD_UPPER_BOUND_X1,
  HARD_UPPER_BOUND_Y1,
  HARD_LOWER_BOUND_X0,
  HARD_LOWER_BOUND_Y0,
  HARD_LOWER_BOUND_X1,
  HARD_LOWER_BOUND_Y1,
  W_REF_X,
  W_REF_Y,
  W_REF_THETA,
  W_FRONT_REF_X,
  W_FRONT_REF_Y,
  W_CONTINUITY_X,
  W_CONTINUITY_Y,
  W_CONTINUITY_THETA,
  W_VIRTUAL_REF_X,
  W_VIRTUAL_REF_Y,
  W_VIRTUAL_REF_THETA,
  W_ACC,
  W_JERK,
  W_ACC_BOUND,
  W_JERK_BOUND,
  W_FIRST_SOFT_CORRIDOR,
  W_SOFT_CORRIDOR,
  W_HARD_CORRIDOR,
  W_SNAP,
  WHEEL_BASE,
  CURV_FACTOR,
  TERMINAL_FLAG,
  CONFIG_SIZE,
};

enum ALiLQRConfigID {
  L_ACC_HARDBOUND = 0,
  W_ACC_HARDBOUND,
  L_JERK_HARDBOUND,
  W_JERK_HARDBOUND,
  L_POS_LOWER_HARDBOUND,
  W_POS_LOWER_HARDBOUND,
  L_POS_UPPER_HARDBOUND,
  W_POS_UPPER_HARDBOUND,
  PHI_SCALE,
  CONSTRAINT_CONFIG_SIZE,
};

}  // namespace lateral_planning
}  // namespace pnc