// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Funnel.proto

#ifndef PROTOBUF_INCLUDED_Funnel_2eproto
#define PROTOBUF_INCLUDED_Funnel_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Funnel_2eproto 

namespace protobuf_Funnel_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Funnel_2eproto
namespace FeiMa {
namespace Funnel {
class Funnels;
class FunnelsDefaultTypeInternal;
extern FunnelsDefaultTypeInternal _Funnels_default_instance_;
}  // namespace Funnel
}  // namespace FeiMa
namespace google {
namespace protobuf {
template<> ::FeiMa::Funnel::Funnels* Arena::CreateMaybeMessage<::FeiMa::Funnel::Funnels>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace FeiMa {
namespace Funnel {

// ===================================================================

class Funnels : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FeiMa.Funnel.Funnels) */ {
 public:
  Funnels();
  virtual ~Funnels();

  Funnels(const Funnels& from);

  inline Funnels& operator=(const Funnels& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Funnels(Funnels&& from) noexcept
    : Funnels() {
    *this = ::std::move(from);
  }

  inline Funnels& operator=(Funnels&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Funnels& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Funnels* internal_default_instance() {
    return reinterpret_cast<const Funnels*>(
               &_Funnels_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Funnels* other);
  friend void swap(Funnels& a, Funnels& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Funnels* New() const final {
    return CreateMaybeMessage<Funnels>(NULL);
  }

  Funnels* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Funnels>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Funnels& from);
  void MergeFrom(const Funnels& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Funnels* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 x = 1;
  int x_size() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::uint32 x(int index) const;
  void set_x(int index, ::google::protobuf::uint32 value);
  void add_x(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      x() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_x();

  // repeated float inner = 2;
  int inner_size() const;
  void clear_inner();
  static const int kInnerFieldNumber = 2;
  float inner(int index) const;
  void set_inner(int index, float value);
  void add_inner(float value);
  const ::google::protobuf::RepeatedField< float >&
      inner() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_inner();

  // repeated float outer = 3;
  int outer_size() const;
  void clear_outer();
  static const int kOuterFieldNumber = 3;
  float outer(int index) const;
  void set_outer(int index, float value);
  void add_outer(float value);
  const ::google::protobuf::RepeatedField< float >&
      outer() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_outer();

  // repeated float width_inner = 4;
  int width_inner_size() const;
  void clear_width_inner();
  static const int kWidthInnerFieldNumber = 4;
  float width_inner(int index) const;
  void set_width_inner(int index, float value);
  void add_width_inner(float value);
  const ::google::protobuf::RepeatedField< float >&
      width_inner() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_width_inner();

  // repeated float width_outer = 5;
  int width_outer_size() const;
  void clear_width_outer();
  static const int kWidthOuterFieldNumber = 5;
  float width_outer(int index) const;
  void set_width_outer(int index, float value);
  void add_width_outer(float value);
  const ::google::protobuf::RepeatedField< float >&
      width_outer() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_width_outer();

  // @@protoc_insertion_point(class_scope:FeiMa.Funnel.Funnels)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > x_;
  ::google::protobuf::RepeatedField< float > inner_;
  ::google::protobuf::RepeatedField< float > outer_;
  ::google::protobuf::RepeatedField< float > width_inner_;
  ::google::protobuf::RepeatedField< float > width_outer_;
  friend struct ::protobuf_Funnel_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Funnels

// repeated uint32 x = 1;
inline int Funnels::x_size() const {
  return x_.size();
}
inline void Funnels::clear_x() {
  x_.Clear();
}
inline ::google::protobuf::uint32 Funnels::x(int index) const {
  // @@protoc_insertion_point(field_get:FeiMa.Funnel.Funnels.x)
  return x_.Get(index);
}
inline void Funnels::set_x(int index, ::google::protobuf::uint32 value) {
  x_.Set(index, value);
  // @@protoc_insertion_point(field_set:FeiMa.Funnel.Funnels.x)
}
inline void Funnels::add_x(::google::protobuf::uint32 value) {
  x_.Add(value);
  // @@protoc_insertion_point(field_add:FeiMa.Funnel.Funnels.x)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Funnels::x() const {
  // @@protoc_insertion_point(field_list:FeiMa.Funnel.Funnels.x)
  return x_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Funnels::mutable_x() {
  // @@protoc_insertion_point(field_mutable_list:FeiMa.Funnel.Funnels.x)
  return &x_;
}

// repeated float inner = 2;
inline int Funnels::inner_size() const {
  return inner_.size();
}
inline void Funnels::clear_inner() {
  inner_.Clear();
}
inline float Funnels::inner(int index) const {
  // @@protoc_insertion_point(field_get:FeiMa.Funnel.Funnels.inner)
  return inner_.Get(index);
}
inline void Funnels::set_inner(int index, float value) {
  inner_.Set(index, value);
  // @@protoc_insertion_point(field_set:FeiMa.Funnel.Funnels.inner)
}
inline void Funnels::add_inner(float value) {
  inner_.Add(value);
  // @@protoc_insertion_point(field_add:FeiMa.Funnel.Funnels.inner)
}
inline const ::google::protobuf::RepeatedField< float >&
Funnels::inner() const {
  // @@protoc_insertion_point(field_list:FeiMa.Funnel.Funnels.inner)
  return inner_;
}
inline ::google::protobuf::RepeatedField< float >*
Funnels::mutable_inner() {
  // @@protoc_insertion_point(field_mutable_list:FeiMa.Funnel.Funnels.inner)
  return &inner_;
}

// repeated float outer = 3;
inline int Funnels::outer_size() const {
  return outer_.size();
}
inline void Funnels::clear_outer() {
  outer_.Clear();
}
inline float Funnels::outer(int index) const {
  // @@protoc_insertion_point(field_get:FeiMa.Funnel.Funnels.outer)
  return outer_.Get(index);
}
inline void Funnels::set_outer(int index, float value) {
  outer_.Set(index, value);
  // @@protoc_insertion_point(field_set:FeiMa.Funnel.Funnels.outer)
}
inline void Funnels::add_outer(float value) {
  outer_.Add(value);
  // @@protoc_insertion_point(field_add:FeiMa.Funnel.Funnels.outer)
}
inline const ::google::protobuf::RepeatedField< float >&
Funnels::outer() const {
  // @@protoc_insertion_point(field_list:FeiMa.Funnel.Funnels.outer)
  return outer_;
}
inline ::google::protobuf::RepeatedField< float >*
Funnels::mutable_outer() {
  // @@protoc_insertion_point(field_mutable_list:FeiMa.Funnel.Funnels.outer)
  return &outer_;
}

// repeated float width_inner = 4;
inline int Funnels::width_inner_size() const {
  return width_inner_.size();
}
inline void Funnels::clear_width_inner() {
  width_inner_.Clear();
}
inline float Funnels::width_inner(int index) const {
  // @@protoc_insertion_point(field_get:FeiMa.Funnel.Funnels.width_inner)
  return width_inner_.Get(index);
}
inline void Funnels::set_width_inner(int index, float value) {
  width_inner_.Set(index, value);
  // @@protoc_insertion_point(field_set:FeiMa.Funnel.Funnels.width_inner)
}
inline void Funnels::add_width_inner(float value) {
  width_inner_.Add(value);
  // @@protoc_insertion_point(field_add:FeiMa.Funnel.Funnels.width_inner)
}
inline const ::google::protobuf::RepeatedField< float >&
Funnels::width_inner() const {
  // @@protoc_insertion_point(field_list:FeiMa.Funnel.Funnels.width_inner)
  return width_inner_;
}
inline ::google::protobuf::RepeatedField< float >*
Funnels::mutable_width_inner() {
  // @@protoc_insertion_point(field_mutable_list:FeiMa.Funnel.Funnels.width_inner)
  return &width_inner_;
}

// repeated float width_outer = 5;
inline int Funnels::width_outer_size() const {
  return width_outer_.size();
}
inline void Funnels::clear_width_outer() {
  width_outer_.Clear();
}
inline float Funnels::width_outer(int index) const {
  // @@protoc_insertion_point(field_get:FeiMa.Funnel.Funnels.width_outer)
  return width_outer_.Get(index);
}
inline void Funnels::set_width_outer(int index, float value) {
  width_outer_.Set(index, value);
  // @@protoc_insertion_point(field_set:FeiMa.Funnel.Funnels.width_outer)
}
inline void Funnels::add_width_outer(float value) {
  width_outer_.Add(value);
  // @@protoc_insertion_point(field_add:FeiMa.Funnel.Funnels.width_outer)
}
inline const ::google::protobuf::RepeatedField< float >&
Funnels::width_outer() const {
  // @@protoc_insertion_point(field_list:FeiMa.Funnel.Funnels.width_outer)
  return width_outer_;
}
inline ::google::protobuf::RepeatedField< float >*
Funnels::mutable_width_outer() {
  // @@protoc_insertion_point(field_mutable_list:FeiMa.Funnel.Funnels.width_outer)
  return &width_outer_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Funnel
}  // namespace FeiMa

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Funnel_2eproto
