// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FusionObject.proto

#ifndef PROTOBUF_INCLUDED_FusionObject_2eproto
#define PROTOBUF_INCLUDED_FusionObject_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_FusionObject_2eproto 

namespace protobuf_FusionObject_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_FusionObject_2eproto
namespace FeiMa {
namespace FusionObject {
class FusionObjectInfo;
class FusionObjectInfoDefaultTypeInternal;
extern FusionObjectInfoDefaultTypeInternal _FusionObjectInfo_default_instance_;
class FusionObjects;
class FusionObjectsDefaultTypeInternal;
extern FusionObjectsDefaultTypeInternal _FusionObjects_default_instance_;
}  // namespace FusionObject
}  // namespace FeiMa
namespace google {
namespace protobuf {
template<> ::FeiMa::FusionObject::FusionObjectInfo* Arena::CreateMaybeMessage<::FeiMa::FusionObject::FusionObjectInfo>(Arena*);
template<> ::FeiMa::FusionObject::FusionObjects* Arena::CreateMaybeMessage<::FeiMa::FusionObject::FusionObjects>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace FeiMa {
namespace FusionObject {

enum FusionObjectType {
  RACAM_CAM_OBJ_TYPE_UNKWN_ = 0,
  RACAM_CAM_OBJ_TYPE_CAR_ = 1,
  RACAM_CAM_OBJ_TYPE_MOTORCYCLE_ = 2,
  RACAM_CAM_OBJ_TYPE_TRUCK_ = 3,
  RACAM_CAM_OBJ_TYPE_PEDESTRIAN_ = 4,
  RACAM_CAM_OBJ_TYPE_NOTUSED_ = 5,
  RACAM_CAM_OBJ_TYPE_NOTUSED1_ = 6,
  RACAM_CAM_OBJ_TYPE_ANIMAL_ = 7,
  RACAM_CAM_OBJ_TYPE_GEN_OBJ_ = 8,
  RACAM_CAM_OBJ_TYPE_BICYCLE_ = 9,
  RACAM_CAM_OBJ_TYPE_UNID_VEH_ = 10
};
bool FusionObjectType_IsValid(int value);
const FusionObjectType FusionObjectType_MIN = RACAM_CAM_OBJ_TYPE_UNKWN_;
const FusionObjectType FusionObjectType_MAX = RACAM_CAM_OBJ_TYPE_UNID_VEH_;
const int FusionObjectType_ARRAYSIZE = FusionObjectType_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectType_descriptor();
inline const ::std::string& FusionObjectType_Name(FusionObjectType value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectType_descriptor(), value);
}
inline bool FusionObjectType_Parse(
    const ::std::string& name, FusionObjectType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectType>(
    FusionObjectType_descriptor(), name, value);
}
enum FusionObjectMotionPatternCurrent {
  RACAM_MOTION_PATTERN_CURRENT_UNKWN_ = 0,
  RACAM_MOTION_PATTERN_CURRENT_STATIC_ = 1,
  RACAM_MOTION_PATTERN_CURRENT_RECEDE_ = 2,
  RACAM_MOTION_PATTERN_CURRENT_ONCOME_ = 3,
  RACAM_MOTION_PATTERN_CURRENT_CROSS_ = 4,
  RACAM_MOTION_PATTERN_CURRENT_RESERVE_ = 5
};
bool FusionObjectMotionPatternCurrent_IsValid(int value);
const FusionObjectMotionPatternCurrent FusionObjectMotionPatternCurrent_MIN = RACAM_MOTION_PATTERN_CURRENT_UNKWN_;
const FusionObjectMotionPatternCurrent FusionObjectMotionPatternCurrent_MAX = RACAM_MOTION_PATTERN_CURRENT_RESERVE_;
const int FusionObjectMotionPatternCurrent_ARRAYSIZE = FusionObjectMotionPatternCurrent_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectMotionPatternCurrent_descriptor();
inline const ::std::string& FusionObjectMotionPatternCurrent_Name(FusionObjectMotionPatternCurrent value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectMotionPatternCurrent_descriptor(), value);
}
inline bool FusionObjectMotionPatternCurrent_Parse(
    const ::std::string& name, FusionObjectMotionPatternCurrent* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectMotionPatternCurrent>(
    FusionObjectMotionPatternCurrent_descriptor(), name, value);
}
enum FusionObjectMotionPatternHistory {
  RACAM_MOTION_PATTERN_HIST_UNKWN_ = 0,
  RACAM_MOTION_PATTERN_HIST_STOPPED_ = 1,
  RACAM_MOTION_PATTERN_HIST_RECEDABLE_ = 2,
  RACAM_MOTION_PATTERN_HIST_ONCOMEABLE_ = 3
};
bool FusionObjectMotionPatternHistory_IsValid(int value);
const FusionObjectMotionPatternHistory FusionObjectMotionPatternHistory_MIN = RACAM_MOTION_PATTERN_HIST_UNKWN_;
const FusionObjectMotionPatternHistory FusionObjectMotionPatternHistory_MAX = RACAM_MOTION_PATTERN_HIST_ONCOMEABLE_;
const int FusionObjectMotionPatternHistory_ARRAYSIZE = FusionObjectMotionPatternHistory_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectMotionPatternHistory_descriptor();
inline const ::std::string& FusionObjectMotionPatternHistory_Name(FusionObjectMotionPatternHistory value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectMotionPatternHistory_descriptor(), value);
}
inline bool FusionObjectMotionPatternHistory_Parse(
    const ::std::string& name, FusionObjectMotionPatternHistory* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectMotionPatternHistory>(
    FusionObjectMotionPatternHistory_descriptor(), name, value);
}
enum FusionObjectCMBBPrimaryConfidence {
  RACAM_CMBB_PRIMARY_CONFIDENCE_NOT_RELIABLE_ = 0,
  RACAM_CMBB_PRIMARY_CONFIDENCE_COASTED_RELIABLE_ = 1,
  RACAM_CMBB_PRIMARY_CONFIDENCE_BRAKE_SUPPORT_RELIABLE_ = 2,
  RACAM_CMBB_PRIMARY_CONFIDENCE_BRAKE_RELIABLE_ = 3
};
bool FusionObjectCMBBPrimaryConfidence_IsValid(int value);
const FusionObjectCMBBPrimaryConfidence FusionObjectCMBBPrimaryConfidence_MIN = RACAM_CMBB_PRIMARY_CONFIDENCE_NOT_RELIABLE_;
const FusionObjectCMBBPrimaryConfidence FusionObjectCMBBPrimaryConfidence_MAX = RACAM_CMBB_PRIMARY_CONFIDENCE_BRAKE_RELIABLE_;
const int FusionObjectCMBBPrimaryConfidence_ARRAYSIZE = FusionObjectCMBBPrimaryConfidence_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectCMBBPrimaryConfidence_descriptor();
inline const ::std::string& FusionObjectCMBBPrimaryConfidence_Name(FusionObjectCMBBPrimaryConfidence value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectCMBBPrimaryConfidence_descriptor(), value);
}
inline bool FusionObjectCMBBPrimaryConfidence_Parse(
    const ::std::string& name, FusionObjectCMBBPrimaryConfidence* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectCMBBPrimaryConfidence>(
    FusionObjectCMBBPrimaryConfidence_descriptor(), name, value);
}
enum FusionObjectCMBBSecondaryConfidence {
  RACAM_CMBB_SECONDARY_CONFIDENCE_NOT_RELIABLE_ = 0,
  RACAM_CMBB_SECONDARY_CONFIDENCE_RELIABLE_ = 1
};
bool FusionObjectCMBBSecondaryConfidence_IsValid(int value);
const FusionObjectCMBBSecondaryConfidence FusionObjectCMBBSecondaryConfidence_MIN = RACAM_CMBB_SECONDARY_CONFIDENCE_NOT_RELIABLE_;
const FusionObjectCMBBSecondaryConfidence FusionObjectCMBBSecondaryConfidence_MAX = RACAM_CMBB_SECONDARY_CONFIDENCE_RELIABLE_;
const int FusionObjectCMBBSecondaryConfidence_ARRAYSIZE = FusionObjectCMBBSecondaryConfidence_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectCMBBSecondaryConfidence_descriptor();
inline const ::std::string& FusionObjectCMBBSecondaryConfidence_Name(FusionObjectCMBBSecondaryConfidence value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectCMBBSecondaryConfidence_descriptor(), value);
}
inline bool FusionObjectCMBBSecondaryConfidence_Parse(
    const ::std::string& name, FusionObjectCMBBSecondaryConfidence* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectCMBBSecondaryConfidence>(
    FusionObjectCMBBSecondaryConfidence_descriptor(), name, value);
}
enum FusionObjectFCWConfidence {
  RACAM_FCW_CONFIDENCE_NOT_RELIABLE_ = 0,
  RACAM_FCW_CONFIDENCE_RELIABLE_ = 1
};
bool FusionObjectFCWConfidence_IsValid(int value);
const FusionObjectFCWConfidence FusionObjectFCWConfidence_MIN = RACAM_FCW_CONFIDENCE_NOT_RELIABLE_;
const FusionObjectFCWConfidence FusionObjectFCWConfidence_MAX = RACAM_FCW_CONFIDENCE_RELIABLE_;
const int FusionObjectFCWConfidence_ARRAYSIZE = FusionObjectFCWConfidence_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectFCWConfidence_descriptor();
inline const ::std::string& FusionObjectFCWConfidence_Name(FusionObjectFCWConfidence value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectFCWConfidence_descriptor(), value);
}
inline bool FusionObjectFCWConfidence_Parse(
    const ::std::string& name, FusionObjectFCWConfidence* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectFCWConfidence>(
    FusionObjectFCWConfidence_descriptor(), name, value);
}
enum FusionObjectFusionSource {
  ObjFusn_LIRACAM_SOURCE_FALG_NOFUSED_ = 0,
  ObjFusn_LIRACAM_SOURCE_FLAG_CAMERA_ONLY_ = 1,
  ObjFusn_LIRACAM_SOURCE_FLAG_RADAR_ONLY_ = 2,
  ObjFusn_LIRACAM_SOURCE_FLAG_RACAM_ = 3,
  ObjFusn_LIRACAM_SOURCE_FLAG_LIDAR_ONLY_ = 4,
  ObjFusn_LIRACAM_SOURCE_FLAG_LICAM_ = 5,
  ObjFusn_LIRACAM_SOURCE_FLAG_LIRA_ = 6,
  ObjFusn_LIRACAM_SOURCE_FLAG_LIRACAM_ = 7,
  ObjFusn_RACAM_FUSION_SOURCE_DEFAULT_ = 255
};
bool FusionObjectFusionSource_IsValid(int value);
const FusionObjectFusionSource FusionObjectFusionSource_MIN = ObjFusn_LIRACAM_SOURCE_FALG_NOFUSED_;
const FusionObjectFusionSource FusionObjectFusionSource_MAX = ObjFusn_RACAM_FUSION_SOURCE_DEFAULT_;
const int FusionObjectFusionSource_ARRAYSIZE = FusionObjectFusionSource_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectFusionSource_descriptor();
inline const ::std::string& FusionObjectFusionSource_Name(FusionObjectFusionSource value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectFusionSource_descriptor(), value);
}
inline bool FusionObjectFusionSource_Parse(
    const ::std::string& name, FusionObjectFusionSource* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectFusionSource>(
    FusionObjectFusionSource_descriptor(), name, value);
}
enum FusionObjectPositionConfidence {
  RACAM_OBJ_CONFIDENCE_NOT_RELIABLE_ = 0,
  RACAM_OBJ_CONFIDENCE_RELIABLE_ = 1,
  RACAM_OBJ_CONFIDENCE_RELIABLE1_ = 2
};
bool FusionObjectPositionConfidence_IsValid(int value);
const FusionObjectPositionConfidence FusionObjectPositionConfidence_MIN = RACAM_OBJ_CONFIDENCE_NOT_RELIABLE_;
const FusionObjectPositionConfidence FusionObjectPositionConfidence_MAX = RACAM_OBJ_CONFIDENCE_RELIABLE1_;
const int FusionObjectPositionConfidence_ARRAYSIZE = FusionObjectPositionConfidence_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectPositionConfidence_descriptor();
inline const ::std::string& FusionObjectPositionConfidence_Name(FusionObjectPositionConfidence value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectPositionConfidence_descriptor(), value);
}
inline bool FusionObjectPositionConfidence_Parse(
    const ::std::string& name, FusionObjectPositionConfidence* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectPositionConfidence>(
    FusionObjectPositionConfidence_descriptor(), name, value);
}
enum FusionObjectTrackStatus {
  OBJ_TRACK_STATUS_INVALID_ = 0,
  OBJ_TRACK_STATUS_MERGED_ = 1,
  OBJ_TRACK_STATUS_NEW_ = 2,
  OBJ_TRACK_STATUS_NEW_COASTED_ = 3,
  OBJ_TRACK_STATUS_NOT_USED_ = 4,
  OBJ_TRACK_STATUS_UPDATED_ = 5,
  OBJ_TRACK_STATUS_COASTED_ = 6
};
bool FusionObjectTrackStatus_IsValid(int value);
const FusionObjectTrackStatus FusionObjectTrackStatus_MIN = OBJ_TRACK_STATUS_INVALID_;
const FusionObjectTrackStatus FusionObjectTrackStatus_MAX = OBJ_TRACK_STATUS_COASTED_;
const int FusionObjectTrackStatus_ARRAYSIZE = FusionObjectTrackStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectTrackStatus_descriptor();
inline const ::std::string& FusionObjectTrackStatus_Name(FusionObjectTrackStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectTrackStatus_descriptor(), value);
}
inline bool FusionObjectTrackStatus_Parse(
    const ::std::string& name, FusionObjectTrackStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectTrackStatus>(
    FusionObjectTrackStatus_descriptor(), name, value);
}
enum FusionObjectCutType {
  OBJ_CUT_TYPE_Unknown_ = 0,
  OBJ_CUT_TYPE_NO_CUT_ = 1,
  OBJ_CUT_TYPE_CUT_IN_ = 2,
  OBJ_CUT_TYPE_CUT_OUT_ = 3
};
bool FusionObjectCutType_IsValid(int value);
const FusionObjectCutType FusionObjectCutType_MIN = OBJ_CUT_TYPE_Unknown_;
const FusionObjectCutType FusionObjectCutType_MAX = OBJ_CUT_TYPE_CUT_OUT_;
const int FusionObjectCutType_ARRAYSIZE = FusionObjectCutType_MAX + 1;

const ::google::protobuf::EnumDescriptor* FusionObjectCutType_descriptor();
inline const ::std::string& FusionObjectCutType_Name(FusionObjectCutType value) {
  return ::google::protobuf::internal::NameOfEnum(
    FusionObjectCutType_descriptor(), value);
}
inline bool FusionObjectCutType_Parse(
    const ::std::string& name, FusionObjectCutType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<FusionObjectCutType>(
    FusionObjectCutType_descriptor(), name, value);
}
// ===================================================================

class FusionObjectInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FeiMa.FusionObject.FusionObjectInfo) */ {
 public:
  FusionObjectInfo();
  virtual ~FusionObjectInfo();

  FusionObjectInfo(const FusionObjectInfo& from);

  inline FusionObjectInfo& operator=(const FusionObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FusionObjectInfo(FusionObjectInfo&& from) noexcept
    : FusionObjectInfo() {
    *this = ::std::move(from);
  }

  inline FusionObjectInfo& operator=(FusionObjectInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FusionObjectInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FusionObjectInfo* internal_default_instance() {
    return reinterpret_cast<const FusionObjectInfo*>(
               &_FusionObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FusionObjectInfo* other);
  friend void swap(FusionObjectInfo& a, FusionObjectInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FusionObjectInfo* New() const final {
    return CreateMaybeMessage<FusionObjectInfo>(NULL);
  }

  FusionObjectInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FusionObjectInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FusionObjectInfo& from);
  void MergeFrom(const FusionObjectInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FusionObjectInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 sensor_source = 28;
  int sensor_source_size() const;
  void clear_sensor_source();
  static const int kSensorSourceFieldNumber = 28;
  ::google::protobuf::uint32 sensor_source(int index) const;
  void set_sensor_source(int index, ::google::protobuf::uint32 value);
  void add_sensor_source(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      sensor_source() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_sensor_source();

  // optional float long_position = 1;
  bool has_long_position() const;
  void clear_long_position();
  static const int kLongPositionFieldNumber = 1;
  float long_position() const;
  void set_long_position(float value);

  // optional float lat_position = 2;
  bool has_lat_position() const;
  void clear_lat_position();
  static const int kLatPositionFieldNumber = 2;
  float lat_position() const;
  void set_lat_position(float value);

  // optional float heading_angle = 3;
  bool has_heading_angle() const;
  void clear_heading_angle();
  static const int kHeadingAngleFieldNumber = 3;
  float heading_angle() const;
  void set_heading_angle(float value);

  // optional float speed = 4;
  bool has_speed() const;
  void clear_speed();
  static const int kSpeedFieldNumber = 4;
  float speed() const;
  void set_speed(float value);

  // optional float long_velocity = 5;
  bool has_long_velocity() const;
  void clear_long_velocity();
  static const int kLongVelocityFieldNumber = 5;
  float long_velocity() const;
  void set_long_velocity(float value);

  // optional float lat_velocity = 6;
  bool has_lat_velocity() const;
  void clear_lat_velocity();
  static const int kLatVelocityFieldNumber = 6;
  float lat_velocity() const;
  void set_lat_velocity(float value);

  // optional float acceleration = 7;
  bool has_acceleration() const;
  void clear_acceleration();
  static const int kAccelerationFieldNumber = 7;
  float acceleration() const;
  void set_acceleration(float value);

  // optional float long_acceleration = 8;
  bool has_long_acceleration() const;
  void clear_long_acceleration();
  static const int kLongAccelerationFieldNumber = 8;
  float long_acceleration() const;
  void set_long_acceleration(float value);

  // optional float lat_acceleration = 9;
  bool has_lat_acceleration() const;
  void clear_lat_acceleration();
  static const int kLatAccelerationFieldNumber = 9;
  float lat_acceleration() const;
  void set_lat_acceleration(float value);

  // optional float curvature = 10;
  bool has_curvature() const;
  void clear_curvature();
  static const int kCurvatureFieldNumber = 10;
  float curvature() const;
  void set_curvature(float value);

  // optional uint32 type = 11;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 11;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // optional float width = 12;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 12;
  float width() const;
  void set_width(float value);

  // optional float height = 13;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 13;
  float height() const;
  void set_height(float value);

  // optional float length = 14;
  bool has_length() const;
  void clear_length();
  static const int kLengthFieldNumber = 14;
  float length() const;
  void set_length(float value);

  // optional uint32 nearest_side = 15;
  bool has_nearest_side() const;
  void clear_nearest_side();
  static const int kNearestSideFieldNumber = 15;
  ::google::protobuf::uint32 nearest_side() const;
  void set_nearest_side(::google::protobuf::uint32 value);

  // optional uint32 turn_indicator = 16;
  bool has_turn_indicator() const;
  void clear_turn_indicator();
  static const int kTurnIndicatorFieldNumber = 16;
  ::google::protobuf::uint32 turn_indicator() const;
  void set_turn_indicator(::google::protobuf::uint32 value);

  // optional uint32 brake_light_indicator = 17;
  bool has_brake_light_indicator() const;
  void clear_brake_light_indicator();
  static const int kBrakeLightIndicatorFieldNumber = 17;
  ::google::protobuf::uint32 brake_light_indicator() const;
  void set_brake_light_indicator(::google::protobuf::uint32 value);

  // optional uint32 hazard_light_indicator = 18;
  bool has_hazard_light_indicator() const;
  void clear_hazard_light_indicator();
  static const int kHazardLightIndicatorFieldNumber = 18;
  ::google::protobuf::uint32 hazard_light_indicator() const;
  void set_hazard_light_indicator(::google::protobuf::uint32 value);

  // optional uint32 motion_pattern_current = 19;
  bool has_motion_pattern_current() const;
  void clear_motion_pattern_current();
  static const int kMotionPatternCurrentFieldNumber = 19;
  ::google::protobuf::uint32 motion_pattern_current() const;
  void set_motion_pattern_current(::google::protobuf::uint32 value);

  // optional uint32 motion_pattern_history = 20;
  bool has_motion_pattern_history() const;
  void clear_motion_pattern_history();
  static const int kMotionPatternHistoryFieldNumber = 20;
  ::google::protobuf::uint32 motion_pattern_history() const;
  void set_motion_pattern_history(::google::protobuf::uint32 value);

  // optional float distance_to_left_near_lane_marking = 21;
  bool has_distance_to_left_near_lane_marking() const;
  void clear_distance_to_left_near_lane_marking();
  static const int kDistanceToLeftNearLaneMarkingFieldNumber = 21;
  float distance_to_left_near_lane_marking() const;
  void set_distance_to_left_near_lane_marking(float value);

  // optional float distance_to_right_near_lane_marking = 22;
  bool has_distance_to_right_near_lane_marking() const;
  void clear_distance_to_right_near_lane_marking();
  static const int kDistanceToRightNearLaneMarkingFieldNumber = 22;
  float distance_to_right_near_lane_marking() const;
  void set_distance_to_right_near_lane_marking(float value);

  // optional float acceleration_std_dev = 23;
  bool has_acceleration_std_dev() const;
  void clear_acceleration_std_dev();
  static const int kAccelerationStdDevFieldNumber = 23;
  float acceleration_std_dev() const;
  void set_acceleration_std_dev(float value);

  // optional uint32 cmbb_primary_confidence = 24;
  bool has_cmbb_primary_confidence() const;
  void clear_cmbb_primary_confidence();
  static const int kCmbbPrimaryConfidenceFieldNumber = 24;
  ::google::protobuf::uint32 cmbb_primary_confidence() const;
  void set_cmbb_primary_confidence(::google::protobuf::uint32 value);

  // optional uint32 cmbb_secondary_confidence = 25;
  bool has_cmbb_secondary_confidence() const;
  void clear_cmbb_secondary_confidence();
  static const int kCmbbSecondaryConfidenceFieldNumber = 25;
  ::google::protobuf::uint32 cmbb_secondary_confidence() const;
  void set_cmbb_secondary_confidence(::google::protobuf::uint32 value);

  // optional uint32 fcw_confidence = 26;
  bool has_fcw_confidence() const;
  void clear_fcw_confidence();
  static const int kFcwConfidenceFieldNumber = 26;
  ::google::protobuf::uint32 fcw_confidence() const;
  void set_fcw_confidence(::google::protobuf::uint32 value);

  // optional uint32 fusion_source = 27;
  bool has_fusion_source() const;
  void clear_fusion_source();
  static const int kFusionSourceFieldNumber = 27;
  ::google::protobuf::uint32 fusion_source() const;
  void set_fusion_source(::google::protobuf::uint32 value);

  // optional float heading_angle_std_dev = 29;
  bool has_heading_angle_std_dev() const;
  void clear_heading_angle_std_dev();
  static const int kHeadingAngleStdDevFieldNumber = 29;
  float heading_angle_std_dev() const;
  void set_heading_angle_std_dev(float value);

  // optional uint32 id = 30;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 30;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint32 track_id = 31;
  bool has_track_id() const;
  void clear_track_id();
  static const int kTrackIdFieldNumber = 31;
  ::google::protobuf::uint32 track_id() const;
  void set_track_id(::google::protobuf::uint32 value);

  // optional uint32 track_age = 32;
  bool has_track_age() const;
  void clear_track_age();
  static const int kTrackAgeFieldNumber = 32;
  ::google::protobuf::uint32 track_age() const;
  void set_track_age(::google::protobuf::uint32 value);

  // optional float lat_position_std_dev = 33;
  bool has_lat_position_std_dev() const;
  void clear_lat_position_std_dev();
  static const int kLatPositionStdDevFieldNumber = 33;
  float lat_position_std_dev() const;
  void set_lat_position_std_dev(float value);

  // optional uint32 left_near_lane_marking_confidence = 34;
  bool has_left_near_lane_marking_confidence() const;
  void clear_left_near_lane_marking_confidence();
  static const int kLeftNearLaneMarkingConfidenceFieldNumber = 34;
  ::google::protobuf::uint32 left_near_lane_marking_confidence() const;
  void set_left_near_lane_marking_confidence(::google::protobuf::uint32 value);

  // optional float long_position_std_dev = 35;
  bool has_long_position_std_dev() const;
  void clear_long_position_std_dev();
  static const int kLongPositionStdDevFieldNumber = 35;
  float long_position_std_dev() const;
  void set_long_position_std_dev(float value);

  // optional uint32 motion_model = 36;
  bool has_motion_model() const;
  void clear_motion_model();
  static const int kMotionModelFieldNumber = 36;
  ::google::protobuf::uint32 motion_model() const;
  void set_motion_model(::google::protobuf::uint32 value);

  // optional uint32 position_confidence = 37;
  bool has_position_confidence() const;
  void clear_position_confidence();
  static const int kPositionConfidenceFieldNumber = 37;
  ::google::protobuf::uint32 position_confidence() const;
  void set_position_confidence(::google::protobuf::uint32 value);

  // optional uint32 right_near_lane_marking_confidence = 38;
  bool has_right_near_lane_marking_confidence() const;
  void clear_right_near_lane_marking_confidence();
  static const int kRightNearLaneMarkingConfidenceFieldNumber = 38;
  ::google::protobuf::uint32 right_near_lane_marking_confidence() const;
  void set_right_near_lane_marking_confidence(::google::protobuf::uint32 value);

  // optional float speed_std_dev = 39;
  bool has_speed_std_dev() const;
  void clear_speed_std_dev();
  static const int kSpeedStdDevFieldNumber = 39;
  float speed_std_dev() const;
  void set_speed_std_dev(float value);

  // optional uint32 tja_confidence = 40;
  bool has_tja_confidence() const;
  void clear_tja_confidence();
  static const int kTjaConfidenceFieldNumber = 40;
  ::google::protobuf::uint32 tja_confidence() const;
  void set_tja_confidence(::google::protobuf::uint32 value);

  // optional uint32 track_status = 41;
  bool has_track_status() const;
  void clear_track_status();
  static const int kTrackStatusFieldNumber = 41;
  ::google::protobuf::uint32 track_status() const;
  void set_track_status(::google::protobuf::uint32 value);

  // optional uint32 traffic_scenario = 42;
  bool has_traffic_scenario() const;
  void clear_traffic_scenario();
  static const int kTrafficScenarioFieldNumber = 42;
  ::google::protobuf::uint32 traffic_scenario() const;
  void set_traffic_scenario(::google::protobuf::uint32 value);

  // optional uint32 vision_id = 43;
  bool has_vision_id() const;
  void clear_vision_id();
  static const int kVisionIdFieldNumber = 43;
  ::google::protobuf::uint32 vision_id() const;
  void set_vision_id(::google::protobuf::uint32 value);

  // optional uint32 radar_id = 44;
  bool has_radar_id() const;
  void clear_radar_id();
  static const int kRadarIdFieldNumber = 44;
  ::google::protobuf::uint32 radar_id() const;
  void set_radar_id(::google::protobuf::uint32 value);

  // optional float obstacle_probability = 45;
  bool has_obstacle_probability() const;
  void clear_obstacle_probability();
  static const int kObstacleProbabilityFieldNumber = 45;
  float obstacle_probability() const;
  void set_obstacle_probability(float value);

  // optional uint32 target_selection_type = 46;
  bool has_target_selection_type() const;
  void clear_target_selection_type();
  static const int kTargetSelectionTypeFieldNumber = 46;
  ::google::protobuf::uint32 target_selection_type() const;
  void set_target_selection_type(::google::protobuf::uint32 value);

  // optional uint32 cut_type = 47;
  bool has_cut_type() const;
  void clear_cut_type();
  static const int kCutTypeFieldNumber = 47;
  ::google::protobuf::uint32 cut_type() const;
  void set_cut_type(::google::protobuf::uint32 value);

  // optional uint32 feature_target_cutflag = 48;
  bool has_feature_target_cutflag() const;
  void clear_feature_target_cutflag();
  static const int kFeatureTargetCutflagFieldNumber = 48;
  ::google::protobuf::uint32 feature_target_cutflag() const;
  void set_feature_target_cutflag(::google::protobuf::uint32 value);

  // optional float dst_lat_from_mid_of_laneself = 49;
  bool has_dst_lat_from_mid_of_laneself() const;
  void clear_dst_lat_from_mid_of_laneself();
  static const int kDstLatFromMidOfLaneselfFieldNumber = 49;
  float dst_lat_from_mid_of_laneself() const;
  void set_dst_lat_from_mid_of_laneself(float value);

  // optional uint32 target_selection_ccr = 50;
  bool has_target_selection_ccr() const;
  void clear_target_selection_ccr();
  static const int kTargetSelectionCcrFieldNumber = 50;
  ::google::protobuf::uint32 target_selection_ccr() const;
  void set_target_selection_ccr(::google::protobuf::uint32 value);

  // optional uint32 target_selection_vru = 51;
  bool has_target_selection_vru() const;
  void clear_target_selection_vru();
  static const int kTargetSelectionVruFieldNumber = 51;
  ::google::protobuf::uint32 target_selection_vru() const;
  void set_target_selection_vru(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:FeiMa.FusionObject.FusionObjectInfo)
 private:
  void set_has_long_position();
  void clear_has_long_position();
  void set_has_lat_position();
  void clear_has_lat_position();
  void set_has_heading_angle();
  void clear_has_heading_angle();
  void set_has_speed();
  void clear_has_speed();
  void set_has_long_velocity();
  void clear_has_long_velocity();
  void set_has_lat_velocity();
  void clear_has_lat_velocity();
  void set_has_acceleration();
  void clear_has_acceleration();
  void set_has_long_acceleration();
  void clear_has_long_acceleration();
  void set_has_lat_acceleration();
  void clear_has_lat_acceleration();
  void set_has_curvature();
  void clear_has_curvature();
  void set_has_type();
  void clear_has_type();
  void set_has_width();
  void clear_has_width();
  void set_has_height();
  void clear_has_height();
  void set_has_length();
  void clear_has_length();
  void set_has_nearest_side();
  void clear_has_nearest_side();
  void set_has_turn_indicator();
  void clear_has_turn_indicator();
  void set_has_brake_light_indicator();
  void clear_has_brake_light_indicator();
  void set_has_hazard_light_indicator();
  void clear_has_hazard_light_indicator();
  void set_has_motion_pattern_current();
  void clear_has_motion_pattern_current();
  void set_has_motion_pattern_history();
  void clear_has_motion_pattern_history();
  void set_has_distance_to_left_near_lane_marking();
  void clear_has_distance_to_left_near_lane_marking();
  void set_has_distance_to_right_near_lane_marking();
  void clear_has_distance_to_right_near_lane_marking();
  void set_has_acceleration_std_dev();
  void clear_has_acceleration_std_dev();
  void set_has_cmbb_primary_confidence();
  void clear_has_cmbb_primary_confidence();
  void set_has_cmbb_secondary_confidence();
  void clear_has_cmbb_secondary_confidence();
  void set_has_fcw_confidence();
  void clear_has_fcw_confidence();
  void set_has_fusion_source();
  void clear_has_fusion_source();
  void set_has_heading_angle_std_dev();
  void clear_has_heading_angle_std_dev();
  void set_has_id();
  void clear_has_id();
  void set_has_track_id();
  void clear_has_track_id();
  void set_has_track_age();
  void clear_has_track_age();
  void set_has_lat_position_std_dev();
  void clear_has_lat_position_std_dev();
  void set_has_left_near_lane_marking_confidence();
  void clear_has_left_near_lane_marking_confidence();
  void set_has_long_position_std_dev();
  void clear_has_long_position_std_dev();
  void set_has_motion_model();
  void clear_has_motion_model();
  void set_has_position_confidence();
  void clear_has_position_confidence();
  void set_has_right_near_lane_marking_confidence();
  void clear_has_right_near_lane_marking_confidence();
  void set_has_speed_std_dev();
  void clear_has_speed_std_dev();
  void set_has_tja_confidence();
  void clear_has_tja_confidence();
  void set_has_track_status();
  void clear_has_track_status();
  void set_has_traffic_scenario();
  void clear_has_traffic_scenario();
  void set_has_vision_id();
  void clear_has_vision_id();
  void set_has_radar_id();
  void clear_has_radar_id();
  void set_has_obstacle_probability();
  void clear_has_obstacle_probability();
  void set_has_target_selection_type();
  void clear_has_target_selection_type();
  void set_has_cut_type();
  void clear_has_cut_type();
  void set_has_feature_target_cutflag();
  void clear_has_feature_target_cutflag();
  void set_has_dst_lat_from_mid_of_laneself();
  void clear_has_dst_lat_from_mid_of_laneself();
  void set_has_target_selection_ccr();
  void clear_has_target_selection_ccr();
  void set_has_target_selection_vru();
  void clear_has_target_selection_vru();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<2> _has_bits_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > sensor_source_;
  float long_position_;
  float lat_position_;
  float heading_angle_;
  float speed_;
  float long_velocity_;
  float lat_velocity_;
  float acceleration_;
  float long_acceleration_;
  float lat_acceleration_;
  float curvature_;
  ::google::protobuf::uint32 type_;
  float width_;
  float height_;
  float length_;
  ::google::protobuf::uint32 nearest_side_;
  ::google::protobuf::uint32 turn_indicator_;
  ::google::protobuf::uint32 brake_light_indicator_;
  ::google::protobuf::uint32 hazard_light_indicator_;
  ::google::protobuf::uint32 motion_pattern_current_;
  ::google::protobuf::uint32 motion_pattern_history_;
  float distance_to_left_near_lane_marking_;
  float distance_to_right_near_lane_marking_;
  float acceleration_std_dev_;
  ::google::protobuf::uint32 cmbb_primary_confidence_;
  ::google::protobuf::uint32 cmbb_secondary_confidence_;
  ::google::protobuf::uint32 fcw_confidence_;
  ::google::protobuf::uint32 fusion_source_;
  float heading_angle_std_dev_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 track_id_;
  ::google::protobuf::uint32 track_age_;
  float lat_position_std_dev_;
  ::google::protobuf::uint32 left_near_lane_marking_confidence_;
  float long_position_std_dev_;
  ::google::protobuf::uint32 motion_model_;
  ::google::protobuf::uint32 position_confidence_;
  ::google::protobuf::uint32 right_near_lane_marking_confidence_;
  float speed_std_dev_;
  ::google::protobuf::uint32 tja_confidence_;
  ::google::protobuf::uint32 track_status_;
  ::google::protobuf::uint32 traffic_scenario_;
  ::google::protobuf::uint32 vision_id_;
  ::google::protobuf::uint32 radar_id_;
  float obstacle_probability_;
  ::google::protobuf::uint32 target_selection_type_;
  ::google::protobuf::uint32 cut_type_;
  ::google::protobuf::uint32 feature_target_cutflag_;
  float dst_lat_from_mid_of_laneself_;
  ::google::protobuf::uint32 target_selection_ccr_;
  ::google::protobuf::uint32 target_selection_vru_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_FusionObject_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FusionObjects : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FeiMa.FusionObject.FusionObjects) */ {
 public:
  FusionObjects();
  virtual ~FusionObjects();

  FusionObjects(const FusionObjects& from);

  inline FusionObjects& operator=(const FusionObjects& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FusionObjects(FusionObjects&& from) noexcept
    : FusionObjects() {
    *this = ::std::move(from);
  }

  inline FusionObjects& operator=(FusionObjects&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FusionObjects& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FusionObjects* internal_default_instance() {
    return reinterpret_cast<const FusionObjects*>(
               &_FusionObjects_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(FusionObjects* other);
  friend void swap(FusionObjects& a, FusionObjects& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FusionObjects* New() const final {
    return CreateMaybeMessage<FusionObjects>(NULL);
  }

  FusionObjects* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FusionObjects>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FusionObjects& from);
  void MergeFrom(const FusionObjects& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FusionObjects* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .FeiMa.FusionObject.FusionObjectInfo objects = 2;
  int objects_size() const;
  void clear_objects();
  static const int kObjectsFieldNumber = 2;
  ::FeiMa::FusionObject::FusionObjectInfo* mutable_objects(int index);
  ::google::protobuf::RepeatedPtrField< ::FeiMa::FusionObject::FusionObjectInfo >*
      mutable_objects();
  const ::FeiMa::FusionObject::FusionObjectInfo& objects(int index) const;
  ::FeiMa::FusionObject::FusionObjectInfo* add_objects();
  const ::google::protobuf::RepeatedPtrField< ::FeiMa::FusionObject::FusionObjectInfo >&
      objects() const;

  // optional uint32 num_obstacle = 1;
  bool has_num_obstacle() const;
  void clear_num_obstacle();
  static const int kNumObstacleFieldNumber = 1;
  ::google::protobuf::uint32 num_obstacle() const;
  void set_num_obstacle(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:FeiMa.FusionObject.FusionObjects)
 private:
  void set_has_num_obstacle();
  void clear_has_num_obstacle();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::FeiMa::FusionObject::FusionObjectInfo > objects_;
  ::google::protobuf::uint32 num_obstacle_;
  friend struct ::protobuf_FusionObject_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FusionObjectInfo

// optional float long_position = 1;
inline bool FusionObjectInfo::has_long_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FusionObjectInfo::set_has_long_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FusionObjectInfo::clear_has_long_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FusionObjectInfo::clear_long_position() {
  long_position_ = 0;
  clear_has_long_position();
}
inline float FusionObjectInfo::long_position() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.long_position)
  return long_position_;
}
inline void FusionObjectInfo::set_long_position(float value) {
  set_has_long_position();
  long_position_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.long_position)
}

// optional float lat_position = 2;
inline bool FusionObjectInfo::has_lat_position() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FusionObjectInfo::set_has_lat_position() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FusionObjectInfo::clear_has_lat_position() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FusionObjectInfo::clear_lat_position() {
  lat_position_ = 0;
  clear_has_lat_position();
}
inline float FusionObjectInfo::lat_position() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.lat_position)
  return lat_position_;
}
inline void FusionObjectInfo::set_lat_position(float value) {
  set_has_lat_position();
  lat_position_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.lat_position)
}

// optional float heading_angle = 3;
inline bool FusionObjectInfo::has_heading_angle() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FusionObjectInfo::set_has_heading_angle() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FusionObjectInfo::clear_has_heading_angle() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FusionObjectInfo::clear_heading_angle() {
  heading_angle_ = 0;
  clear_has_heading_angle();
}
inline float FusionObjectInfo::heading_angle() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.heading_angle)
  return heading_angle_;
}
inline void FusionObjectInfo::set_heading_angle(float value) {
  set_has_heading_angle();
  heading_angle_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.heading_angle)
}

// optional float speed = 4;
inline bool FusionObjectInfo::has_speed() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void FusionObjectInfo::set_has_speed() {
  _has_bits_[0] |= 0x00000008u;
}
inline void FusionObjectInfo::clear_has_speed() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void FusionObjectInfo::clear_speed() {
  speed_ = 0;
  clear_has_speed();
}
inline float FusionObjectInfo::speed() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.speed)
  return speed_;
}
inline void FusionObjectInfo::set_speed(float value) {
  set_has_speed();
  speed_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.speed)
}

// optional float long_velocity = 5;
inline bool FusionObjectInfo::has_long_velocity() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void FusionObjectInfo::set_has_long_velocity() {
  _has_bits_[0] |= 0x00000010u;
}
inline void FusionObjectInfo::clear_has_long_velocity() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void FusionObjectInfo::clear_long_velocity() {
  long_velocity_ = 0;
  clear_has_long_velocity();
}
inline float FusionObjectInfo::long_velocity() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.long_velocity)
  return long_velocity_;
}
inline void FusionObjectInfo::set_long_velocity(float value) {
  set_has_long_velocity();
  long_velocity_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.long_velocity)
}

// optional float lat_velocity = 6;
inline bool FusionObjectInfo::has_lat_velocity() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void FusionObjectInfo::set_has_lat_velocity() {
  _has_bits_[0] |= 0x00000020u;
}
inline void FusionObjectInfo::clear_has_lat_velocity() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void FusionObjectInfo::clear_lat_velocity() {
  lat_velocity_ = 0;
  clear_has_lat_velocity();
}
inline float FusionObjectInfo::lat_velocity() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.lat_velocity)
  return lat_velocity_;
}
inline void FusionObjectInfo::set_lat_velocity(float value) {
  set_has_lat_velocity();
  lat_velocity_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.lat_velocity)
}

// optional float acceleration = 7;
inline bool FusionObjectInfo::has_acceleration() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void FusionObjectInfo::set_has_acceleration() {
  _has_bits_[0] |= 0x00000040u;
}
inline void FusionObjectInfo::clear_has_acceleration() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void FusionObjectInfo::clear_acceleration() {
  acceleration_ = 0;
  clear_has_acceleration();
}
inline float FusionObjectInfo::acceleration() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.acceleration)
  return acceleration_;
}
inline void FusionObjectInfo::set_acceleration(float value) {
  set_has_acceleration();
  acceleration_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.acceleration)
}

// optional float long_acceleration = 8;
inline bool FusionObjectInfo::has_long_acceleration() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void FusionObjectInfo::set_has_long_acceleration() {
  _has_bits_[0] |= 0x00000080u;
}
inline void FusionObjectInfo::clear_has_long_acceleration() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void FusionObjectInfo::clear_long_acceleration() {
  long_acceleration_ = 0;
  clear_has_long_acceleration();
}
inline float FusionObjectInfo::long_acceleration() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.long_acceleration)
  return long_acceleration_;
}
inline void FusionObjectInfo::set_long_acceleration(float value) {
  set_has_long_acceleration();
  long_acceleration_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.long_acceleration)
}

// optional float lat_acceleration = 9;
inline bool FusionObjectInfo::has_lat_acceleration() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void FusionObjectInfo::set_has_lat_acceleration() {
  _has_bits_[0] |= 0x00000100u;
}
inline void FusionObjectInfo::clear_has_lat_acceleration() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void FusionObjectInfo::clear_lat_acceleration() {
  lat_acceleration_ = 0;
  clear_has_lat_acceleration();
}
inline float FusionObjectInfo::lat_acceleration() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.lat_acceleration)
  return lat_acceleration_;
}
inline void FusionObjectInfo::set_lat_acceleration(float value) {
  set_has_lat_acceleration();
  lat_acceleration_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.lat_acceleration)
}

// optional float curvature = 10;
inline bool FusionObjectInfo::has_curvature() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void FusionObjectInfo::set_has_curvature() {
  _has_bits_[0] |= 0x00000200u;
}
inline void FusionObjectInfo::clear_has_curvature() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void FusionObjectInfo::clear_curvature() {
  curvature_ = 0;
  clear_has_curvature();
}
inline float FusionObjectInfo::curvature() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.curvature)
  return curvature_;
}
inline void FusionObjectInfo::set_curvature(float value) {
  set_has_curvature();
  curvature_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.curvature)
}

// optional uint32 type = 11;
inline bool FusionObjectInfo::has_type() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void FusionObjectInfo::set_has_type() {
  _has_bits_[0] |= 0x00000400u;
}
inline void FusionObjectInfo::clear_has_type() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void FusionObjectInfo::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 FusionObjectInfo::type() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.type)
  return type_;
}
inline void FusionObjectInfo::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.type)
}

// optional float width = 12;
inline bool FusionObjectInfo::has_width() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void FusionObjectInfo::set_has_width() {
  _has_bits_[0] |= 0x00000800u;
}
inline void FusionObjectInfo::clear_has_width() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void FusionObjectInfo::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline float FusionObjectInfo::width() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.width)
  return width_;
}
inline void FusionObjectInfo::set_width(float value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.width)
}

// optional float height = 13;
inline bool FusionObjectInfo::has_height() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void FusionObjectInfo::set_has_height() {
  _has_bits_[0] |= 0x00001000u;
}
inline void FusionObjectInfo::clear_has_height() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void FusionObjectInfo::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline float FusionObjectInfo::height() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.height)
  return height_;
}
inline void FusionObjectInfo::set_height(float value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.height)
}

// optional float length = 14;
inline bool FusionObjectInfo::has_length() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void FusionObjectInfo::set_has_length() {
  _has_bits_[0] |= 0x00002000u;
}
inline void FusionObjectInfo::clear_has_length() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void FusionObjectInfo::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline float FusionObjectInfo::length() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.length)
  return length_;
}
inline void FusionObjectInfo::set_length(float value) {
  set_has_length();
  length_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.length)
}

// optional uint32 nearest_side = 15;
inline bool FusionObjectInfo::has_nearest_side() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void FusionObjectInfo::set_has_nearest_side() {
  _has_bits_[0] |= 0x00004000u;
}
inline void FusionObjectInfo::clear_has_nearest_side() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void FusionObjectInfo::clear_nearest_side() {
  nearest_side_ = 0u;
  clear_has_nearest_side();
}
inline ::google::protobuf::uint32 FusionObjectInfo::nearest_side() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.nearest_side)
  return nearest_side_;
}
inline void FusionObjectInfo::set_nearest_side(::google::protobuf::uint32 value) {
  set_has_nearest_side();
  nearest_side_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.nearest_side)
}

// optional uint32 turn_indicator = 16;
inline bool FusionObjectInfo::has_turn_indicator() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void FusionObjectInfo::set_has_turn_indicator() {
  _has_bits_[0] |= 0x00008000u;
}
inline void FusionObjectInfo::clear_has_turn_indicator() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void FusionObjectInfo::clear_turn_indicator() {
  turn_indicator_ = 0u;
  clear_has_turn_indicator();
}
inline ::google::protobuf::uint32 FusionObjectInfo::turn_indicator() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.turn_indicator)
  return turn_indicator_;
}
inline void FusionObjectInfo::set_turn_indicator(::google::protobuf::uint32 value) {
  set_has_turn_indicator();
  turn_indicator_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.turn_indicator)
}

// optional uint32 brake_light_indicator = 17;
inline bool FusionObjectInfo::has_brake_light_indicator() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void FusionObjectInfo::set_has_brake_light_indicator() {
  _has_bits_[0] |= 0x00010000u;
}
inline void FusionObjectInfo::clear_has_brake_light_indicator() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void FusionObjectInfo::clear_brake_light_indicator() {
  brake_light_indicator_ = 0u;
  clear_has_brake_light_indicator();
}
inline ::google::protobuf::uint32 FusionObjectInfo::brake_light_indicator() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.brake_light_indicator)
  return brake_light_indicator_;
}
inline void FusionObjectInfo::set_brake_light_indicator(::google::protobuf::uint32 value) {
  set_has_brake_light_indicator();
  brake_light_indicator_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.brake_light_indicator)
}

// optional uint32 hazard_light_indicator = 18;
inline bool FusionObjectInfo::has_hazard_light_indicator() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void FusionObjectInfo::set_has_hazard_light_indicator() {
  _has_bits_[0] |= 0x00020000u;
}
inline void FusionObjectInfo::clear_has_hazard_light_indicator() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void FusionObjectInfo::clear_hazard_light_indicator() {
  hazard_light_indicator_ = 0u;
  clear_has_hazard_light_indicator();
}
inline ::google::protobuf::uint32 FusionObjectInfo::hazard_light_indicator() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.hazard_light_indicator)
  return hazard_light_indicator_;
}
inline void FusionObjectInfo::set_hazard_light_indicator(::google::protobuf::uint32 value) {
  set_has_hazard_light_indicator();
  hazard_light_indicator_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.hazard_light_indicator)
}

// optional uint32 motion_pattern_current = 19;
inline bool FusionObjectInfo::has_motion_pattern_current() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void FusionObjectInfo::set_has_motion_pattern_current() {
  _has_bits_[0] |= 0x00040000u;
}
inline void FusionObjectInfo::clear_has_motion_pattern_current() {
  _has_bits_[0] &= ~0x00040000u;
}
inline void FusionObjectInfo::clear_motion_pattern_current() {
  motion_pattern_current_ = 0u;
  clear_has_motion_pattern_current();
}
inline ::google::protobuf::uint32 FusionObjectInfo::motion_pattern_current() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.motion_pattern_current)
  return motion_pattern_current_;
}
inline void FusionObjectInfo::set_motion_pattern_current(::google::protobuf::uint32 value) {
  set_has_motion_pattern_current();
  motion_pattern_current_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.motion_pattern_current)
}

// optional uint32 motion_pattern_history = 20;
inline bool FusionObjectInfo::has_motion_pattern_history() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void FusionObjectInfo::set_has_motion_pattern_history() {
  _has_bits_[0] |= 0x00080000u;
}
inline void FusionObjectInfo::clear_has_motion_pattern_history() {
  _has_bits_[0] &= ~0x00080000u;
}
inline void FusionObjectInfo::clear_motion_pattern_history() {
  motion_pattern_history_ = 0u;
  clear_has_motion_pattern_history();
}
inline ::google::protobuf::uint32 FusionObjectInfo::motion_pattern_history() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.motion_pattern_history)
  return motion_pattern_history_;
}
inline void FusionObjectInfo::set_motion_pattern_history(::google::protobuf::uint32 value) {
  set_has_motion_pattern_history();
  motion_pattern_history_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.motion_pattern_history)
}

// optional float distance_to_left_near_lane_marking = 21;
inline bool FusionObjectInfo::has_distance_to_left_near_lane_marking() const {
  return (_has_bits_[0] & 0x00100000u) != 0;
}
inline void FusionObjectInfo::set_has_distance_to_left_near_lane_marking() {
  _has_bits_[0] |= 0x00100000u;
}
inline void FusionObjectInfo::clear_has_distance_to_left_near_lane_marking() {
  _has_bits_[0] &= ~0x00100000u;
}
inline void FusionObjectInfo::clear_distance_to_left_near_lane_marking() {
  distance_to_left_near_lane_marking_ = 0;
  clear_has_distance_to_left_near_lane_marking();
}
inline float FusionObjectInfo::distance_to_left_near_lane_marking() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.distance_to_left_near_lane_marking)
  return distance_to_left_near_lane_marking_;
}
inline void FusionObjectInfo::set_distance_to_left_near_lane_marking(float value) {
  set_has_distance_to_left_near_lane_marking();
  distance_to_left_near_lane_marking_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.distance_to_left_near_lane_marking)
}

// optional float distance_to_right_near_lane_marking = 22;
inline bool FusionObjectInfo::has_distance_to_right_near_lane_marking() const {
  return (_has_bits_[0] & 0x00200000u) != 0;
}
inline void FusionObjectInfo::set_has_distance_to_right_near_lane_marking() {
  _has_bits_[0] |= 0x00200000u;
}
inline void FusionObjectInfo::clear_has_distance_to_right_near_lane_marking() {
  _has_bits_[0] &= ~0x00200000u;
}
inline void FusionObjectInfo::clear_distance_to_right_near_lane_marking() {
  distance_to_right_near_lane_marking_ = 0;
  clear_has_distance_to_right_near_lane_marking();
}
inline float FusionObjectInfo::distance_to_right_near_lane_marking() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.distance_to_right_near_lane_marking)
  return distance_to_right_near_lane_marking_;
}
inline void FusionObjectInfo::set_distance_to_right_near_lane_marking(float value) {
  set_has_distance_to_right_near_lane_marking();
  distance_to_right_near_lane_marking_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.distance_to_right_near_lane_marking)
}

// optional float acceleration_std_dev = 23;
inline bool FusionObjectInfo::has_acceleration_std_dev() const {
  return (_has_bits_[0] & 0x00400000u) != 0;
}
inline void FusionObjectInfo::set_has_acceleration_std_dev() {
  _has_bits_[0] |= 0x00400000u;
}
inline void FusionObjectInfo::clear_has_acceleration_std_dev() {
  _has_bits_[0] &= ~0x00400000u;
}
inline void FusionObjectInfo::clear_acceleration_std_dev() {
  acceleration_std_dev_ = 0;
  clear_has_acceleration_std_dev();
}
inline float FusionObjectInfo::acceleration_std_dev() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.acceleration_std_dev)
  return acceleration_std_dev_;
}
inline void FusionObjectInfo::set_acceleration_std_dev(float value) {
  set_has_acceleration_std_dev();
  acceleration_std_dev_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.acceleration_std_dev)
}

// optional uint32 cmbb_primary_confidence = 24;
inline bool FusionObjectInfo::has_cmbb_primary_confidence() const {
  return (_has_bits_[0] & 0x00800000u) != 0;
}
inline void FusionObjectInfo::set_has_cmbb_primary_confidence() {
  _has_bits_[0] |= 0x00800000u;
}
inline void FusionObjectInfo::clear_has_cmbb_primary_confidence() {
  _has_bits_[0] &= ~0x00800000u;
}
inline void FusionObjectInfo::clear_cmbb_primary_confidence() {
  cmbb_primary_confidence_ = 0u;
  clear_has_cmbb_primary_confidence();
}
inline ::google::protobuf::uint32 FusionObjectInfo::cmbb_primary_confidence() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.cmbb_primary_confidence)
  return cmbb_primary_confidence_;
}
inline void FusionObjectInfo::set_cmbb_primary_confidence(::google::protobuf::uint32 value) {
  set_has_cmbb_primary_confidence();
  cmbb_primary_confidence_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.cmbb_primary_confidence)
}

// optional uint32 cmbb_secondary_confidence = 25;
inline bool FusionObjectInfo::has_cmbb_secondary_confidence() const {
  return (_has_bits_[0] & 0x01000000u) != 0;
}
inline void FusionObjectInfo::set_has_cmbb_secondary_confidence() {
  _has_bits_[0] |= 0x01000000u;
}
inline void FusionObjectInfo::clear_has_cmbb_secondary_confidence() {
  _has_bits_[0] &= ~0x01000000u;
}
inline void FusionObjectInfo::clear_cmbb_secondary_confidence() {
  cmbb_secondary_confidence_ = 0u;
  clear_has_cmbb_secondary_confidence();
}
inline ::google::protobuf::uint32 FusionObjectInfo::cmbb_secondary_confidence() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.cmbb_secondary_confidence)
  return cmbb_secondary_confidence_;
}
inline void FusionObjectInfo::set_cmbb_secondary_confidence(::google::protobuf::uint32 value) {
  set_has_cmbb_secondary_confidence();
  cmbb_secondary_confidence_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.cmbb_secondary_confidence)
}

// optional uint32 fcw_confidence = 26;
inline bool FusionObjectInfo::has_fcw_confidence() const {
  return (_has_bits_[0] & 0x02000000u) != 0;
}
inline void FusionObjectInfo::set_has_fcw_confidence() {
  _has_bits_[0] |= 0x02000000u;
}
inline void FusionObjectInfo::clear_has_fcw_confidence() {
  _has_bits_[0] &= ~0x02000000u;
}
inline void FusionObjectInfo::clear_fcw_confidence() {
  fcw_confidence_ = 0u;
  clear_has_fcw_confidence();
}
inline ::google::protobuf::uint32 FusionObjectInfo::fcw_confidence() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.fcw_confidence)
  return fcw_confidence_;
}
inline void FusionObjectInfo::set_fcw_confidence(::google::protobuf::uint32 value) {
  set_has_fcw_confidence();
  fcw_confidence_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.fcw_confidence)
}

// optional uint32 fusion_source = 27;
inline bool FusionObjectInfo::has_fusion_source() const {
  return (_has_bits_[0] & 0x04000000u) != 0;
}
inline void FusionObjectInfo::set_has_fusion_source() {
  _has_bits_[0] |= 0x04000000u;
}
inline void FusionObjectInfo::clear_has_fusion_source() {
  _has_bits_[0] &= ~0x04000000u;
}
inline void FusionObjectInfo::clear_fusion_source() {
  fusion_source_ = 0u;
  clear_has_fusion_source();
}
inline ::google::protobuf::uint32 FusionObjectInfo::fusion_source() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.fusion_source)
  return fusion_source_;
}
inline void FusionObjectInfo::set_fusion_source(::google::protobuf::uint32 value) {
  set_has_fusion_source();
  fusion_source_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.fusion_source)
}

// repeated uint32 sensor_source = 28;
inline int FusionObjectInfo::sensor_source_size() const {
  return sensor_source_.size();
}
inline void FusionObjectInfo::clear_sensor_source() {
  sensor_source_.Clear();
}
inline ::google::protobuf::uint32 FusionObjectInfo::sensor_source(int index) const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.sensor_source)
  return sensor_source_.Get(index);
}
inline void FusionObjectInfo::set_sensor_source(int index, ::google::protobuf::uint32 value) {
  sensor_source_.Set(index, value);
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.sensor_source)
}
inline void FusionObjectInfo::add_sensor_source(::google::protobuf::uint32 value) {
  sensor_source_.Add(value);
  // @@protoc_insertion_point(field_add:FeiMa.FusionObject.FusionObjectInfo.sensor_source)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
FusionObjectInfo::sensor_source() const {
  // @@protoc_insertion_point(field_list:FeiMa.FusionObject.FusionObjectInfo.sensor_source)
  return sensor_source_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
FusionObjectInfo::mutable_sensor_source() {
  // @@protoc_insertion_point(field_mutable_list:FeiMa.FusionObject.FusionObjectInfo.sensor_source)
  return &sensor_source_;
}

// optional float heading_angle_std_dev = 29;
inline bool FusionObjectInfo::has_heading_angle_std_dev() const {
  return (_has_bits_[0] & 0x08000000u) != 0;
}
inline void FusionObjectInfo::set_has_heading_angle_std_dev() {
  _has_bits_[0] |= 0x08000000u;
}
inline void FusionObjectInfo::clear_has_heading_angle_std_dev() {
  _has_bits_[0] &= ~0x08000000u;
}
inline void FusionObjectInfo::clear_heading_angle_std_dev() {
  heading_angle_std_dev_ = 0;
  clear_has_heading_angle_std_dev();
}
inline float FusionObjectInfo::heading_angle_std_dev() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.heading_angle_std_dev)
  return heading_angle_std_dev_;
}
inline void FusionObjectInfo::set_heading_angle_std_dev(float value) {
  set_has_heading_angle_std_dev();
  heading_angle_std_dev_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.heading_angle_std_dev)
}

// optional uint32 id = 30;
inline bool FusionObjectInfo::has_id() const {
  return (_has_bits_[0] & 0x10000000u) != 0;
}
inline void FusionObjectInfo::set_has_id() {
  _has_bits_[0] |= 0x10000000u;
}
inline void FusionObjectInfo::clear_has_id() {
  _has_bits_[0] &= ~0x10000000u;
}
inline void FusionObjectInfo::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 FusionObjectInfo::id() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.id)
  return id_;
}
inline void FusionObjectInfo::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.id)
}

// optional uint32 track_id = 31;
inline bool FusionObjectInfo::has_track_id() const {
  return (_has_bits_[0] & 0x20000000u) != 0;
}
inline void FusionObjectInfo::set_has_track_id() {
  _has_bits_[0] |= 0x20000000u;
}
inline void FusionObjectInfo::clear_has_track_id() {
  _has_bits_[0] &= ~0x20000000u;
}
inline void FusionObjectInfo::clear_track_id() {
  track_id_ = 0u;
  clear_has_track_id();
}
inline ::google::protobuf::uint32 FusionObjectInfo::track_id() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.track_id)
  return track_id_;
}
inline void FusionObjectInfo::set_track_id(::google::protobuf::uint32 value) {
  set_has_track_id();
  track_id_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.track_id)
}

// optional uint32 track_age = 32;
inline bool FusionObjectInfo::has_track_age() const {
  return (_has_bits_[0] & 0x40000000u) != 0;
}
inline void FusionObjectInfo::set_has_track_age() {
  _has_bits_[0] |= 0x40000000u;
}
inline void FusionObjectInfo::clear_has_track_age() {
  _has_bits_[0] &= ~0x40000000u;
}
inline void FusionObjectInfo::clear_track_age() {
  track_age_ = 0u;
  clear_has_track_age();
}
inline ::google::protobuf::uint32 FusionObjectInfo::track_age() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.track_age)
  return track_age_;
}
inline void FusionObjectInfo::set_track_age(::google::protobuf::uint32 value) {
  set_has_track_age();
  track_age_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.track_age)
}

// optional float lat_position_std_dev = 33;
inline bool FusionObjectInfo::has_lat_position_std_dev() const {
  return (_has_bits_[0] & 0x80000000u) != 0;
}
inline void FusionObjectInfo::set_has_lat_position_std_dev() {
  _has_bits_[0] |= 0x80000000u;
}
inline void FusionObjectInfo::clear_has_lat_position_std_dev() {
  _has_bits_[0] &= ~0x80000000u;
}
inline void FusionObjectInfo::clear_lat_position_std_dev() {
  lat_position_std_dev_ = 0;
  clear_has_lat_position_std_dev();
}
inline float FusionObjectInfo::lat_position_std_dev() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.lat_position_std_dev)
  return lat_position_std_dev_;
}
inline void FusionObjectInfo::set_lat_position_std_dev(float value) {
  set_has_lat_position_std_dev();
  lat_position_std_dev_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.lat_position_std_dev)
}

// optional uint32 left_near_lane_marking_confidence = 34;
inline bool FusionObjectInfo::has_left_near_lane_marking_confidence() const {
  return (_has_bits_[1] & 0x00000001u) != 0;
}
inline void FusionObjectInfo::set_has_left_near_lane_marking_confidence() {
  _has_bits_[1] |= 0x00000001u;
}
inline void FusionObjectInfo::clear_has_left_near_lane_marking_confidence() {
  _has_bits_[1] &= ~0x00000001u;
}
inline void FusionObjectInfo::clear_left_near_lane_marking_confidence() {
  left_near_lane_marking_confidence_ = 0u;
  clear_has_left_near_lane_marking_confidence();
}
inline ::google::protobuf::uint32 FusionObjectInfo::left_near_lane_marking_confidence() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.left_near_lane_marking_confidence)
  return left_near_lane_marking_confidence_;
}
inline void FusionObjectInfo::set_left_near_lane_marking_confidence(::google::protobuf::uint32 value) {
  set_has_left_near_lane_marking_confidence();
  left_near_lane_marking_confidence_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.left_near_lane_marking_confidence)
}

// optional float long_position_std_dev = 35;
inline bool FusionObjectInfo::has_long_position_std_dev() const {
  return (_has_bits_[1] & 0x00000002u) != 0;
}
inline void FusionObjectInfo::set_has_long_position_std_dev() {
  _has_bits_[1] |= 0x00000002u;
}
inline void FusionObjectInfo::clear_has_long_position_std_dev() {
  _has_bits_[1] &= ~0x00000002u;
}
inline void FusionObjectInfo::clear_long_position_std_dev() {
  long_position_std_dev_ = 0;
  clear_has_long_position_std_dev();
}
inline float FusionObjectInfo::long_position_std_dev() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.long_position_std_dev)
  return long_position_std_dev_;
}
inline void FusionObjectInfo::set_long_position_std_dev(float value) {
  set_has_long_position_std_dev();
  long_position_std_dev_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.long_position_std_dev)
}

// optional uint32 motion_model = 36;
inline bool FusionObjectInfo::has_motion_model() const {
  return (_has_bits_[1] & 0x00000004u) != 0;
}
inline void FusionObjectInfo::set_has_motion_model() {
  _has_bits_[1] |= 0x00000004u;
}
inline void FusionObjectInfo::clear_has_motion_model() {
  _has_bits_[1] &= ~0x00000004u;
}
inline void FusionObjectInfo::clear_motion_model() {
  motion_model_ = 0u;
  clear_has_motion_model();
}
inline ::google::protobuf::uint32 FusionObjectInfo::motion_model() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.motion_model)
  return motion_model_;
}
inline void FusionObjectInfo::set_motion_model(::google::protobuf::uint32 value) {
  set_has_motion_model();
  motion_model_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.motion_model)
}

// optional uint32 position_confidence = 37;
inline bool FusionObjectInfo::has_position_confidence() const {
  return (_has_bits_[1] & 0x00000008u) != 0;
}
inline void FusionObjectInfo::set_has_position_confidence() {
  _has_bits_[1] |= 0x00000008u;
}
inline void FusionObjectInfo::clear_has_position_confidence() {
  _has_bits_[1] &= ~0x00000008u;
}
inline void FusionObjectInfo::clear_position_confidence() {
  position_confidence_ = 0u;
  clear_has_position_confidence();
}
inline ::google::protobuf::uint32 FusionObjectInfo::position_confidence() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.position_confidence)
  return position_confidence_;
}
inline void FusionObjectInfo::set_position_confidence(::google::protobuf::uint32 value) {
  set_has_position_confidence();
  position_confidence_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.position_confidence)
}

// optional uint32 right_near_lane_marking_confidence = 38;
inline bool FusionObjectInfo::has_right_near_lane_marking_confidence() const {
  return (_has_bits_[1] & 0x00000010u) != 0;
}
inline void FusionObjectInfo::set_has_right_near_lane_marking_confidence() {
  _has_bits_[1] |= 0x00000010u;
}
inline void FusionObjectInfo::clear_has_right_near_lane_marking_confidence() {
  _has_bits_[1] &= ~0x00000010u;
}
inline void FusionObjectInfo::clear_right_near_lane_marking_confidence() {
  right_near_lane_marking_confidence_ = 0u;
  clear_has_right_near_lane_marking_confidence();
}
inline ::google::protobuf::uint32 FusionObjectInfo::right_near_lane_marking_confidence() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.right_near_lane_marking_confidence)
  return right_near_lane_marking_confidence_;
}
inline void FusionObjectInfo::set_right_near_lane_marking_confidence(::google::protobuf::uint32 value) {
  set_has_right_near_lane_marking_confidence();
  right_near_lane_marking_confidence_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.right_near_lane_marking_confidence)
}

// optional float speed_std_dev = 39;
inline bool FusionObjectInfo::has_speed_std_dev() const {
  return (_has_bits_[1] & 0x00000020u) != 0;
}
inline void FusionObjectInfo::set_has_speed_std_dev() {
  _has_bits_[1] |= 0x00000020u;
}
inline void FusionObjectInfo::clear_has_speed_std_dev() {
  _has_bits_[1] &= ~0x00000020u;
}
inline void FusionObjectInfo::clear_speed_std_dev() {
  speed_std_dev_ = 0;
  clear_has_speed_std_dev();
}
inline float FusionObjectInfo::speed_std_dev() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.speed_std_dev)
  return speed_std_dev_;
}
inline void FusionObjectInfo::set_speed_std_dev(float value) {
  set_has_speed_std_dev();
  speed_std_dev_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.speed_std_dev)
}

// optional uint32 tja_confidence = 40;
inline bool FusionObjectInfo::has_tja_confidence() const {
  return (_has_bits_[1] & 0x00000040u) != 0;
}
inline void FusionObjectInfo::set_has_tja_confidence() {
  _has_bits_[1] |= 0x00000040u;
}
inline void FusionObjectInfo::clear_has_tja_confidence() {
  _has_bits_[1] &= ~0x00000040u;
}
inline void FusionObjectInfo::clear_tja_confidence() {
  tja_confidence_ = 0u;
  clear_has_tja_confidence();
}
inline ::google::protobuf::uint32 FusionObjectInfo::tja_confidence() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.tja_confidence)
  return tja_confidence_;
}
inline void FusionObjectInfo::set_tja_confidence(::google::protobuf::uint32 value) {
  set_has_tja_confidence();
  tja_confidence_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.tja_confidence)
}

// optional uint32 track_status = 41;
inline bool FusionObjectInfo::has_track_status() const {
  return (_has_bits_[1] & 0x00000080u) != 0;
}
inline void FusionObjectInfo::set_has_track_status() {
  _has_bits_[1] |= 0x00000080u;
}
inline void FusionObjectInfo::clear_has_track_status() {
  _has_bits_[1] &= ~0x00000080u;
}
inline void FusionObjectInfo::clear_track_status() {
  track_status_ = 0u;
  clear_has_track_status();
}
inline ::google::protobuf::uint32 FusionObjectInfo::track_status() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.track_status)
  return track_status_;
}
inline void FusionObjectInfo::set_track_status(::google::protobuf::uint32 value) {
  set_has_track_status();
  track_status_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.track_status)
}

// optional uint32 traffic_scenario = 42;
inline bool FusionObjectInfo::has_traffic_scenario() const {
  return (_has_bits_[1] & 0x00000100u) != 0;
}
inline void FusionObjectInfo::set_has_traffic_scenario() {
  _has_bits_[1] |= 0x00000100u;
}
inline void FusionObjectInfo::clear_has_traffic_scenario() {
  _has_bits_[1] &= ~0x00000100u;
}
inline void FusionObjectInfo::clear_traffic_scenario() {
  traffic_scenario_ = 0u;
  clear_has_traffic_scenario();
}
inline ::google::protobuf::uint32 FusionObjectInfo::traffic_scenario() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.traffic_scenario)
  return traffic_scenario_;
}
inline void FusionObjectInfo::set_traffic_scenario(::google::protobuf::uint32 value) {
  set_has_traffic_scenario();
  traffic_scenario_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.traffic_scenario)
}

// optional uint32 vision_id = 43;
inline bool FusionObjectInfo::has_vision_id() const {
  return (_has_bits_[1] & 0x00000200u) != 0;
}
inline void FusionObjectInfo::set_has_vision_id() {
  _has_bits_[1] |= 0x00000200u;
}
inline void FusionObjectInfo::clear_has_vision_id() {
  _has_bits_[1] &= ~0x00000200u;
}
inline void FusionObjectInfo::clear_vision_id() {
  vision_id_ = 0u;
  clear_has_vision_id();
}
inline ::google::protobuf::uint32 FusionObjectInfo::vision_id() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.vision_id)
  return vision_id_;
}
inline void FusionObjectInfo::set_vision_id(::google::protobuf::uint32 value) {
  set_has_vision_id();
  vision_id_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.vision_id)
}

// optional uint32 radar_id = 44;
inline bool FusionObjectInfo::has_radar_id() const {
  return (_has_bits_[1] & 0x00000400u) != 0;
}
inline void FusionObjectInfo::set_has_radar_id() {
  _has_bits_[1] |= 0x00000400u;
}
inline void FusionObjectInfo::clear_has_radar_id() {
  _has_bits_[1] &= ~0x00000400u;
}
inline void FusionObjectInfo::clear_radar_id() {
  radar_id_ = 0u;
  clear_has_radar_id();
}
inline ::google::protobuf::uint32 FusionObjectInfo::radar_id() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.radar_id)
  return radar_id_;
}
inline void FusionObjectInfo::set_radar_id(::google::protobuf::uint32 value) {
  set_has_radar_id();
  radar_id_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.radar_id)
}

// optional float obstacle_probability = 45;
inline bool FusionObjectInfo::has_obstacle_probability() const {
  return (_has_bits_[1] & 0x00000800u) != 0;
}
inline void FusionObjectInfo::set_has_obstacle_probability() {
  _has_bits_[1] |= 0x00000800u;
}
inline void FusionObjectInfo::clear_has_obstacle_probability() {
  _has_bits_[1] &= ~0x00000800u;
}
inline void FusionObjectInfo::clear_obstacle_probability() {
  obstacle_probability_ = 0;
  clear_has_obstacle_probability();
}
inline float FusionObjectInfo::obstacle_probability() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.obstacle_probability)
  return obstacle_probability_;
}
inline void FusionObjectInfo::set_obstacle_probability(float value) {
  set_has_obstacle_probability();
  obstacle_probability_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.obstacle_probability)
}

// optional uint32 target_selection_type = 46;
inline bool FusionObjectInfo::has_target_selection_type() const {
  return (_has_bits_[1] & 0x00001000u) != 0;
}
inline void FusionObjectInfo::set_has_target_selection_type() {
  _has_bits_[1] |= 0x00001000u;
}
inline void FusionObjectInfo::clear_has_target_selection_type() {
  _has_bits_[1] &= ~0x00001000u;
}
inline void FusionObjectInfo::clear_target_selection_type() {
  target_selection_type_ = 0u;
  clear_has_target_selection_type();
}
inline ::google::protobuf::uint32 FusionObjectInfo::target_selection_type() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.target_selection_type)
  return target_selection_type_;
}
inline void FusionObjectInfo::set_target_selection_type(::google::protobuf::uint32 value) {
  set_has_target_selection_type();
  target_selection_type_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.target_selection_type)
}

// optional uint32 cut_type = 47;
inline bool FusionObjectInfo::has_cut_type() const {
  return (_has_bits_[1] & 0x00002000u) != 0;
}
inline void FusionObjectInfo::set_has_cut_type() {
  _has_bits_[1] |= 0x00002000u;
}
inline void FusionObjectInfo::clear_has_cut_type() {
  _has_bits_[1] &= ~0x00002000u;
}
inline void FusionObjectInfo::clear_cut_type() {
  cut_type_ = 0u;
  clear_has_cut_type();
}
inline ::google::protobuf::uint32 FusionObjectInfo::cut_type() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.cut_type)
  return cut_type_;
}
inline void FusionObjectInfo::set_cut_type(::google::protobuf::uint32 value) {
  set_has_cut_type();
  cut_type_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.cut_type)
}

// optional uint32 feature_target_cutflag = 48;
inline bool FusionObjectInfo::has_feature_target_cutflag() const {
  return (_has_bits_[1] & 0x00004000u) != 0;
}
inline void FusionObjectInfo::set_has_feature_target_cutflag() {
  _has_bits_[1] |= 0x00004000u;
}
inline void FusionObjectInfo::clear_has_feature_target_cutflag() {
  _has_bits_[1] &= ~0x00004000u;
}
inline void FusionObjectInfo::clear_feature_target_cutflag() {
  feature_target_cutflag_ = 0u;
  clear_has_feature_target_cutflag();
}
inline ::google::protobuf::uint32 FusionObjectInfo::feature_target_cutflag() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.feature_target_cutflag)
  return feature_target_cutflag_;
}
inline void FusionObjectInfo::set_feature_target_cutflag(::google::protobuf::uint32 value) {
  set_has_feature_target_cutflag();
  feature_target_cutflag_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.feature_target_cutflag)
}

// optional float dst_lat_from_mid_of_laneself = 49;
inline bool FusionObjectInfo::has_dst_lat_from_mid_of_laneself() const {
  return (_has_bits_[1] & 0x00008000u) != 0;
}
inline void FusionObjectInfo::set_has_dst_lat_from_mid_of_laneself() {
  _has_bits_[1] |= 0x00008000u;
}
inline void FusionObjectInfo::clear_has_dst_lat_from_mid_of_laneself() {
  _has_bits_[1] &= ~0x00008000u;
}
inline void FusionObjectInfo::clear_dst_lat_from_mid_of_laneself() {
  dst_lat_from_mid_of_laneself_ = 0;
  clear_has_dst_lat_from_mid_of_laneself();
}
inline float FusionObjectInfo::dst_lat_from_mid_of_laneself() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.dst_lat_from_mid_of_laneself)
  return dst_lat_from_mid_of_laneself_;
}
inline void FusionObjectInfo::set_dst_lat_from_mid_of_laneself(float value) {
  set_has_dst_lat_from_mid_of_laneself();
  dst_lat_from_mid_of_laneself_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.dst_lat_from_mid_of_laneself)
}

// optional uint32 target_selection_ccr = 50;
inline bool FusionObjectInfo::has_target_selection_ccr() const {
  return (_has_bits_[1] & 0x00010000u) != 0;
}
inline void FusionObjectInfo::set_has_target_selection_ccr() {
  _has_bits_[1] |= 0x00010000u;
}
inline void FusionObjectInfo::clear_has_target_selection_ccr() {
  _has_bits_[1] &= ~0x00010000u;
}
inline void FusionObjectInfo::clear_target_selection_ccr() {
  target_selection_ccr_ = 0u;
  clear_has_target_selection_ccr();
}
inline ::google::protobuf::uint32 FusionObjectInfo::target_selection_ccr() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.target_selection_ccr)
  return target_selection_ccr_;
}
inline void FusionObjectInfo::set_target_selection_ccr(::google::protobuf::uint32 value) {
  set_has_target_selection_ccr();
  target_selection_ccr_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.target_selection_ccr)
}

// optional uint32 target_selection_vru = 51;
inline bool FusionObjectInfo::has_target_selection_vru() const {
  return (_has_bits_[1] & 0x00020000u) != 0;
}
inline void FusionObjectInfo::set_has_target_selection_vru() {
  _has_bits_[1] |= 0x00020000u;
}
inline void FusionObjectInfo::clear_has_target_selection_vru() {
  _has_bits_[1] &= ~0x00020000u;
}
inline void FusionObjectInfo::clear_target_selection_vru() {
  target_selection_vru_ = 0u;
  clear_has_target_selection_vru();
}
inline ::google::protobuf::uint32 FusionObjectInfo::target_selection_vru() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjectInfo.target_selection_vru)
  return target_selection_vru_;
}
inline void FusionObjectInfo::set_target_selection_vru(::google::protobuf::uint32 value) {
  set_has_target_selection_vru();
  target_selection_vru_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjectInfo.target_selection_vru)
}

// -------------------------------------------------------------------

// FusionObjects

// optional uint32 num_obstacle = 1;
inline bool FusionObjects::has_num_obstacle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FusionObjects::set_has_num_obstacle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FusionObjects::clear_has_num_obstacle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FusionObjects::clear_num_obstacle() {
  num_obstacle_ = 0u;
  clear_has_num_obstacle();
}
inline ::google::protobuf::uint32 FusionObjects::num_obstacle() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjects.num_obstacle)
  return num_obstacle_;
}
inline void FusionObjects::set_num_obstacle(::google::protobuf::uint32 value) {
  set_has_num_obstacle();
  num_obstacle_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionObject.FusionObjects.num_obstacle)
}

// repeated .FeiMa.FusionObject.FusionObjectInfo objects = 2;
inline int FusionObjects::objects_size() const {
  return objects_.size();
}
inline void FusionObjects::clear_objects() {
  objects_.Clear();
}
inline ::FeiMa::FusionObject::FusionObjectInfo* FusionObjects::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:FeiMa.FusionObject.FusionObjects.objects)
  return objects_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::FeiMa::FusionObject::FusionObjectInfo >*
FusionObjects::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:FeiMa.FusionObject.FusionObjects.objects)
  return &objects_;
}
inline const ::FeiMa::FusionObject::FusionObjectInfo& FusionObjects::objects(int index) const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionObject.FusionObjects.objects)
  return objects_.Get(index);
}
inline ::FeiMa::FusionObject::FusionObjectInfo* FusionObjects::add_objects() {
  // @@protoc_insertion_point(field_add:FeiMa.FusionObject.FusionObjects.objects)
  return objects_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::FeiMa::FusionObject::FusionObjectInfo >&
FusionObjects::objects() const {
  // @@protoc_insertion_point(field_list:FeiMa.FusionObject.FusionObjects.objects)
  return objects_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace FusionObject
}  // namespace FeiMa

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectType>() {
  return ::FeiMa::FusionObject::FusionObjectType_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectMotionPatternCurrent> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectMotionPatternCurrent>() {
  return ::FeiMa::FusionObject::FusionObjectMotionPatternCurrent_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectMotionPatternHistory> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectMotionPatternHistory>() {
  return ::FeiMa::FusionObject::FusionObjectMotionPatternHistory_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectCMBBPrimaryConfidence> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectCMBBPrimaryConfidence>() {
  return ::FeiMa::FusionObject::FusionObjectCMBBPrimaryConfidence_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectCMBBSecondaryConfidence> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectCMBBSecondaryConfidence>() {
  return ::FeiMa::FusionObject::FusionObjectCMBBSecondaryConfidence_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectFCWConfidence> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectFCWConfidence>() {
  return ::FeiMa::FusionObject::FusionObjectFCWConfidence_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectFusionSource> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectFusionSource>() {
  return ::FeiMa::FusionObject::FusionObjectFusionSource_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectPositionConfidence> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectPositionConfidence>() {
  return ::FeiMa::FusionObject::FusionObjectPositionConfidence_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectTrackStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectTrackStatus>() {
  return ::FeiMa::FusionObject::FusionObjectTrackStatus_descriptor();
}
template <> struct is_proto_enum< ::FeiMa::FusionObject::FusionObjectCutType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::FeiMa::FusionObject::FusionObjectCutType>() {
  return ::FeiMa::FusionObject::FusionObjectCutType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_FusionObject_2eproto
