// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FusionOut.proto

#ifndef PROTOBUF_INCLUDED_FusionOut_2eproto
#define PROTOBUF_INCLUDED_FusionOut_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "FusionObject.pb.h"
#include "LaneMarker.pb.h"
#include "RGFInfo.pb.h"
#include "EgoMotion.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_FusionOut_2eproto 

namespace protobuf_FusionOut_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_FusionOut_2eproto
namespace FeiMa {
namespace FusionOut {
class FusionOut;
class FusionOutDefaultTypeInternal;
extern FusionOutDefaultTypeInternal _FusionOut_default_instance_;
}  // namespace FusionOut
}  // namespace FeiMa
namespace google {
namespace protobuf {
template<> ::FeiMa::FusionOut::FusionOut* Arena::CreateMaybeMessage<::FeiMa::FusionOut::FusionOut>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace FeiMa {
namespace FusionOut {

// ===================================================================

class FusionOut : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FeiMa.FusionOut.FusionOut) */ {
 public:
  FusionOut();
  virtual ~FusionOut();

  FusionOut(const FusionOut& from);

  inline FusionOut& operator=(const FusionOut& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FusionOut(FusionOut&& from) noexcept
    : FusionOut() {
    *this = ::std::move(from);
  }

  inline FusionOut& operator=(FusionOut&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FusionOut& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FusionOut* internal_default_instance() {
    return reinterpret_cast<const FusionOut*>(
               &_FusionOut_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FusionOut* other);
  friend void swap(FusionOut& a, FusionOut& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FusionOut* New() const final {
    return CreateMaybeMessage<FusionOut>(NULL);
  }

  FusionOut* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FusionOut>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FusionOut& from);
  void MergeFrom(const FusionOut& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FusionOut* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .FeiMa.FusionObject.FusionObjects fusion = 1;
  bool has_fusion() const;
  void clear_fusion();
  static const int kFusionFieldNumber = 1;
  private:
  const ::FeiMa::FusionObject::FusionObjects& _internal_fusion() const;
  public:
  const ::FeiMa::FusionObject::FusionObjects& fusion() const;
  ::FeiMa::FusionObject::FusionObjects* release_fusion();
  ::FeiMa::FusionObject::FusionObjects* mutable_fusion();
  void set_allocated_fusion(::FeiMa::FusionObject::FusionObjects* fusion);

  // optional .FeiMa.LaneMarker.LaneMarkers lane = 2;
  bool has_lane() const;
  void clear_lane();
  static const int kLaneFieldNumber = 2;
  private:
  const ::FeiMa::LaneMarker::LaneMarkers& _internal_lane() const;
  public:
  const ::FeiMa::LaneMarker::LaneMarkers& lane() const;
  ::FeiMa::LaneMarker::LaneMarkers* release_lane();
  ::FeiMa::LaneMarker::LaneMarkers* mutable_lane();
  void set_allocated_lane(::FeiMa::LaneMarker::LaneMarkers* lane);

  // optional .FeiMa.RGFInfo.RGFInfos rgf = 3;
  bool has_rgf() const;
  void clear_rgf();
  static const int kRgfFieldNumber = 3;
  private:
  const ::FeiMa::RGFInfo::RGFInfos& _internal_rgf() const;
  public:
  const ::FeiMa::RGFInfo::RGFInfos& rgf() const;
  ::FeiMa::RGFInfo::RGFInfos* release_rgf();
  ::FeiMa::RGFInfo::RGFInfos* mutable_rgf();
  void set_allocated_rgf(::FeiMa::RGFInfo::RGFInfos* rgf);

  // optional .FeiMa.EgoMotion.VehicleEgoMotion ego_motion = 4;
  bool has_ego_motion() const;
  void clear_ego_motion();
  static const int kEgoMotionFieldNumber = 4;
  private:
  const ::FeiMa::EgoMotion::VehicleEgoMotion& _internal_ego_motion() const;
  public:
  const ::FeiMa::EgoMotion::VehicleEgoMotion& ego_motion() const;
  ::FeiMa::EgoMotion::VehicleEgoMotion* release_ego_motion();
  ::FeiMa::EgoMotion::VehicleEgoMotion* mutable_ego_motion();
  void set_allocated_ego_motion(::FeiMa::EgoMotion::VehicleEgoMotion* ego_motion);

  // optional uint64 camera_timestamp = 5;
  bool has_camera_timestamp() const;
  void clear_camera_timestamp();
  static const int kCameraTimestampFieldNumber = 5;
  ::google::protobuf::uint64 camera_timestamp() const;
  void set_camera_timestamp(::google::protobuf::uint64 value);

  // optional uint64 radar_timestamp = 6;
  bool has_radar_timestamp() const;
  void clear_radar_timestamp();
  static const int kRadarTimestampFieldNumber = 6;
  ::google::protobuf::uint64 radar_timestamp() const;
  void set_radar_timestamp(::google::protobuf::uint64 value);

  // optional uint64 fusion_timestamp = 7;
  bool has_fusion_timestamp() const;
  void clear_fusion_timestamp();
  static const int kFusionTimestampFieldNumber = 7;
  ::google::protobuf::uint64 fusion_timestamp() const;
  void set_fusion_timestamp(::google::protobuf::uint64 value);

  // optional uint64 rgf_timestamp = 8;
  bool has_rgf_timestamp() const;
  void clear_rgf_timestamp();
  static const int kRgfTimestampFieldNumber = 8;
  ::google::protobuf::uint64 rgf_timestamp() const;
  void set_rgf_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:FeiMa.FusionOut.FusionOut)
 private:
  void set_has_fusion();
  void clear_has_fusion();
  void set_has_lane();
  void clear_has_lane();
  void set_has_rgf();
  void clear_has_rgf();
  void set_has_ego_motion();
  void clear_has_ego_motion();
  void set_has_camera_timestamp();
  void clear_has_camera_timestamp();
  void set_has_radar_timestamp();
  void clear_has_radar_timestamp();
  void set_has_fusion_timestamp();
  void clear_has_fusion_timestamp();
  void set_has_rgf_timestamp();
  void clear_has_rgf_timestamp();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::FeiMa::FusionObject::FusionObjects* fusion_;
  ::FeiMa::LaneMarker::LaneMarkers* lane_;
  ::FeiMa::RGFInfo::RGFInfos* rgf_;
  ::FeiMa::EgoMotion::VehicleEgoMotion* ego_motion_;
  ::google::protobuf::uint64 camera_timestamp_;
  ::google::protobuf::uint64 radar_timestamp_;
  ::google::protobuf::uint64 fusion_timestamp_;
  ::google::protobuf::uint64 rgf_timestamp_;
  friend struct ::protobuf_FusionOut_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FusionOut

// optional .FeiMa.FusionObject.FusionObjects fusion = 1;
inline bool FusionOut::has_fusion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FusionOut::set_has_fusion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FusionOut::clear_has_fusion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::FeiMa::FusionObject::FusionObjects& FusionOut::_internal_fusion() const {
  return *fusion_;
}
inline const ::FeiMa::FusionObject::FusionObjects& FusionOut::fusion() const {
  const ::FeiMa::FusionObject::FusionObjects* p = fusion_;
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.fusion)
  return p != NULL ? *p : *reinterpret_cast<const ::FeiMa::FusionObject::FusionObjects*>(
      &::FeiMa::FusionObject::_FusionObjects_default_instance_);
}
inline ::FeiMa::FusionObject::FusionObjects* FusionOut::release_fusion() {
  // @@protoc_insertion_point(field_release:FeiMa.FusionOut.FusionOut.fusion)
  clear_has_fusion();
  ::FeiMa::FusionObject::FusionObjects* temp = fusion_;
  fusion_ = NULL;
  return temp;
}
inline ::FeiMa::FusionObject::FusionObjects* FusionOut::mutable_fusion() {
  set_has_fusion();
  if (fusion_ == NULL) {
    auto* p = CreateMaybeMessage<::FeiMa::FusionObject::FusionObjects>(GetArenaNoVirtual());
    fusion_ = p;
  }
  // @@protoc_insertion_point(field_mutable:FeiMa.FusionOut.FusionOut.fusion)
  return fusion_;
}
inline void FusionOut::set_allocated_fusion(::FeiMa::FusionObject::FusionObjects* fusion) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(fusion_);
  }
  if (fusion) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      fusion = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, fusion, submessage_arena);
    }
    set_has_fusion();
  } else {
    clear_has_fusion();
  }
  fusion_ = fusion;
  // @@protoc_insertion_point(field_set_allocated:FeiMa.FusionOut.FusionOut.fusion)
}

// optional .FeiMa.LaneMarker.LaneMarkers lane = 2;
inline bool FusionOut::has_lane() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FusionOut::set_has_lane() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FusionOut::clear_has_lane() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::FeiMa::LaneMarker::LaneMarkers& FusionOut::_internal_lane() const {
  return *lane_;
}
inline const ::FeiMa::LaneMarker::LaneMarkers& FusionOut::lane() const {
  const ::FeiMa::LaneMarker::LaneMarkers* p = lane_;
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.lane)
  return p != NULL ? *p : *reinterpret_cast<const ::FeiMa::LaneMarker::LaneMarkers*>(
      &::FeiMa::LaneMarker::_LaneMarkers_default_instance_);
}
inline ::FeiMa::LaneMarker::LaneMarkers* FusionOut::release_lane() {
  // @@protoc_insertion_point(field_release:FeiMa.FusionOut.FusionOut.lane)
  clear_has_lane();
  ::FeiMa::LaneMarker::LaneMarkers* temp = lane_;
  lane_ = NULL;
  return temp;
}
inline ::FeiMa::LaneMarker::LaneMarkers* FusionOut::mutable_lane() {
  set_has_lane();
  if (lane_ == NULL) {
    auto* p = CreateMaybeMessage<::FeiMa::LaneMarker::LaneMarkers>(GetArenaNoVirtual());
    lane_ = p;
  }
  // @@protoc_insertion_point(field_mutable:FeiMa.FusionOut.FusionOut.lane)
  return lane_;
}
inline void FusionOut::set_allocated_lane(::FeiMa::LaneMarker::LaneMarkers* lane) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(lane_);
  }
  if (lane) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      lane = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, lane, submessage_arena);
    }
    set_has_lane();
  } else {
    clear_has_lane();
  }
  lane_ = lane;
  // @@protoc_insertion_point(field_set_allocated:FeiMa.FusionOut.FusionOut.lane)
}

// optional .FeiMa.RGFInfo.RGFInfos rgf = 3;
inline bool FusionOut::has_rgf() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FusionOut::set_has_rgf() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FusionOut::clear_has_rgf() {
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::FeiMa::RGFInfo::RGFInfos& FusionOut::_internal_rgf() const {
  return *rgf_;
}
inline const ::FeiMa::RGFInfo::RGFInfos& FusionOut::rgf() const {
  const ::FeiMa::RGFInfo::RGFInfos* p = rgf_;
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.rgf)
  return p != NULL ? *p : *reinterpret_cast<const ::FeiMa::RGFInfo::RGFInfos*>(
      &::FeiMa::RGFInfo::_RGFInfos_default_instance_);
}
inline ::FeiMa::RGFInfo::RGFInfos* FusionOut::release_rgf() {
  // @@protoc_insertion_point(field_release:FeiMa.FusionOut.FusionOut.rgf)
  clear_has_rgf();
  ::FeiMa::RGFInfo::RGFInfos* temp = rgf_;
  rgf_ = NULL;
  return temp;
}
inline ::FeiMa::RGFInfo::RGFInfos* FusionOut::mutable_rgf() {
  set_has_rgf();
  if (rgf_ == NULL) {
    auto* p = CreateMaybeMessage<::FeiMa::RGFInfo::RGFInfos>(GetArenaNoVirtual());
    rgf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:FeiMa.FusionOut.FusionOut.rgf)
  return rgf_;
}
inline void FusionOut::set_allocated_rgf(::FeiMa::RGFInfo::RGFInfos* rgf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(rgf_);
  }
  if (rgf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      rgf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, rgf, submessage_arena);
    }
    set_has_rgf();
  } else {
    clear_has_rgf();
  }
  rgf_ = rgf;
  // @@protoc_insertion_point(field_set_allocated:FeiMa.FusionOut.FusionOut.rgf)
}

// optional .FeiMa.EgoMotion.VehicleEgoMotion ego_motion = 4;
inline bool FusionOut::has_ego_motion() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void FusionOut::set_has_ego_motion() {
  _has_bits_[0] |= 0x00000008u;
}
inline void FusionOut::clear_has_ego_motion() {
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::FeiMa::EgoMotion::VehicleEgoMotion& FusionOut::_internal_ego_motion() const {
  return *ego_motion_;
}
inline const ::FeiMa::EgoMotion::VehicleEgoMotion& FusionOut::ego_motion() const {
  const ::FeiMa::EgoMotion::VehicleEgoMotion* p = ego_motion_;
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.ego_motion)
  return p != NULL ? *p : *reinterpret_cast<const ::FeiMa::EgoMotion::VehicleEgoMotion*>(
      &::FeiMa::EgoMotion::_VehicleEgoMotion_default_instance_);
}
inline ::FeiMa::EgoMotion::VehicleEgoMotion* FusionOut::release_ego_motion() {
  // @@protoc_insertion_point(field_release:FeiMa.FusionOut.FusionOut.ego_motion)
  clear_has_ego_motion();
  ::FeiMa::EgoMotion::VehicleEgoMotion* temp = ego_motion_;
  ego_motion_ = NULL;
  return temp;
}
inline ::FeiMa::EgoMotion::VehicleEgoMotion* FusionOut::mutable_ego_motion() {
  set_has_ego_motion();
  if (ego_motion_ == NULL) {
    auto* p = CreateMaybeMessage<::FeiMa::EgoMotion::VehicleEgoMotion>(GetArenaNoVirtual());
    ego_motion_ = p;
  }
  // @@protoc_insertion_point(field_mutable:FeiMa.FusionOut.FusionOut.ego_motion)
  return ego_motion_;
}
inline void FusionOut::set_allocated_ego_motion(::FeiMa::EgoMotion::VehicleEgoMotion* ego_motion) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(ego_motion_);
  }
  if (ego_motion) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      ego_motion = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, ego_motion, submessage_arena);
    }
    set_has_ego_motion();
  } else {
    clear_has_ego_motion();
  }
  ego_motion_ = ego_motion;
  // @@protoc_insertion_point(field_set_allocated:FeiMa.FusionOut.FusionOut.ego_motion)
}

// optional uint64 camera_timestamp = 5;
inline bool FusionOut::has_camera_timestamp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void FusionOut::set_has_camera_timestamp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void FusionOut::clear_has_camera_timestamp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void FusionOut::clear_camera_timestamp() {
  camera_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_camera_timestamp();
}
inline ::google::protobuf::uint64 FusionOut::camera_timestamp() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.camera_timestamp)
  return camera_timestamp_;
}
inline void FusionOut::set_camera_timestamp(::google::protobuf::uint64 value) {
  set_has_camera_timestamp();
  camera_timestamp_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionOut.FusionOut.camera_timestamp)
}

// optional uint64 radar_timestamp = 6;
inline bool FusionOut::has_radar_timestamp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void FusionOut::set_has_radar_timestamp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void FusionOut::clear_has_radar_timestamp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void FusionOut::clear_radar_timestamp() {
  radar_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_radar_timestamp();
}
inline ::google::protobuf::uint64 FusionOut::radar_timestamp() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.radar_timestamp)
  return radar_timestamp_;
}
inline void FusionOut::set_radar_timestamp(::google::protobuf::uint64 value) {
  set_has_radar_timestamp();
  radar_timestamp_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionOut.FusionOut.radar_timestamp)
}

// optional uint64 fusion_timestamp = 7;
inline bool FusionOut::has_fusion_timestamp() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void FusionOut::set_has_fusion_timestamp() {
  _has_bits_[0] |= 0x00000040u;
}
inline void FusionOut::clear_has_fusion_timestamp() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void FusionOut::clear_fusion_timestamp() {
  fusion_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_fusion_timestamp();
}
inline ::google::protobuf::uint64 FusionOut::fusion_timestamp() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.fusion_timestamp)
  return fusion_timestamp_;
}
inline void FusionOut::set_fusion_timestamp(::google::protobuf::uint64 value) {
  set_has_fusion_timestamp();
  fusion_timestamp_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionOut.FusionOut.fusion_timestamp)
}

// optional uint64 rgf_timestamp = 8;
inline bool FusionOut::has_rgf_timestamp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void FusionOut::set_has_rgf_timestamp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void FusionOut::clear_has_rgf_timestamp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void FusionOut::clear_rgf_timestamp() {
  rgf_timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_rgf_timestamp();
}
inline ::google::protobuf::uint64 FusionOut::rgf_timestamp() const {
  // @@protoc_insertion_point(field_get:FeiMa.FusionOut.FusionOut.rgf_timestamp)
  return rgf_timestamp_;
}
inline void FusionOut::set_rgf_timestamp(::google::protobuf::uint64 value) {
  set_has_rgf_timestamp();
  rgf_timestamp_ = value;
  // @@protoc_insertion_point(field_set:FeiMa.FusionOut.FusionOut.rgf_timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace FusionOut
}  // namespace FeiMa

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_FusionOut_2eproto
