// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UltrasonicInfo.proto

#ifndef PROTOBUF_INCLUDED_UltrasonicInfo_2eproto
#define PROTOBUF_INCLUDED_UltrasonicInfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_UltrasonicInfo_2eproto 

namespace protobuf_UltrasonicInfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_UltrasonicInfo_2eproto
namespace Parking {
namespace UltrasonicInfo {
class APosition2D_UPS;
class APosition2D_UPSDefaultTypeInternal;
extern APosition2D_UPSDefaultTypeInternal _APosition2D_UPS_default_instance_;
class AUSSPS_USS;
class AUSSPS_USSDefaultTypeInternal;
extern AUSSPS_USSDefaultTypeInternal _AUSSPS_USS_default_instance_;
class Pos2DType;
class Pos2DTypeDefaultTypeInternal;
extern Pos2DTypeDefaultTypeInternal _Pos2DType_default_instance_;
class RadarObj;
class RadarObjDefaultTypeInternal;
extern RadarObjDefaultTypeInternal _RadarObj_default_instance_;
class USSObject;
class USSObjectDefaultTypeInternal;
extern USSObjectDefaultTypeInternal _USSObject_default_instance_;
class UltrasonicInfo;
class UltrasonicInfoDefaultTypeInternal;
extern UltrasonicInfoDefaultTypeInternal _UltrasonicInfo_default_instance_;
class Uss_Data;
class Uss_DataDefaultTypeInternal;
extern Uss_DataDefaultTypeInternal _Uss_Data_default_instance_;
class Ussslotlist;
class UssslotlistDefaultTypeInternal;
extern UssslotlistDefaultTypeInternal _Ussslotlist_default_instance_;
}  // namespace UltrasonicInfo
}  // namespace Parking
namespace google {
namespace protobuf {
template<> ::Parking::UltrasonicInfo::APosition2D_UPS* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::APosition2D_UPS>(Arena*);
template<> ::Parking::UltrasonicInfo::AUSSPS_USS* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::AUSSPS_USS>(Arena*);
template<> ::Parking::UltrasonicInfo::Pos2DType* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::Pos2DType>(Arena*);
template<> ::Parking::UltrasonicInfo::RadarObj* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::RadarObj>(Arena*);
template<> ::Parking::UltrasonicInfo::USSObject* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::USSObject>(Arena*);
template<> ::Parking::UltrasonicInfo::UltrasonicInfo* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::UltrasonicInfo>(Arena*);
template<> ::Parking::UltrasonicInfo::Uss_Data* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::Uss_Data>(Arena*);
template<> ::Parking::UltrasonicInfo::Ussslotlist* Arena::CreateMaybeMessage<::Parking::UltrasonicInfo::Ussslotlist>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Parking {
namespace UltrasonicInfo {

enum tObjType_USS {
  Unkwon = 0,
  Low = 1,
  High = 2,
  Curb = 3
};
bool tObjType_USS_IsValid(int value);
const tObjType_USS tObjType_USS_MIN = Unkwon;
const tObjType_USS tObjType_USS_MAX = Curb;
const int tObjType_USS_ARRAYSIZE = tObjType_USS_MAX + 1;

const ::google::protobuf::EnumDescriptor* tObjType_USS_descriptor();
inline const ::std::string& tObjType_USS_Name(tObjType_USS value) {
  return ::google::protobuf::internal::NameOfEnum(
    tObjType_USS_descriptor(), value);
}
inline bool tObjType_USS_Parse(
    const ::std::string& name, tObjType_USS* value) {
  return ::google::protobuf::internal::ParseNamedEnum<tObjType_USS>(
    tObjType_USS_descriptor(), name, value);
}
enum tSlotType_USS {
  Vertical = 0,
  Horizontal = 1,
  Slanting = 2,
  APA_SLOT_TYPE_INVALID = 3
};
bool tSlotType_USS_IsValid(int value);
const tSlotType_USS tSlotType_USS_MIN = Vertical;
const tSlotType_USS tSlotType_USS_MAX = APA_SLOT_TYPE_INVALID;
const int tSlotType_USS_ARRAYSIZE = tSlotType_USS_MAX + 1;

const ::google::protobuf::EnumDescriptor* tSlotType_USS_descriptor();
inline const ::std::string& tSlotType_USS_Name(tSlotType_USS value) {
  return ::google::protobuf::internal::NameOfEnum(
    tSlotType_USS_descriptor(), value);
}
inline bool tSlotType_USS_Parse(
    const ::std::string& name, tSlotType_USS* value) {
  return ::google::protobuf::internal::ParseNamedEnum<tSlotType_USS>(
    tSlotType_USS_descriptor(), name, value);
}
// ===================================================================

class Pos2DType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.Pos2DType) */ {
 public:
  Pos2DType();
  virtual ~Pos2DType();

  Pos2DType(const Pos2DType& from);

  inline Pos2DType& operator=(const Pos2DType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Pos2DType(Pos2DType&& from) noexcept
    : Pos2DType() {
    *this = ::std::move(from);
  }

  inline Pos2DType& operator=(Pos2DType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pos2DType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Pos2DType* internal_default_instance() {
    return reinterpret_cast<const Pos2DType*>(
               &_Pos2DType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Pos2DType* other);
  friend void swap(Pos2DType& a, Pos2DType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Pos2DType* New() const final {
    return CreateMaybeMessage<Pos2DType>(NULL);
  }

  Pos2DType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Pos2DType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Pos2DType& from);
  void MergeFrom(const Pos2DType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Pos2DType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // optional sint32 y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.Pos2DType)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class APosition2D_UPS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.APosition2D_UPS) */ {
 public:
  APosition2D_UPS();
  virtual ~APosition2D_UPS();

  APosition2D_UPS(const APosition2D_UPS& from);

  inline APosition2D_UPS& operator=(const APosition2D_UPS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  APosition2D_UPS(APosition2D_UPS&& from) noexcept
    : APosition2D_UPS() {
    *this = ::std::move(from);
  }

  inline APosition2D_UPS& operator=(APosition2D_UPS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APosition2D_UPS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const APosition2D_UPS* internal_default_instance() {
    return reinterpret_cast<const APosition2D_UPS*>(
               &_APosition2D_UPS_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(APosition2D_UPS* other);
  friend void swap(APosition2D_UPS& a, APosition2D_UPS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline APosition2D_UPS* New() const final {
    return CreateMaybeMessage<APosition2D_UPS>(NULL);
  }

  APosition2D_UPS* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<APosition2D_UPS>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const APosition2D_UPS& from);
  void MergeFrom(const APosition2D_UPS& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(APosition2D_UPS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // optional sint32 y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.APosition2D_UPS)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RadarObj : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.RadarObj) */ {
 public:
  RadarObj();
  virtual ~RadarObj();

  RadarObj(const RadarObj& from);

  inline RadarObj& operator=(const RadarObj& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RadarObj(RadarObj&& from) noexcept
    : RadarObj() {
    *this = ::std::move(from);
  }

  inline RadarObj& operator=(RadarObj&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarObj& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RadarObj* internal_default_instance() {
    return reinterpret_cast<const RadarObj*>(
               &_RadarObj_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RadarObj* other);
  friend void swap(RadarObj& a, RadarObj& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RadarObj* New() const final {
    return CreateMaybeMessage<RadarObj>(NULL);
  }

  RadarObj* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RadarObj>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RadarObj& from);
  void MergeFrom(const RadarObj& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RadarObj* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Parking.UltrasonicInfo.Pos2DType radar_object = 1;
  int radar_object_size() const;
  void clear_radar_object();
  static const int kRadarObjectFieldNumber = 1;
  ::Parking::UltrasonicInfo::Pos2DType* mutable_radar_object(int index);
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::Pos2DType >*
      mutable_radar_object();
  const ::Parking::UltrasonicInfo::Pos2DType& radar_object(int index) const;
  ::Parking::UltrasonicInfo::Pos2DType* add_radar_object();
  const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::Pos2DType >&
      radar_object() const;

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.RadarObj)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::Pos2DType > radar_object_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Uss_Data : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.Uss_Data) */ {
 public:
  Uss_Data();
  virtual ~Uss_Data();

  Uss_Data(const Uss_Data& from);

  inline Uss_Data& operator=(const Uss_Data& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Uss_Data(Uss_Data&& from) noexcept
    : Uss_Data() {
    *this = ::std::move(from);
  }

  inline Uss_Data& operator=(Uss_Data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Uss_Data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Uss_Data* internal_default_instance() {
    return reinterpret_cast<const Uss_Data*>(
               &_Uss_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Uss_Data* other);
  friend void swap(Uss_Data& a, Uss_Data& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Uss_Data* New() const final {
    return CreateMaybeMessage<Uss_Data>(NULL);
  }

  Uss_Data* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Uss_Data>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Uss_Data& from);
  void MergeFrom(const Uss_Data& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Uss_Data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 front0 = 1;
  bool has_front0() const;
  void clear_front0();
  static const int kFront0FieldNumber = 1;
  ::google::protobuf::uint32 front0() const;
  void set_front0(::google::protobuf::uint32 value);

  // optional uint32 front1 = 2;
  bool has_front1() const;
  void clear_front1();
  static const int kFront1FieldNumber = 2;
  ::google::protobuf::uint32 front1() const;
  void set_front1(::google::protobuf::uint32 value);

  // optional uint32 front2 = 3;
  bool has_front2() const;
  void clear_front2();
  static const int kFront2FieldNumber = 3;
  ::google::protobuf::uint32 front2() const;
  void set_front2(::google::protobuf::uint32 value);

  // optional uint32 front3 = 4;
  bool has_front3() const;
  void clear_front3();
  static const int kFront3FieldNumber = 4;
  ::google::protobuf::uint32 front3() const;
  void set_front3(::google::protobuf::uint32 value);

  // optional uint32 rear0 = 5;
  bool has_rear0() const;
  void clear_rear0();
  static const int kRear0FieldNumber = 5;
  ::google::protobuf::uint32 rear0() const;
  void set_rear0(::google::protobuf::uint32 value);

  // optional uint32 rear1 = 6;
  bool has_rear1() const;
  void clear_rear1();
  static const int kRear1FieldNumber = 6;
  ::google::protobuf::uint32 rear1() const;
  void set_rear1(::google::protobuf::uint32 value);

  // optional uint32 rear2 = 7;
  bool has_rear2() const;
  void clear_rear2();
  static const int kRear2FieldNumber = 7;
  ::google::protobuf::uint32 rear2() const;
  void set_rear2(::google::protobuf::uint32 value);

  // optional uint32 rear3 = 8;
  bool has_rear3() const;
  void clear_rear3();
  static const int kRear3FieldNumber = 8;
  ::google::protobuf::uint32 rear3() const;
  void set_rear3(::google::protobuf::uint32 value);

  // optional uint32 left_side0 = 9;
  bool has_left_side0() const;
  void clear_left_side0();
  static const int kLeftSide0FieldNumber = 9;
  ::google::protobuf::uint32 left_side0() const;
  void set_left_side0(::google::protobuf::uint32 value);

  // optional uint32 left_side1 = 10;
  bool has_left_side1() const;
  void clear_left_side1();
  static const int kLeftSide1FieldNumber = 10;
  ::google::protobuf::uint32 left_side1() const;
  void set_left_side1(::google::protobuf::uint32 value);

  // optional uint32 right_side0 = 11;
  bool has_right_side0() const;
  void clear_right_side0();
  static const int kRightSide0FieldNumber = 11;
  ::google::protobuf::uint32 right_side0() const;
  void set_right_side0(::google::protobuf::uint32 value);

  // optional uint32 right_side1 = 12;
  bool has_right_side1() const;
  void clear_right_side1();
  static const int kRightSide1FieldNumber = 12;
  ::google::protobuf::uint32 right_side1() const;
  void set_right_side1(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.Uss_Data)
 private:
  void set_has_front0();
  void clear_has_front0();
  void set_has_front1();
  void clear_has_front1();
  void set_has_front2();
  void clear_has_front2();
  void set_has_front3();
  void clear_has_front3();
  void set_has_rear0();
  void clear_has_rear0();
  void set_has_rear1();
  void clear_has_rear1();
  void set_has_rear2();
  void clear_has_rear2();
  void set_has_rear3();
  void clear_has_rear3();
  void set_has_left_side0();
  void clear_has_left_side0();
  void set_has_left_side1();
  void clear_has_left_side1();
  void set_has_right_side0();
  void clear_has_right_side0();
  void set_has_right_side1();
  void clear_has_right_side1();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 front0_;
  ::google::protobuf::uint32 front1_;
  ::google::protobuf::uint32 front2_;
  ::google::protobuf::uint32 front3_;
  ::google::protobuf::uint32 rear0_;
  ::google::protobuf::uint32 rear1_;
  ::google::protobuf::uint32 rear2_;
  ::google::protobuf::uint32 rear3_;
  ::google::protobuf::uint32 left_side0_;
  ::google::protobuf::uint32 left_side1_;
  ::google::protobuf::uint32 right_side0_;
  ::google::protobuf::uint32 right_side1_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class USSObject : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.USSObject) */ {
 public:
  USSObject();
  virtual ~USSObject();

  USSObject(const USSObject& from);

  inline USSObject& operator=(const USSObject& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  USSObject(USSObject&& from) noexcept
    : USSObject() {
    *this = ::std::move(from);
  }

  inline USSObject& operator=(USSObject&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const USSObject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const USSObject* internal_default_instance() {
    return reinterpret_cast<const USSObject*>(
               &_USSObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(USSObject* other);
  friend void swap(USSObject& a, USSObject& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline USSObject* New() const final {
    return CreateMaybeMessage<USSObject>(NULL);
  }

  USSObject* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<USSObject>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const USSObject& from);
  void MergeFrom(const USSObject& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(USSObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 uss_state = 1;
  int uss_state_size() const;
  void clear_uss_state();
  static const int kUssStateFieldNumber = 1;
  ::google::protobuf::uint32 uss_state(int index) const;
  void set_uss_state(int index, ::google::protobuf::uint32 value);
  void add_uss_state(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      uss_state() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_uss_state();

  // repeated .Parking.UltrasonicInfo.RadarObj region = 3;
  int region_size() const;
  void clear_region();
  static const int kRegionFieldNumber = 3;
  ::Parking::UltrasonicInfo::RadarObj* mutable_region(int index);
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::RadarObj >*
      mutable_region();
  const ::Parking::UltrasonicInfo::RadarObj& region(int index) const;
  ::Parking::UltrasonicInfo::RadarObj* add_region();
  const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::RadarObj >&
      region() const;

  // optional .Parking.UltrasonicInfo.Pos2DType obj_point_a = 5;
  bool has_obj_point_a() const;
  void clear_obj_point_a();
  static const int kObjPointAFieldNumber = 5;
  private:
  const ::Parking::UltrasonicInfo::Pos2DType& _internal_obj_point_a() const;
  public:
  const ::Parking::UltrasonicInfo::Pos2DType& obj_point_a() const;
  ::Parking::UltrasonicInfo::Pos2DType* release_obj_point_a();
  ::Parking::UltrasonicInfo::Pos2DType* mutable_obj_point_a();
  void set_allocated_obj_point_a(::Parking::UltrasonicInfo::Pos2DType* obj_point_a);

  // optional .Parking.UltrasonicInfo.Pos2DType obj_point_b = 6;
  bool has_obj_point_b() const;
  void clear_obj_point_b();
  static const int kObjPointBFieldNumber = 6;
  private:
  const ::Parking::UltrasonicInfo::Pos2DType& _internal_obj_point_b() const;
  public:
  const ::Parking::UltrasonicInfo::Pos2DType& obj_point_b() const;
  ::Parking::UltrasonicInfo::Pos2DType* release_obj_point_b();
  ::Parking::UltrasonicInfo::Pos2DType* mutable_obj_point_b();
  void set_allocated_obj_point_b(::Parking::UltrasonicInfo::Pos2DType* obj_point_b);

  // optional uint32 obj_counter = 2;
  bool has_obj_counter() const;
  void clear_obj_counter();
  static const int kObjCounterFieldNumber = 2;
  ::google::protobuf::uint32 obj_counter() const;
  void set_obj_counter(::google::protobuf::uint32 value);

  // optional uint32 id = 4;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 4;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional .Parking.UltrasonicInfo.tObjType_USS obj_type = 7;
  bool has_obj_type() const;
  void clear_obj_type();
  static const int kObjTypeFieldNumber = 7;
  ::Parking::UltrasonicInfo::tObjType_USS obj_type() const;
  void set_obj_type(::Parking::UltrasonicInfo::tObjType_USS value);

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.USSObject)
 private:
  void set_has_obj_counter();
  void clear_has_obj_counter();
  void set_has_id();
  void clear_has_id();
  void set_has_obj_point_a();
  void clear_has_obj_point_a();
  void set_has_obj_point_b();
  void clear_has_obj_point_b();
  void set_has_obj_type();
  void clear_has_obj_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > uss_state_;
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::RadarObj > region_;
  ::Parking::UltrasonicInfo::Pos2DType* obj_point_a_;
  ::Parking::UltrasonicInfo::Pos2DType* obj_point_b_;
  ::google::protobuf::uint32 obj_counter_;
  ::google::protobuf::uint32 id_;
  int obj_type_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AUSSPS_USS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.AUSSPS_USS) */ {
 public:
  AUSSPS_USS();
  virtual ~AUSSPS_USS();

  AUSSPS_USS(const AUSSPS_USS& from);

  inline AUSSPS_USS& operator=(const AUSSPS_USS& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AUSSPS_USS(AUSSPS_USS&& from) noexcept
    : AUSSPS_USS() {
    *this = ::std::move(from);
  }

  inline AUSSPS_USS& operator=(AUSSPS_USS&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AUSSPS_USS& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AUSSPS_USS* internal_default_instance() {
    return reinterpret_cast<const AUSSPS_USS*>(
               &_AUSSPS_USS_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(AUSSPS_USS* other);
  friend void swap(AUSSPS_USS& a, AUSSPS_USS& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AUSSPS_USS* New() const final {
    return CreateMaybeMessage<AUSSPS_USS>(NULL);
  }

  AUSSPS_USS* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AUSSPS_USS>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AUSSPS_USS& from);
  void MergeFrom(const AUSSPS_USS& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AUSSPS_USS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Parking.UltrasonicInfo.APosition2D_UPS corner_points = 2;
  int corner_points_size() const;
  void clear_corner_points();
  static const int kCornerPointsFieldNumber = 2;
  ::Parking::UltrasonicInfo::APosition2D_UPS* mutable_corner_points(int index);
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::APosition2D_UPS >*
      mutable_corner_points();
  const ::Parking::UltrasonicInfo::APosition2D_UPS& corner_points(int index) const;
  ::Parking::UltrasonicInfo::APosition2D_UPS* add_corner_points();
  const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::APosition2D_UPS >&
      corner_points() const;

  // optional uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint32 slot_side = 3;
  bool has_slot_side() const;
  void clear_slot_side();
  static const int kSlotSideFieldNumber = 3;
  ::google::protobuf::uint32 slot_side() const;
  void set_slot_side(::google::protobuf::uint32 value);

  // optional sint32 sita = 4;
  bool has_sita() const;
  void clear_sita();
  static const int kSitaFieldNumber = 4;
  ::google::protobuf::int32 sita() const;
  void set_sita(::google::protobuf::int32 value);

  // optional sint32 sita_0 = 5;
  bool has_sita_0() const;
  void clear_sita_0();
  static const int kSita0FieldNumber = 5;
  ::google::protobuf::int32 sita_0() const;
  void set_sita_0(::google::protobuf::int32 value);

  // optional sint32 sita_1 = 6;
  bool has_sita_1() const;
  void clear_sita_1();
  static const int kSita1FieldNumber = 6;
  ::google::protobuf::int32 sita_1() const;
  void set_sita_1(::google::protobuf::int32 value);

  // optional float line_a = 7;
  bool has_line_a() const;
  void clear_line_a();
  static const int kLineAFieldNumber = 7;
  float line_a() const;
  void set_line_a(float value);

  // optional float line_b = 8;
  bool has_line_b() const;
  void clear_line_b();
  static const int kLineBFieldNumber = 8;
  float line_b() const;
  void set_line_b(float value);

  // optional .Parking.UltrasonicInfo.tSlotType_USS slot_type = 9;
  bool has_slot_type() const;
  void clear_slot_type();
  static const int kSlotTypeFieldNumber = 9;
  ::Parking::UltrasonicInfo::tSlotType_USS slot_type() const;
  void set_slot_type(::Parking::UltrasonicInfo::tSlotType_USS value);

  // optional bool slot_update_flag = 10;
  bool has_slot_update_flag() const;
  void clear_slot_update_flag();
  static const int kSlotUpdateFlagFieldNumber = 10;
  bool slot_update_flag() const;
  void set_slot_update_flag(bool value);

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.AUSSPS_USS)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_slot_side();
  void clear_has_slot_side();
  void set_has_sita();
  void clear_has_sita();
  void set_has_sita_0();
  void clear_has_sita_0();
  void set_has_sita_1();
  void clear_has_sita_1();
  void set_has_line_a();
  void clear_has_line_a();
  void set_has_line_b();
  void clear_has_line_b();
  void set_has_slot_type();
  void clear_has_slot_type();
  void set_has_slot_update_flag();
  void clear_has_slot_update_flag();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::APosition2D_UPS > corner_points_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 slot_side_;
  ::google::protobuf::int32 sita_;
  ::google::protobuf::int32 sita_0_;
  ::google::protobuf::int32 sita_1_;
  float line_a_;
  float line_b_;
  int slot_type_;
  bool slot_update_flag_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Ussslotlist : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.Ussslotlist) */ {
 public:
  Ussslotlist();
  virtual ~Ussslotlist();

  Ussslotlist(const Ussslotlist& from);

  inline Ussslotlist& operator=(const Ussslotlist& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ussslotlist(Ussslotlist&& from) noexcept
    : Ussslotlist() {
    *this = ::std::move(from);
  }

  inline Ussslotlist& operator=(Ussslotlist&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Ussslotlist& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ussslotlist* internal_default_instance() {
    return reinterpret_cast<const Ussslotlist*>(
               &_Ussslotlist_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Ussslotlist* other);
  friend void swap(Ussslotlist& a, Ussslotlist& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ussslotlist* New() const final {
    return CreateMaybeMessage<Ussslotlist>(NULL);
  }

  Ussslotlist* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Ussslotlist>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Ussslotlist& from);
  void MergeFrom(const Ussslotlist& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ussslotlist* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Parking.UltrasonicInfo.AUSSPS_USS parking_slots = 5;
  int parking_slots_size() const;
  void clear_parking_slots();
  static const int kParkingSlotsFieldNumber = 5;
  ::Parking::UltrasonicInfo::AUSSPS_USS* mutable_parking_slots(int index);
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::AUSSPS_USS >*
      mutable_parking_slots();
  const ::Parking::UltrasonicInfo::AUSSPS_USS& parking_slots(int index) const;
  ::Parking::UltrasonicInfo::AUSSPS_USS* add_parking_slots();
  const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::AUSSPS_USS >&
      parking_slots() const;

  // optional uint64 time_stamp_image = 1;
  bool has_time_stamp_image() const;
  void clear_time_stamp_image();
  static const int kTimeStampImageFieldNumber = 1;
  ::google::protobuf::uint64 time_stamp_image() const;
  void set_time_stamp_image(::google::protobuf::uint64 value);

  // optional uint64 time_stamp = 2;
  bool has_time_stamp() const;
  void clear_time_stamp();
  static const int kTimeStampFieldNumber = 2;
  ::google::protobuf::uint64 time_stamp() const;
  void set_time_stamp(::google::protobuf::uint64 value);

  // optional uint32 protocol_version = 3;
  bool has_protocol_version() const;
  void clear_protocol_version();
  static const int kProtocolVersionFieldNumber = 3;
  ::google::protobuf::uint32 protocol_version() const;
  void set_protocol_version(::google::protobuf::uint32 value);

  // optional uint32 parking_slot_num = 4;
  bool has_parking_slot_num() const;
  void clear_parking_slot_num();
  static const int kParkingSlotNumFieldNumber = 4;
  ::google::protobuf::uint32 parking_slot_num() const;
  void set_parking_slot_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.Ussslotlist)
 private:
  void set_has_time_stamp_image();
  void clear_has_time_stamp_image();
  void set_has_time_stamp();
  void clear_has_time_stamp();
  void set_has_protocol_version();
  void clear_has_protocol_version();
  void set_has_parking_slot_num();
  void clear_has_parking_slot_num();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::AUSSPS_USS > parking_slots_;
  ::google::protobuf::uint64 time_stamp_image_;
  ::google::protobuf::uint64 time_stamp_;
  ::google::protobuf::uint32 protocol_version_;
  ::google::protobuf::uint32 parking_slot_num_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UltrasonicInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Parking.UltrasonicInfo.UltrasonicInfo) */ {
 public:
  UltrasonicInfo();
  virtual ~UltrasonicInfo();

  UltrasonicInfo(const UltrasonicInfo& from);

  inline UltrasonicInfo& operator=(const UltrasonicInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UltrasonicInfo(UltrasonicInfo&& from) noexcept
    : UltrasonicInfo() {
    *this = ::std::move(from);
  }

  inline UltrasonicInfo& operator=(UltrasonicInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UltrasonicInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UltrasonicInfo* internal_default_instance() {
    return reinterpret_cast<const UltrasonicInfo*>(
               &_UltrasonicInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(UltrasonicInfo* other);
  friend void swap(UltrasonicInfo& a, UltrasonicInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UltrasonicInfo* New() const final {
    return CreateMaybeMessage<UltrasonicInfo>(NULL);
  }

  UltrasonicInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UltrasonicInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UltrasonicInfo& from);
  void MergeFrom(const UltrasonicInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UltrasonicInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Parking.UltrasonicInfo.USSObject uss_obj = 2;
  bool has_uss_obj() const;
  void clear_uss_obj();
  static const int kUssObjFieldNumber = 2;
  private:
  const ::Parking::UltrasonicInfo::USSObject& _internal_uss_obj() const;
  public:
  const ::Parking::UltrasonicInfo::USSObject& uss_obj() const;
  ::Parking::UltrasonicInfo::USSObject* release_uss_obj();
  ::Parking::UltrasonicInfo::USSObject* mutable_uss_obj();
  void set_allocated_uss_obj(::Parking::UltrasonicInfo::USSObject* uss_obj);

  // optional .Parking.UltrasonicInfo.Ussslotlist uss_slot_list = 3;
  bool has_uss_slot_list() const;
  void clear_uss_slot_list();
  static const int kUssSlotListFieldNumber = 3;
  private:
  const ::Parking::UltrasonicInfo::Ussslotlist& _internal_uss_slot_list() const;
  public:
  const ::Parking::UltrasonicInfo::Ussslotlist& uss_slot_list() const;
  ::Parking::UltrasonicInfo::Ussslotlist* release_uss_slot_list();
  ::Parking::UltrasonicInfo::Ussslotlist* mutable_uss_slot_list();
  void set_allocated_uss_slot_list(::Parking::UltrasonicInfo::Ussslotlist* uss_slot_list);

  // optional .Parking.UltrasonicInfo.Uss_Data uss_dis = 4;
  bool has_uss_dis() const;
  void clear_uss_dis();
  static const int kUssDisFieldNumber = 4;
  private:
  const ::Parking::UltrasonicInfo::Uss_Data& _internal_uss_dis() const;
  public:
  const ::Parking::UltrasonicInfo::Uss_Data& uss_dis() const;
  ::Parking::UltrasonicInfo::Uss_Data* release_uss_dis();
  ::Parking::UltrasonicInfo::Uss_Data* mutable_uss_dis();
  void set_allocated_uss_dis(::Parking::UltrasonicInfo::Uss_Data* uss_dis);

  // optional uint64 time_stamp = 1;
  bool has_time_stamp() const;
  void clear_time_stamp();
  static const int kTimeStampFieldNumber = 1;
  ::google::protobuf::uint64 time_stamp() const;
  void set_time_stamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Parking.UltrasonicInfo.UltrasonicInfo)
 private:
  void set_has_time_stamp();
  void clear_has_time_stamp();
  void set_has_uss_obj();
  void clear_has_uss_obj();
  void set_has_uss_slot_list();
  void clear_has_uss_slot_list();
  void set_has_uss_dis();
  void clear_has_uss_dis();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::Parking::UltrasonicInfo::USSObject* uss_obj_;
  ::Parking::UltrasonicInfo::Ussslotlist* uss_slot_list_;
  ::Parking::UltrasonicInfo::Uss_Data* uss_dis_;
  ::google::protobuf::uint64 time_stamp_;
  friend struct ::protobuf_UltrasonicInfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Pos2DType

// optional sint32 x = 1;
inline bool Pos2DType::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pos2DType::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pos2DType::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pos2DType::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Pos2DType::x() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Pos2DType.x)
  return x_;
}
inline void Pos2DType::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Pos2DType.x)
}

// optional sint32 y = 2;
inline bool Pos2DType::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Pos2DType::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Pos2DType::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Pos2DType::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Pos2DType::y() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Pos2DType.y)
  return y_;
}
inline void Pos2DType::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Pos2DType.y)
}

// -------------------------------------------------------------------

// APosition2D_UPS

// optional sint32 x = 1;
inline bool APosition2D_UPS::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void APosition2D_UPS::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void APosition2D_UPS::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void APosition2D_UPS::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 APosition2D_UPS::x() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.APosition2D_UPS.x)
  return x_;
}
inline void APosition2D_UPS::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.APosition2D_UPS.x)
}

// optional sint32 y = 2;
inline bool APosition2D_UPS::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void APosition2D_UPS::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void APosition2D_UPS::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void APosition2D_UPS::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 APosition2D_UPS::y() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.APosition2D_UPS.y)
  return y_;
}
inline void APosition2D_UPS::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.APosition2D_UPS.y)
}

// -------------------------------------------------------------------

// RadarObj

// repeated .Parking.UltrasonicInfo.Pos2DType radar_object = 1;
inline int RadarObj::radar_object_size() const {
  return radar_object_.size();
}
inline void RadarObj::clear_radar_object() {
  radar_object_.Clear();
}
inline ::Parking::UltrasonicInfo::Pos2DType* RadarObj::mutable_radar_object(int index) {
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.RadarObj.radar_object)
  return radar_object_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::Pos2DType >*
RadarObj::mutable_radar_object() {
  // @@protoc_insertion_point(field_mutable_list:Parking.UltrasonicInfo.RadarObj.radar_object)
  return &radar_object_;
}
inline const ::Parking::UltrasonicInfo::Pos2DType& RadarObj::radar_object(int index) const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.RadarObj.radar_object)
  return radar_object_.Get(index);
}
inline ::Parking::UltrasonicInfo::Pos2DType* RadarObj::add_radar_object() {
  // @@protoc_insertion_point(field_add:Parking.UltrasonicInfo.RadarObj.radar_object)
  return radar_object_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::Pos2DType >&
RadarObj::radar_object() const {
  // @@protoc_insertion_point(field_list:Parking.UltrasonicInfo.RadarObj.radar_object)
  return radar_object_;
}

// -------------------------------------------------------------------

// Uss_Data

// optional uint32 front0 = 1;
inline bool Uss_Data::has_front0() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Uss_Data::set_has_front0() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Uss_Data::clear_has_front0() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Uss_Data::clear_front0() {
  front0_ = 0u;
  clear_has_front0();
}
inline ::google::protobuf::uint32 Uss_Data::front0() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.front0)
  return front0_;
}
inline void Uss_Data::set_front0(::google::protobuf::uint32 value) {
  set_has_front0();
  front0_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.front0)
}

// optional uint32 front1 = 2;
inline bool Uss_Data::has_front1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Uss_Data::set_has_front1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Uss_Data::clear_has_front1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Uss_Data::clear_front1() {
  front1_ = 0u;
  clear_has_front1();
}
inline ::google::protobuf::uint32 Uss_Data::front1() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.front1)
  return front1_;
}
inline void Uss_Data::set_front1(::google::protobuf::uint32 value) {
  set_has_front1();
  front1_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.front1)
}

// optional uint32 front2 = 3;
inline bool Uss_Data::has_front2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Uss_Data::set_has_front2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Uss_Data::clear_has_front2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Uss_Data::clear_front2() {
  front2_ = 0u;
  clear_has_front2();
}
inline ::google::protobuf::uint32 Uss_Data::front2() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.front2)
  return front2_;
}
inline void Uss_Data::set_front2(::google::protobuf::uint32 value) {
  set_has_front2();
  front2_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.front2)
}

// optional uint32 front3 = 4;
inline bool Uss_Data::has_front3() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Uss_Data::set_has_front3() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Uss_Data::clear_has_front3() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Uss_Data::clear_front3() {
  front3_ = 0u;
  clear_has_front3();
}
inline ::google::protobuf::uint32 Uss_Data::front3() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.front3)
  return front3_;
}
inline void Uss_Data::set_front3(::google::protobuf::uint32 value) {
  set_has_front3();
  front3_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.front3)
}

// optional uint32 rear0 = 5;
inline bool Uss_Data::has_rear0() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Uss_Data::set_has_rear0() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Uss_Data::clear_has_rear0() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Uss_Data::clear_rear0() {
  rear0_ = 0u;
  clear_has_rear0();
}
inline ::google::protobuf::uint32 Uss_Data::rear0() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.rear0)
  return rear0_;
}
inline void Uss_Data::set_rear0(::google::protobuf::uint32 value) {
  set_has_rear0();
  rear0_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.rear0)
}

// optional uint32 rear1 = 6;
inline bool Uss_Data::has_rear1() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Uss_Data::set_has_rear1() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Uss_Data::clear_has_rear1() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Uss_Data::clear_rear1() {
  rear1_ = 0u;
  clear_has_rear1();
}
inline ::google::protobuf::uint32 Uss_Data::rear1() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.rear1)
  return rear1_;
}
inline void Uss_Data::set_rear1(::google::protobuf::uint32 value) {
  set_has_rear1();
  rear1_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.rear1)
}

// optional uint32 rear2 = 7;
inline bool Uss_Data::has_rear2() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Uss_Data::set_has_rear2() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Uss_Data::clear_has_rear2() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Uss_Data::clear_rear2() {
  rear2_ = 0u;
  clear_has_rear2();
}
inline ::google::protobuf::uint32 Uss_Data::rear2() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.rear2)
  return rear2_;
}
inline void Uss_Data::set_rear2(::google::protobuf::uint32 value) {
  set_has_rear2();
  rear2_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.rear2)
}

// optional uint32 rear3 = 8;
inline bool Uss_Data::has_rear3() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Uss_Data::set_has_rear3() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Uss_Data::clear_has_rear3() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Uss_Data::clear_rear3() {
  rear3_ = 0u;
  clear_has_rear3();
}
inline ::google::protobuf::uint32 Uss_Data::rear3() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.rear3)
  return rear3_;
}
inline void Uss_Data::set_rear3(::google::protobuf::uint32 value) {
  set_has_rear3();
  rear3_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.rear3)
}

// optional uint32 left_side0 = 9;
inline bool Uss_Data::has_left_side0() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Uss_Data::set_has_left_side0() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Uss_Data::clear_has_left_side0() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Uss_Data::clear_left_side0() {
  left_side0_ = 0u;
  clear_has_left_side0();
}
inline ::google::protobuf::uint32 Uss_Data::left_side0() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.left_side0)
  return left_side0_;
}
inline void Uss_Data::set_left_side0(::google::protobuf::uint32 value) {
  set_has_left_side0();
  left_side0_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.left_side0)
}

// optional uint32 left_side1 = 10;
inline bool Uss_Data::has_left_side1() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Uss_Data::set_has_left_side1() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Uss_Data::clear_has_left_side1() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Uss_Data::clear_left_side1() {
  left_side1_ = 0u;
  clear_has_left_side1();
}
inline ::google::protobuf::uint32 Uss_Data::left_side1() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.left_side1)
  return left_side1_;
}
inline void Uss_Data::set_left_side1(::google::protobuf::uint32 value) {
  set_has_left_side1();
  left_side1_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.left_side1)
}

// optional uint32 right_side0 = 11;
inline bool Uss_Data::has_right_side0() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Uss_Data::set_has_right_side0() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Uss_Data::clear_has_right_side0() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Uss_Data::clear_right_side0() {
  right_side0_ = 0u;
  clear_has_right_side0();
}
inline ::google::protobuf::uint32 Uss_Data::right_side0() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.right_side0)
  return right_side0_;
}
inline void Uss_Data::set_right_side0(::google::protobuf::uint32 value) {
  set_has_right_side0();
  right_side0_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.right_side0)
}

// optional uint32 right_side1 = 12;
inline bool Uss_Data::has_right_side1() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Uss_Data::set_has_right_side1() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Uss_Data::clear_has_right_side1() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Uss_Data::clear_right_side1() {
  right_side1_ = 0u;
  clear_has_right_side1();
}
inline ::google::protobuf::uint32 Uss_Data::right_side1() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Uss_Data.right_side1)
  return right_side1_;
}
inline void Uss_Data::set_right_side1(::google::protobuf::uint32 value) {
  set_has_right_side1();
  right_side1_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Uss_Data.right_side1)
}

// -------------------------------------------------------------------

// USSObject

// repeated uint32 uss_state = 1;
inline int USSObject::uss_state_size() const {
  return uss_state_.size();
}
inline void USSObject::clear_uss_state() {
  uss_state_.Clear();
}
inline ::google::protobuf::uint32 USSObject::uss_state(int index) const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.USSObject.uss_state)
  return uss_state_.Get(index);
}
inline void USSObject::set_uss_state(int index, ::google::protobuf::uint32 value) {
  uss_state_.Set(index, value);
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.USSObject.uss_state)
}
inline void USSObject::add_uss_state(::google::protobuf::uint32 value) {
  uss_state_.Add(value);
  // @@protoc_insertion_point(field_add:Parking.UltrasonicInfo.USSObject.uss_state)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
USSObject::uss_state() const {
  // @@protoc_insertion_point(field_list:Parking.UltrasonicInfo.USSObject.uss_state)
  return uss_state_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
USSObject::mutable_uss_state() {
  // @@protoc_insertion_point(field_mutable_list:Parking.UltrasonicInfo.USSObject.uss_state)
  return &uss_state_;
}

// optional uint32 obj_counter = 2;
inline bool USSObject::has_obj_counter() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void USSObject::set_has_obj_counter() {
  _has_bits_[0] |= 0x00000004u;
}
inline void USSObject::clear_has_obj_counter() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void USSObject::clear_obj_counter() {
  obj_counter_ = 0u;
  clear_has_obj_counter();
}
inline ::google::protobuf::uint32 USSObject::obj_counter() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.USSObject.obj_counter)
  return obj_counter_;
}
inline void USSObject::set_obj_counter(::google::protobuf::uint32 value) {
  set_has_obj_counter();
  obj_counter_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.USSObject.obj_counter)
}

// repeated .Parking.UltrasonicInfo.RadarObj region = 3;
inline int USSObject::region_size() const {
  return region_.size();
}
inline void USSObject::clear_region() {
  region_.Clear();
}
inline ::Parking::UltrasonicInfo::RadarObj* USSObject::mutable_region(int index) {
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.USSObject.region)
  return region_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::RadarObj >*
USSObject::mutable_region() {
  // @@protoc_insertion_point(field_mutable_list:Parking.UltrasonicInfo.USSObject.region)
  return &region_;
}
inline const ::Parking::UltrasonicInfo::RadarObj& USSObject::region(int index) const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.USSObject.region)
  return region_.Get(index);
}
inline ::Parking::UltrasonicInfo::RadarObj* USSObject::add_region() {
  // @@protoc_insertion_point(field_add:Parking.UltrasonicInfo.USSObject.region)
  return region_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::RadarObj >&
USSObject::region() const {
  // @@protoc_insertion_point(field_list:Parking.UltrasonicInfo.USSObject.region)
  return region_;
}

// optional uint32 id = 4;
inline bool USSObject::has_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void USSObject::set_has_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void USSObject::clear_has_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void USSObject::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 USSObject::id() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.USSObject.id)
  return id_;
}
inline void USSObject::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.USSObject.id)
}

// optional .Parking.UltrasonicInfo.Pos2DType obj_point_a = 5;
inline bool USSObject::has_obj_point_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void USSObject::set_has_obj_point_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void USSObject::clear_has_obj_point_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void USSObject::clear_obj_point_a() {
  if (obj_point_a_ != NULL) obj_point_a_->Clear();
  clear_has_obj_point_a();
}
inline const ::Parking::UltrasonicInfo::Pos2DType& USSObject::_internal_obj_point_a() const {
  return *obj_point_a_;
}
inline const ::Parking::UltrasonicInfo::Pos2DType& USSObject::obj_point_a() const {
  const ::Parking::UltrasonicInfo::Pos2DType* p = obj_point_a_;
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.USSObject.obj_point_a)
  return p != NULL ? *p : *reinterpret_cast<const ::Parking::UltrasonicInfo::Pos2DType*>(
      &::Parking::UltrasonicInfo::_Pos2DType_default_instance_);
}
inline ::Parking::UltrasonicInfo::Pos2DType* USSObject::release_obj_point_a() {
  // @@protoc_insertion_point(field_release:Parking.UltrasonicInfo.USSObject.obj_point_a)
  clear_has_obj_point_a();
  ::Parking::UltrasonicInfo::Pos2DType* temp = obj_point_a_;
  obj_point_a_ = NULL;
  return temp;
}
inline ::Parking::UltrasonicInfo::Pos2DType* USSObject::mutable_obj_point_a() {
  set_has_obj_point_a();
  if (obj_point_a_ == NULL) {
    auto* p = CreateMaybeMessage<::Parking::UltrasonicInfo::Pos2DType>(GetArenaNoVirtual());
    obj_point_a_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.USSObject.obj_point_a)
  return obj_point_a_;
}
inline void USSObject::set_allocated_obj_point_a(::Parking::UltrasonicInfo::Pos2DType* obj_point_a) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete obj_point_a_;
  }
  if (obj_point_a) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      obj_point_a = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, obj_point_a, submessage_arena);
    }
    set_has_obj_point_a();
  } else {
    clear_has_obj_point_a();
  }
  obj_point_a_ = obj_point_a;
  // @@protoc_insertion_point(field_set_allocated:Parking.UltrasonicInfo.USSObject.obj_point_a)
}

// optional .Parking.UltrasonicInfo.Pos2DType obj_point_b = 6;
inline bool USSObject::has_obj_point_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void USSObject::set_has_obj_point_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void USSObject::clear_has_obj_point_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void USSObject::clear_obj_point_b() {
  if (obj_point_b_ != NULL) obj_point_b_->Clear();
  clear_has_obj_point_b();
}
inline const ::Parking::UltrasonicInfo::Pos2DType& USSObject::_internal_obj_point_b() const {
  return *obj_point_b_;
}
inline const ::Parking::UltrasonicInfo::Pos2DType& USSObject::obj_point_b() const {
  const ::Parking::UltrasonicInfo::Pos2DType* p = obj_point_b_;
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.USSObject.obj_point_b)
  return p != NULL ? *p : *reinterpret_cast<const ::Parking::UltrasonicInfo::Pos2DType*>(
      &::Parking::UltrasonicInfo::_Pos2DType_default_instance_);
}
inline ::Parking::UltrasonicInfo::Pos2DType* USSObject::release_obj_point_b() {
  // @@protoc_insertion_point(field_release:Parking.UltrasonicInfo.USSObject.obj_point_b)
  clear_has_obj_point_b();
  ::Parking::UltrasonicInfo::Pos2DType* temp = obj_point_b_;
  obj_point_b_ = NULL;
  return temp;
}
inline ::Parking::UltrasonicInfo::Pos2DType* USSObject::mutable_obj_point_b() {
  set_has_obj_point_b();
  if (obj_point_b_ == NULL) {
    auto* p = CreateMaybeMessage<::Parking::UltrasonicInfo::Pos2DType>(GetArenaNoVirtual());
    obj_point_b_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.USSObject.obj_point_b)
  return obj_point_b_;
}
inline void USSObject::set_allocated_obj_point_b(::Parking::UltrasonicInfo::Pos2DType* obj_point_b) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete obj_point_b_;
  }
  if (obj_point_b) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      obj_point_b = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, obj_point_b, submessage_arena);
    }
    set_has_obj_point_b();
  } else {
    clear_has_obj_point_b();
  }
  obj_point_b_ = obj_point_b;
  // @@protoc_insertion_point(field_set_allocated:Parking.UltrasonicInfo.USSObject.obj_point_b)
}

// optional .Parking.UltrasonicInfo.tObjType_USS obj_type = 7;
inline bool USSObject::has_obj_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void USSObject::set_has_obj_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void USSObject::clear_has_obj_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void USSObject::clear_obj_type() {
  obj_type_ = 0;
  clear_has_obj_type();
}
inline ::Parking::UltrasonicInfo::tObjType_USS USSObject::obj_type() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.USSObject.obj_type)
  return static_cast< ::Parking::UltrasonicInfo::tObjType_USS >(obj_type_);
}
inline void USSObject::set_obj_type(::Parking::UltrasonicInfo::tObjType_USS value) {
  assert(::Parking::UltrasonicInfo::tObjType_USS_IsValid(value));
  set_has_obj_type();
  obj_type_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.USSObject.obj_type)
}

// -------------------------------------------------------------------

// AUSSPS_USS

// optional uint32 id = 1;
inline bool AUSSPS_USS::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AUSSPS_USS::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AUSSPS_USS::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AUSSPS_USS::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 AUSSPS_USS::id() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.id)
  return id_;
}
inline void AUSSPS_USS::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.id)
}

// repeated .Parking.UltrasonicInfo.APosition2D_UPS corner_points = 2;
inline int AUSSPS_USS::corner_points_size() const {
  return corner_points_.size();
}
inline void AUSSPS_USS::clear_corner_points() {
  corner_points_.Clear();
}
inline ::Parking::UltrasonicInfo::APosition2D_UPS* AUSSPS_USS::mutable_corner_points(int index) {
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.AUSSPS_USS.corner_points)
  return corner_points_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::APosition2D_UPS >*
AUSSPS_USS::mutable_corner_points() {
  // @@protoc_insertion_point(field_mutable_list:Parking.UltrasonicInfo.AUSSPS_USS.corner_points)
  return &corner_points_;
}
inline const ::Parking::UltrasonicInfo::APosition2D_UPS& AUSSPS_USS::corner_points(int index) const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.corner_points)
  return corner_points_.Get(index);
}
inline ::Parking::UltrasonicInfo::APosition2D_UPS* AUSSPS_USS::add_corner_points() {
  // @@protoc_insertion_point(field_add:Parking.UltrasonicInfo.AUSSPS_USS.corner_points)
  return corner_points_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::APosition2D_UPS >&
AUSSPS_USS::corner_points() const {
  // @@protoc_insertion_point(field_list:Parking.UltrasonicInfo.AUSSPS_USS.corner_points)
  return corner_points_;
}

// optional uint32 slot_side = 3;
inline bool AUSSPS_USS::has_slot_side() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AUSSPS_USS::set_has_slot_side() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AUSSPS_USS::clear_has_slot_side() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AUSSPS_USS::clear_slot_side() {
  slot_side_ = 0u;
  clear_has_slot_side();
}
inline ::google::protobuf::uint32 AUSSPS_USS::slot_side() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.slot_side)
  return slot_side_;
}
inline void AUSSPS_USS::set_slot_side(::google::protobuf::uint32 value) {
  set_has_slot_side();
  slot_side_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.slot_side)
}

// optional sint32 sita = 4;
inline bool AUSSPS_USS::has_sita() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AUSSPS_USS::set_has_sita() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AUSSPS_USS::clear_has_sita() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AUSSPS_USS::clear_sita() {
  sita_ = 0;
  clear_has_sita();
}
inline ::google::protobuf::int32 AUSSPS_USS::sita() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.sita)
  return sita_;
}
inline void AUSSPS_USS::set_sita(::google::protobuf::int32 value) {
  set_has_sita();
  sita_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.sita)
}

// optional sint32 sita_0 = 5;
inline bool AUSSPS_USS::has_sita_0() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AUSSPS_USS::set_has_sita_0() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AUSSPS_USS::clear_has_sita_0() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AUSSPS_USS::clear_sita_0() {
  sita_0_ = 0;
  clear_has_sita_0();
}
inline ::google::protobuf::int32 AUSSPS_USS::sita_0() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.sita_0)
  return sita_0_;
}
inline void AUSSPS_USS::set_sita_0(::google::protobuf::int32 value) {
  set_has_sita_0();
  sita_0_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.sita_0)
}

// optional sint32 sita_1 = 6;
inline bool AUSSPS_USS::has_sita_1() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AUSSPS_USS::set_has_sita_1() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AUSSPS_USS::clear_has_sita_1() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AUSSPS_USS::clear_sita_1() {
  sita_1_ = 0;
  clear_has_sita_1();
}
inline ::google::protobuf::int32 AUSSPS_USS::sita_1() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.sita_1)
  return sita_1_;
}
inline void AUSSPS_USS::set_sita_1(::google::protobuf::int32 value) {
  set_has_sita_1();
  sita_1_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.sita_1)
}

// optional float line_a = 7;
inline bool AUSSPS_USS::has_line_a() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AUSSPS_USS::set_has_line_a() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AUSSPS_USS::clear_has_line_a() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AUSSPS_USS::clear_line_a() {
  line_a_ = 0;
  clear_has_line_a();
}
inline float AUSSPS_USS::line_a() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.line_a)
  return line_a_;
}
inline void AUSSPS_USS::set_line_a(float value) {
  set_has_line_a();
  line_a_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.line_a)
}

// optional float line_b = 8;
inline bool AUSSPS_USS::has_line_b() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void AUSSPS_USS::set_has_line_b() {
  _has_bits_[0] |= 0x00000040u;
}
inline void AUSSPS_USS::clear_has_line_b() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void AUSSPS_USS::clear_line_b() {
  line_b_ = 0;
  clear_has_line_b();
}
inline float AUSSPS_USS::line_b() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.line_b)
  return line_b_;
}
inline void AUSSPS_USS::set_line_b(float value) {
  set_has_line_b();
  line_b_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.line_b)
}

// optional .Parking.UltrasonicInfo.tSlotType_USS slot_type = 9;
inline bool AUSSPS_USS::has_slot_type() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void AUSSPS_USS::set_has_slot_type() {
  _has_bits_[0] |= 0x00000080u;
}
inline void AUSSPS_USS::clear_has_slot_type() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void AUSSPS_USS::clear_slot_type() {
  slot_type_ = 0;
  clear_has_slot_type();
}
inline ::Parking::UltrasonicInfo::tSlotType_USS AUSSPS_USS::slot_type() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.slot_type)
  return static_cast< ::Parking::UltrasonicInfo::tSlotType_USS >(slot_type_);
}
inline void AUSSPS_USS::set_slot_type(::Parking::UltrasonicInfo::tSlotType_USS value) {
  assert(::Parking::UltrasonicInfo::tSlotType_USS_IsValid(value));
  set_has_slot_type();
  slot_type_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.slot_type)
}

// optional bool slot_update_flag = 10;
inline bool AUSSPS_USS::has_slot_update_flag() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void AUSSPS_USS::set_has_slot_update_flag() {
  _has_bits_[0] |= 0x00000100u;
}
inline void AUSSPS_USS::clear_has_slot_update_flag() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void AUSSPS_USS::clear_slot_update_flag() {
  slot_update_flag_ = false;
  clear_has_slot_update_flag();
}
inline bool AUSSPS_USS::slot_update_flag() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.AUSSPS_USS.slot_update_flag)
  return slot_update_flag_;
}
inline void AUSSPS_USS::set_slot_update_flag(bool value) {
  set_has_slot_update_flag();
  slot_update_flag_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.AUSSPS_USS.slot_update_flag)
}

// -------------------------------------------------------------------

// Ussslotlist

// optional uint64 time_stamp_image = 1;
inline bool Ussslotlist::has_time_stamp_image() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ussslotlist::set_has_time_stamp_image() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Ussslotlist::clear_has_time_stamp_image() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Ussslotlist::clear_time_stamp_image() {
  time_stamp_image_ = GOOGLE_ULONGLONG(0);
  clear_has_time_stamp_image();
}
inline ::google::protobuf::uint64 Ussslotlist::time_stamp_image() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Ussslotlist.time_stamp_image)
  return time_stamp_image_;
}
inline void Ussslotlist::set_time_stamp_image(::google::protobuf::uint64 value) {
  set_has_time_stamp_image();
  time_stamp_image_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Ussslotlist.time_stamp_image)
}

// optional uint64 time_stamp = 2;
inline bool Ussslotlist::has_time_stamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Ussslotlist::set_has_time_stamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Ussslotlist::clear_has_time_stamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Ussslotlist::clear_time_stamp() {
  time_stamp_ = GOOGLE_ULONGLONG(0);
  clear_has_time_stamp();
}
inline ::google::protobuf::uint64 Ussslotlist::time_stamp() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Ussslotlist.time_stamp)
  return time_stamp_;
}
inline void Ussslotlist::set_time_stamp(::google::protobuf::uint64 value) {
  set_has_time_stamp();
  time_stamp_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Ussslotlist.time_stamp)
}

// optional uint32 protocol_version = 3;
inline bool Ussslotlist::has_protocol_version() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Ussslotlist::set_has_protocol_version() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Ussslotlist::clear_has_protocol_version() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Ussslotlist::clear_protocol_version() {
  protocol_version_ = 0u;
  clear_has_protocol_version();
}
inline ::google::protobuf::uint32 Ussslotlist::protocol_version() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Ussslotlist.protocol_version)
  return protocol_version_;
}
inline void Ussslotlist::set_protocol_version(::google::protobuf::uint32 value) {
  set_has_protocol_version();
  protocol_version_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Ussslotlist.protocol_version)
}

// optional uint32 parking_slot_num = 4;
inline bool Ussslotlist::has_parking_slot_num() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Ussslotlist::set_has_parking_slot_num() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Ussslotlist::clear_has_parking_slot_num() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Ussslotlist::clear_parking_slot_num() {
  parking_slot_num_ = 0u;
  clear_has_parking_slot_num();
}
inline ::google::protobuf::uint32 Ussslotlist::parking_slot_num() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Ussslotlist.parking_slot_num)
  return parking_slot_num_;
}
inline void Ussslotlist::set_parking_slot_num(::google::protobuf::uint32 value) {
  set_has_parking_slot_num();
  parking_slot_num_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.Ussslotlist.parking_slot_num)
}

// repeated .Parking.UltrasonicInfo.AUSSPS_USS parking_slots = 5;
inline int Ussslotlist::parking_slots_size() const {
  return parking_slots_.size();
}
inline void Ussslotlist::clear_parking_slots() {
  parking_slots_.Clear();
}
inline ::Parking::UltrasonicInfo::AUSSPS_USS* Ussslotlist::mutable_parking_slots(int index) {
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.Ussslotlist.parking_slots)
  return parking_slots_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::AUSSPS_USS >*
Ussslotlist::mutable_parking_slots() {
  // @@protoc_insertion_point(field_mutable_list:Parking.UltrasonicInfo.Ussslotlist.parking_slots)
  return &parking_slots_;
}
inline const ::Parking::UltrasonicInfo::AUSSPS_USS& Ussslotlist::parking_slots(int index) const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.Ussslotlist.parking_slots)
  return parking_slots_.Get(index);
}
inline ::Parking::UltrasonicInfo::AUSSPS_USS* Ussslotlist::add_parking_slots() {
  // @@protoc_insertion_point(field_add:Parking.UltrasonicInfo.Ussslotlist.parking_slots)
  return parking_slots_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Parking::UltrasonicInfo::AUSSPS_USS >&
Ussslotlist::parking_slots() const {
  // @@protoc_insertion_point(field_list:Parking.UltrasonicInfo.Ussslotlist.parking_slots)
  return parking_slots_;
}

// -------------------------------------------------------------------

// UltrasonicInfo

// optional uint64 time_stamp = 1;
inline bool UltrasonicInfo::has_time_stamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UltrasonicInfo::set_has_time_stamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UltrasonicInfo::clear_has_time_stamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UltrasonicInfo::clear_time_stamp() {
  time_stamp_ = GOOGLE_ULONGLONG(0);
  clear_has_time_stamp();
}
inline ::google::protobuf::uint64 UltrasonicInfo::time_stamp() const {
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.UltrasonicInfo.time_stamp)
  return time_stamp_;
}
inline void UltrasonicInfo::set_time_stamp(::google::protobuf::uint64 value) {
  set_has_time_stamp();
  time_stamp_ = value;
  // @@protoc_insertion_point(field_set:Parking.UltrasonicInfo.UltrasonicInfo.time_stamp)
}

// optional .Parking.UltrasonicInfo.USSObject uss_obj = 2;
inline bool UltrasonicInfo::has_uss_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UltrasonicInfo::set_has_uss_obj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UltrasonicInfo::clear_has_uss_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UltrasonicInfo::clear_uss_obj() {
  if (uss_obj_ != NULL) uss_obj_->Clear();
  clear_has_uss_obj();
}
inline const ::Parking::UltrasonicInfo::USSObject& UltrasonicInfo::_internal_uss_obj() const {
  return *uss_obj_;
}
inline const ::Parking::UltrasonicInfo::USSObject& UltrasonicInfo::uss_obj() const {
  const ::Parking::UltrasonicInfo::USSObject* p = uss_obj_;
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.UltrasonicInfo.uss_obj)
  return p != NULL ? *p : *reinterpret_cast<const ::Parking::UltrasonicInfo::USSObject*>(
      &::Parking::UltrasonicInfo::_USSObject_default_instance_);
}
inline ::Parking::UltrasonicInfo::USSObject* UltrasonicInfo::release_uss_obj() {
  // @@protoc_insertion_point(field_release:Parking.UltrasonicInfo.UltrasonicInfo.uss_obj)
  clear_has_uss_obj();
  ::Parking::UltrasonicInfo::USSObject* temp = uss_obj_;
  uss_obj_ = NULL;
  return temp;
}
inline ::Parking::UltrasonicInfo::USSObject* UltrasonicInfo::mutable_uss_obj() {
  set_has_uss_obj();
  if (uss_obj_ == NULL) {
    auto* p = CreateMaybeMessage<::Parking::UltrasonicInfo::USSObject>(GetArenaNoVirtual());
    uss_obj_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.UltrasonicInfo.uss_obj)
  return uss_obj_;
}
inline void UltrasonicInfo::set_allocated_uss_obj(::Parking::UltrasonicInfo::USSObject* uss_obj) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete uss_obj_;
  }
  if (uss_obj) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      uss_obj = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, uss_obj, submessage_arena);
    }
    set_has_uss_obj();
  } else {
    clear_has_uss_obj();
  }
  uss_obj_ = uss_obj;
  // @@protoc_insertion_point(field_set_allocated:Parking.UltrasonicInfo.UltrasonicInfo.uss_obj)
}

// optional .Parking.UltrasonicInfo.Ussslotlist uss_slot_list = 3;
inline bool UltrasonicInfo::has_uss_slot_list() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UltrasonicInfo::set_has_uss_slot_list() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UltrasonicInfo::clear_has_uss_slot_list() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UltrasonicInfo::clear_uss_slot_list() {
  if (uss_slot_list_ != NULL) uss_slot_list_->Clear();
  clear_has_uss_slot_list();
}
inline const ::Parking::UltrasonicInfo::Ussslotlist& UltrasonicInfo::_internal_uss_slot_list() const {
  return *uss_slot_list_;
}
inline const ::Parking::UltrasonicInfo::Ussslotlist& UltrasonicInfo::uss_slot_list() const {
  const ::Parking::UltrasonicInfo::Ussslotlist* p = uss_slot_list_;
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.UltrasonicInfo.uss_slot_list)
  return p != NULL ? *p : *reinterpret_cast<const ::Parking::UltrasonicInfo::Ussslotlist*>(
      &::Parking::UltrasonicInfo::_Ussslotlist_default_instance_);
}
inline ::Parking::UltrasonicInfo::Ussslotlist* UltrasonicInfo::release_uss_slot_list() {
  // @@protoc_insertion_point(field_release:Parking.UltrasonicInfo.UltrasonicInfo.uss_slot_list)
  clear_has_uss_slot_list();
  ::Parking::UltrasonicInfo::Ussslotlist* temp = uss_slot_list_;
  uss_slot_list_ = NULL;
  return temp;
}
inline ::Parking::UltrasonicInfo::Ussslotlist* UltrasonicInfo::mutable_uss_slot_list() {
  set_has_uss_slot_list();
  if (uss_slot_list_ == NULL) {
    auto* p = CreateMaybeMessage<::Parking::UltrasonicInfo::Ussslotlist>(GetArenaNoVirtual());
    uss_slot_list_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.UltrasonicInfo.uss_slot_list)
  return uss_slot_list_;
}
inline void UltrasonicInfo::set_allocated_uss_slot_list(::Parking::UltrasonicInfo::Ussslotlist* uss_slot_list) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete uss_slot_list_;
  }
  if (uss_slot_list) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      uss_slot_list = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, uss_slot_list, submessage_arena);
    }
    set_has_uss_slot_list();
  } else {
    clear_has_uss_slot_list();
  }
  uss_slot_list_ = uss_slot_list;
  // @@protoc_insertion_point(field_set_allocated:Parking.UltrasonicInfo.UltrasonicInfo.uss_slot_list)
}

// optional .Parking.UltrasonicInfo.Uss_Data uss_dis = 4;
inline bool UltrasonicInfo::has_uss_dis() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UltrasonicInfo::set_has_uss_dis() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UltrasonicInfo::clear_has_uss_dis() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UltrasonicInfo::clear_uss_dis() {
  if (uss_dis_ != NULL) uss_dis_->Clear();
  clear_has_uss_dis();
}
inline const ::Parking::UltrasonicInfo::Uss_Data& UltrasonicInfo::_internal_uss_dis() const {
  return *uss_dis_;
}
inline const ::Parking::UltrasonicInfo::Uss_Data& UltrasonicInfo::uss_dis() const {
  const ::Parking::UltrasonicInfo::Uss_Data* p = uss_dis_;
  // @@protoc_insertion_point(field_get:Parking.UltrasonicInfo.UltrasonicInfo.uss_dis)
  return p != NULL ? *p : *reinterpret_cast<const ::Parking::UltrasonicInfo::Uss_Data*>(
      &::Parking::UltrasonicInfo::_Uss_Data_default_instance_);
}
inline ::Parking::UltrasonicInfo::Uss_Data* UltrasonicInfo::release_uss_dis() {
  // @@protoc_insertion_point(field_release:Parking.UltrasonicInfo.UltrasonicInfo.uss_dis)
  clear_has_uss_dis();
  ::Parking::UltrasonicInfo::Uss_Data* temp = uss_dis_;
  uss_dis_ = NULL;
  return temp;
}
inline ::Parking::UltrasonicInfo::Uss_Data* UltrasonicInfo::mutable_uss_dis() {
  set_has_uss_dis();
  if (uss_dis_ == NULL) {
    auto* p = CreateMaybeMessage<::Parking::UltrasonicInfo::Uss_Data>(GetArenaNoVirtual());
    uss_dis_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Parking.UltrasonicInfo.UltrasonicInfo.uss_dis)
  return uss_dis_;
}
inline void UltrasonicInfo::set_allocated_uss_dis(::Parking::UltrasonicInfo::Uss_Data* uss_dis) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete uss_dis_;
  }
  if (uss_dis) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      uss_dis = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, uss_dis, submessage_arena);
    }
    set_has_uss_dis();
  } else {
    clear_has_uss_dis();
  }
  uss_dis_ = uss_dis;
  // @@protoc_insertion_point(field_set_allocated:Parking.UltrasonicInfo.UltrasonicInfo.uss_dis)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace UltrasonicInfo
}  // namespace Parking

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Parking::UltrasonicInfo::tObjType_USS> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Parking::UltrasonicInfo::tObjType_USS>() {
  return ::Parking::UltrasonicInfo::tObjType_USS_descriptor();
}
template <> struct is_proto_enum< ::Parking::UltrasonicInfo::tSlotType_USS> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Parking::UltrasonicInfo::tSlotType_USS>() {
  return ::Parking::UltrasonicInfo::tSlotType_USS_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_UltrasonicInfo_2eproto
