std_msgs/Header header

uint16 fl_whl_spd
uint16 fr_whl_spd
uint16 rl_whl_spd
uint16 rr_whl_spd

int32 fl_whl_direc
int32 fr_whl_direc
int32 rl_whl_direc
int32 rr_whl_direc

uint64 fl_whl_spd_pulse
uint64 fr_whl_spd_pulse
uint64 rl_whl_spd_pulse
uint64 rr_whl_spd_pulse

float64 acc_pedal
float64 brake_pedal
float64 steering_angle
float64 lat_acc
float64 lon_acc
float64 yaw_rate
uint8[16] keys
float64 vehicle_spd
uint8 gear
float64 odo
