{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/ChnInfo",
  "Namespace": "::mdc::vo",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "slotId",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/SlotId"
    },
    {
      "Name": "function",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "videoParam",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/VideoParam"
    }
  ],
  "IsPlane": "false"
}