{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/ConfigServerServiceInterface/ConfigServerServiceInterface/SetParamInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}