{
  "ShortName": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/ComCtrlRequestParamsType",
  "Namespace": "::ara::diag",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "controlType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "communicationType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "subnetNumber",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "nodeIdentificationNumber",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16",
      "Padding": "4"
    }
  ],
  "IsPlane": "true"
}