macro(GetRelativeModuleVersion)
  if (PLATFORM STREQUAL "X86")
    set(PLANNING_DIR ${CMAKE_SOURCE_DIR})
    set(INTERFACE_DIR ${CMAKE_SOURCE_DIR}/interface)
    set(ADCOMMON_DIR ${CMAKE_SOURCE_DIR}/ad_common)
  else()
    # get_filename_component(PARENT_DIR ${CMAKE_SOURCE_DIR} DIRECTORY)
    set(PLANNING_DIR ${CMAKE_SOURCE_DIR}/components/planning/core)
    set(INTERFACE_DIR ${CMAKE_SOURCE_DIR}/components/interface)
    set(ADCOMMON_DIR ${CMAKE_SOURCE_DIR}/components/ad_common)
  endif()

  execute_process(
    COMMAND git rev-parse --short=8 --vertify HEAD
    WORKING_DIRECTORY ${PLANNING_DIR}
    OUTPUT_VARIABLE PLANNING_GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  execute_process(
    COMMAND git rev-parse --short=8 --vertify HEAD
    WORKING_DIRECTORY ${INTERFACE_DIR}
    OUTPUT_VARIABLE INTERFACE_GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  execute_process(
    COMMAND git rev-parse --short=8 --vertify HEAD
    WORKING_DIRECTORY ${ADCOMMON_DIR}
    OUTPUT_VARIABLE ADCOMMON_GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )

  if(NOT PLANNING_GIT_COMMIT_HASH)
    set(PLANNING_GIT_COMMIT_HASH "unknown")
  endif()
  if(NOT INTERFACE_GIT_COMMIT_HASH)
    set(INTERFACE_GIT_COMMIT_HASH "unknown")
  endif()
  if(NOT ADCOMMON_GIT_COMMIT_HASH)
    set(ADCOMMON_GIT_COMMIT_HASH "unknown")
  endif()

  string(STRIP "${PLANNING_GIT_COMMIT_HASH}" PLANNING_GIT_COMMIT_HASH)
  string(STRIP "${INTERFACE_GIT_COMMIT_HASH}" INTERFACE_GIT_COMMIT_HASH)
  string(STRIP "${ADCOMMON_GIT_COMMIT_HASH}" ADCOMMON_GIT_COMMIT_HASH)

  add_definitions(-DPLANNING_GIT_COMMIT_HASH="${PLANNING_GIT_COMMIT_HASH}")
  add_definitions(-DINTERFACE_GIT_COMMIT_HASH="${INTERFACE_GIT_COMMIT_HASH}")
  add_definitions(-DADCOMMON_GIT_COMMIT_HASH="${ADCOMMON_GIT_COMMIT_HASH}")

  message("PLANNING_GIT_COMMIT_HASH: ${PLANNING_GIT_COMMIT_HASH}")
  message("PLANNING_DIR: ${PLANNING_DIR}")
  message("INTERFACE_GIT_COMMIT_HASH: ${INTERFACE_GIT_COMMIT_HASH}")
  message("INTERFACE_DIR: ${INTERFACE_DIR}")
  message("ADCOMMON_GIT_COMMIT_HASH: ${ADCOMMON_GIT_COMMIT_HASH}")
  message("ADCOMMON_DIR: ${ADCOMMON_DIR}")
endmacro()