uint32 id                        # 车位ID
APosition2D_UPS[6] corner_points # 车位角点信息[6]
uint32 slot_side                # 车位所在侧边
int32 sita                     # 车位入口线斜率
int32 sita_0                   # 车位入口线斜率
int32 sita_1                   # 车位入口线斜率
float32 line_a                    # 车位侧边线
float32 line_b                    # 车位侧边线
uint8 slot_type         # 车位类型
bool slot_update_flag         # 车位更新标志位 #新增0131