PlanMeta meta 
Trajectory trajectory       # target trajectory.
Velocity velocity          # target velocity.
AccelerationPlanning acceleration  # target acceleration.
TurnState turn_state       # turn light state.
GearState gear_state       # gear state.
Emergency emergency         # emergency degree.
Compensation compensation   # steering offset.
PlanStatus plan_status # plan status.
Comfort comfort          # comfort.
PlanExtra extra           # extra information.
bool is_apa_finished