uint32 obj_id 
uint32 obj_update_flag     # OBJ_UPDATE_FLAG_ENUM
float32 obj_x_pos_stdev 
float32 obj_y_pos_stdev 
float32 obj_x_vel_rel_stdev 
float32 obj_x_pos 
float32 obj_y_pos 
float32 obj_x_vel_rel 
float32 obj_y_vel_rel 
float32 obj_x_acc_rel 
float32 obj_y_acc_rel 
uint32 obj_confidence     # 0 - 100
uint32 obj_obstacle_prob  # 0 - 100
uint32 obj_type           # OBJ_TYPE_ENUM
uint32 obj_motion_pattern     # OBJ_MOTION_PATTERN_ENUM
float32 obj_heading_angle 
float32 obj_width 
float32 obj_length 
uint32 obj_latency 