# /* unit: mm */ //新增0131
uint32 front0       #      /* FL */ //新增0131
uint32 front1       #      /* FML */ //新增0131
uint32 front2       #      /* FMR */ //新增0131
uint32 front3       #      /* FR */ //新增0131
uint32 rear0        #       /* RL */ //新增0131
uint32 rear1        #       /* RML */ //新增0131
uint32 rear2        #       /* RMR */ //新增0131
uint32 rear3        #       /* RR */ //新增0131
uint32 left_side0   #  /* F S Left */ //新增0131
uint32 left_side1   # /* R S Left */ //新增0131
uint32 right_side0  #/* F S Right */ //新增0131
uint32 right_side1  #/* R S Right */ //新增0131