#pragma once

// c struct
#include "interface/src/c/camera_preception_tsr_c.h"
#include "interface/src/c/common_c.h"
#include "interface/src/c/control_command_c.h"
#include "interface/src/c/func_state_machine_c.h"
#include "interface/src/c/fusion_objects_c.h"
#include "interface/src/c/fusion_occupancy_objects_c.h"
#include "interface/src/c/fusion_parking_slot_c.h"
#include "interface/src/c/fusion_road_c.h"
#include "interface/src/c/ifly_localization_c.h"
#include "interface/src/c/ifly_mapping_status_c.h"
#include "interface/src/c/ifly_parking_map_c.h"
#include "interface/src/c/planning_hmi_c.h"
#include "interface/src/c/planning_plan_c.h"
#include "interface/src/c/prediction_c.h"
#include "interface/src/c/vehicle_service_c.h"
#include "interface/src/legacy/interface2.4.5/hmi_mcu_inner_c.h"
#include "interface/src/legacy/interface2.4.6/localization_c.h"
#include "interface/src/c/uss_wave_info_c.h"
#include "interface/src/c/uss_perception_info_c.h"
#include "interface/src/c/camera_preception_parking_slot_c.h"

// rosmsg
#include "proto_msgs/StaticMap.h"
#include "sensor_interface/DebugInfo.h"
#include "struct_msgs/CameraPerceptionTsrInfo.h"
#include "struct_msgs/ControlOutput.h"
#include "struct_msgs/FuncStateMachine.h"
#include "struct_msgs/FusionObjectsInfo.h"
#include "struct_msgs/FusionOccupancyObjectsInfo.h"
#include "struct_msgs/GroundLinePerceptionInfo.h"
#include "struct_msgs_legacy_v2_4_5/HmiMcuInner.h"
// #include "struct_msgs/HmiInner.h"
#include "struct_msgs/IFLYLocalization.h"
#include "struct_msgs/MappingStatusInfo.h"
#include "struct_msgs/ParkingFusionInfo.h"
#include "struct_msgs/ParkingInfo.h"
#include "struct_msgs/PlanningHMIOutputInfoStr.h"
#include "struct_msgs/PlanningOutput.h"
#include "struct_msgs/PredictionResult.h"
#include "struct_msgs/RoadInfo.h"
#include "struct_msgs/SystemVersion.h"
#include "struct_msgs/VehicleServiceOutputInfo.h"
#include "struct_msgs_legacy_v2_4_6/LocalizationEstimate.h"
#include "struct_msgs//UssWaveInfo.h"
#include "struct_msgs/UssPerceptInfo.h"
#include "struct_msgs/ParkingSlotSelectInfo.h"

// struct schema
#include "interface/type_convert/struct_convert/camera_preception_tsr_c.h"
#include "interface/type_convert/struct_convert/common_c.h"
#include "interface/type_convert/struct_convert/control_command_c.h"
#include "interface/type_convert/struct_convert/func_state_machine_c.h"
#include "interface/type_convert/struct_convert/fusion_objects_c.h"
#include "interface/type_convert/struct_convert/fusion_occupancy_objects_c.h"
#include "interface/type_convert/struct_convert/fusion_parking_slot_c.h"
#include "interface/type_convert/struct_convert/fusion_road_c.h"
#include "interface/type_convert/struct_convert/hmi_inner_c.h"
#include "interface/type_convert/struct_convert/ifly_localization_c.h"
#include "interface/type_convert/struct_convert/ifly_parking_map_c.h"
#include "interface/type_convert/struct_convert/planning_hmi_c.h"
#include "interface/type_convert/struct_convert/planning_plan_c.h"
#include "interface/type_convert/struct_convert/prediction_c.h"
#include "interface/type_convert/struct_convert/vehicle_service_c.h"
#include "interface/type_convert/struct_convert_legacy/interface2.4.5/common_c.h"
#include "interface/type_convert/struct_convert_legacy/interface2.4.5/hmi_mcu_inner_c.h"
#include "interface/type_convert/struct_convert_legacy/interface2.4.6/common_c.h"
#include "interface/type_convert/struct_convert_legacy/interface2.4.6/localization_c.h"
#include "interface/type_convert/struct_convert/uss_wave_info_c.h"
#include "interface/type_convert/struct_convert/uss_perception_info_c.h"
#include "interface/type_convert/struct_convert/camera_preception_parking_slot_c.h"
// proto
// #include "proto/common.pb.h"
// #include "proto/ehr.pb.h"
// #include "proto/sensor_image.pb.h"
// #include "private/planning/planning_debug_info.pb.h"
// #include "private/localization/localization_debug_info.pb.h"
// #include "private/control/control_debug_info.pb.h"
// #include "private/prediction/prediction_debug_info.pb.h"
// #include "private/perception/around_view_camera_perception_debug_info.pb.h"
// #include "private/visualization/avm_output_image_info.pb.h"