#pragma once

// c struct
#include "interface/src/c/common_c.h"
#include "interface/src/c/control_command_c.h"
#include "interface/src/c/func_state_machine_c.h"
#include "interface/src/c/fusion_objects_c.h"
#include "interface/src/c/fusion_occupancy_objects_c.h"
#include "interface/src/c/fusion_parking_slot_c.h"
#include "interface/src/c/fusion_road_c.h"
#include "interface/src/c/ifly_localization_c.h"
#include "interface/src/c/ifly_mapping_status_c.h"
#include "interface/src/c/ifly_parking_map_c.h"
// #include "interface/src/c/localization_c.h"
#include "interface/src/c/planning_hmi_c.h"
#include "interface/src/c/planning_plan_c.h"
#include "interface/src/c/prediction_c.h"
#include "interface/src/c/vehicle_service_c.h"
// #include "interface/src/c/ehr_c.h"
// #include "interface/src/c/adas_function_debug_c.h"
// #include "interface/src/c/avm_output_image_info_c.h"
// #include "interface/src/c/camera_perception_lane_lines_c.h"
// #include "interface/src/c/camera_preception_deceler_c.h"
// #include "interface/src/c/camera_preception_groundline_c.h"
// #include "interface/src/c/camera_preception_objects_c.h"
// #include "interface/src/c/camera_preception_parking_slot_c.h"
// #include "interface/src/c/hmi_hpp_inner_c.h"
// #include "interface/src/c/hmi_hpp_outer_c.h"
// #include "interface/src/c/hmi_mcu_inner_c.h"
// #include "interface/src/c/hmi_soc_inner_c.h"
// #include "interface/src/c/hmi_soc_outer_c.h"
// #include "interface/src/c/lidar_objects_c.h"
// #include "interface/src/c/radar_perception_objects_c.h"
// #include "interface/src/c/sensor_gnss_c.h"
// #include "interface/src/c/sensor_image_c.h"
// #include "interface/src/c/sensor_imu_c.h"
// #include "interface/src/c/sensor_pbox_gnss_c.h"
// #include "interface/src/c/sensor_pbox_imu_c.h"
// #include "interface/src/c/uss_perception_debug_info_c.h"
// #include "interface/src/c/uss_perception_info_c.h"
// #include "interface/src/c/uss_wave_debug_info_c.h"
// #include "interface/src/c/uss_wave_info_c.h"

// rosmsg
#include "proto_msgs/StaticMap.h"
#include "sensor_interface/DebugInfo.h"
#include "struct_msgs/ControlOutput.h"
#include "struct_msgs/FuncStateMachine.h"
#include "struct_msgs/FusionObjectsInfo.h"
#include "struct_msgs/FusionOccupancyObjectsInfo.h"
#include "struct_msgs/GroundLinePerceptionInfo.h"
#include "struct_msgs/HmiMcuInner.h"
#include "struct_msgs/IFLYLocalization.h"
#include "struct_msgs/LocalizationEstimate.h"
#include "struct_msgs/MappingStatusInfo.h"
#include "struct_msgs/ParkingFusionInfo.h"
#include "struct_msgs/ParkingInfo.h"
#include "struct_msgs/PlanningHMIOutputInfoStr.h"
#include "struct_msgs/PlanningOutput.h"
#include "struct_msgs/PredictionResult.h"
#include "struct_msgs/RoadInfo.h"
#include "struct_msgs/VehicleServiceOutputInfo.h"
// #include "proto_msgs/PredictionDebugInfo.h"
// #include "proto_msgs/LocalizationDebugInfo.h"
// #include "proto_msgs/ControlDebugInfo.h"
// #include "struct_msgs/HmiSocOuter.h"
// #include "struct_msgs/ParkingSlotSelectInfo.h"
// #include "struct_msgs/ParkingMapFileInfo.h"
// #include "struct_msgs/UpdateSocInner.h"
// #include "struct_msgs/UpdateHppInner.h"
// #include "struct_msgs/RadarPerceptionObjectsInfo.h"
// #include "struct_msgs/RadarPerceptionObjectsInfo.h"
// #include "struct_msgs/RadarPerceptionObjectsInfo.h"
// #include "struct_msgs/RadarPerceptionObjectsInfo.h"
// #include "struct_msgs/RadarPerceptionObjectsInfo.h"
// #include "struct_msgs/GnssInfo.h"
// #include "struct_msgs/ImuInfo.h"
// #include "struct_msgs/ADASFunctionDebugOutputInfo.h"
// #include "struct_msgs/LaneLineSet.h"
// #include "struct_msgs/CameraPerceptionObjectsInfo.h"
// #include "struct_msgs/LaneLineSet.h"
// #include "struct_msgs/CameraPerceptionObjectsInfo.h"
// #include "struct_msgs/UssWaveInfo.h"
// #include "struct_msgs/UssWaveDebugInfo.h"
// #include "struct_msgs/UssPerceptDebugInfo.h"
// #include "struct_msgs/UssPerceptInfo.h"
// #include "struct_msgs/PboxDataGnss.h"
// #include "struct_msgs/PboxDataIMU.h"
// #include "struct_msgs/HmiSocInner.h"
// #include "struct_msgs/Position.h"
// #include "struct_msgs/HmiHppInput.h"
// #include "struct_msgs/HmiHppOutput.h"
// #include "struct_msgs/FeaturePoint.h"
// #include "struct_msgs/DecelerPerceptionInfo.h"
// #include "struct_msgs/UssPerceptDebugInfo.h"
// #include "struct_msgs/DecelerPerceptionInfo.h"
// #include "proto_msgs/OriginData.h"
// #include "proto_msgs/AroundViewCameraPerceptionInfo.h"
// #include "proto_msgs/AVMOutputImageInfo.h"
// #include "sensor_interface/CompressedVideo.h"
// #include "sensor_msgs/CompressedImage.h"
// #include "proto_msgs/Camera_Image_Info.h"
// #include "struct_msgs/Point2si.h"
// #include "struct_msgs/Point3si.h"
// #include "struct_msgs/LidarAdditional.h"
// #include "struct_msgs/LidarObject.h"
// #include "struct_msgs/LidarObjectsInfo.h"
// #include "struct_msgs/OddStatus.h"
// #include "struct_msgs/Camera_Image_Info.h"
// #include "struct_msgs/Front_Camera_Image_Info.h"
// #include "struct_msgs/Surround_Camera_Image_Info.h"
// #include "struct_msgs/Panorama_Camera_Image_Info.h"
// #include "struct_msgs/SnsBkWvStartTimeBuf.h"
// #include "struct_msgs/SnsBkWvWidthBuf.h"
// #include "struct_msgs/SnsBkWvHighBuf.h"
// #include "struct_msgs/SnsBkWvObjTypeBuf.h"
// #include "struct_msgs/EchoTypeBuf.h"
// #include "sensor_interface/CompressedVideo.h"
// #include "sensor_msgs/CompressedImage.h"

// struct schema
#include "interface/type_convert/struct_convert/common_c.h"
#include "interface/type_convert/struct_convert/control_command_c.h"
#include "interface/type_convert/struct_convert/func_state_machine_c.h"
#include "interface/type_convert/struct_convert/fusion_objects_c.h"
#include "interface/type_convert/struct_convert/fusion_occupancy_objects_c.h"
#include "interface/type_convert/struct_convert/fusion_parking_slot_c.h"
#include "interface/type_convert/struct_convert/fusion_road_c.h"
// #include "interface/type_convert/struct_convert/hmi_mcu_inner_c.h"
#include "interface/type_convert/struct_convert/hmi_inner_c.h"
#include "interface/type_convert/struct_convert/ifly_localization_c.h"
#include "interface/type_convert/struct_convert/ifly_parking_map_c.h"
// #include "interface/type_convert/struct_convert/localization_c.h"
#include "interface/type_convert/struct_convert/planning_hmi_c.h"
#include "interface/type_convert/struct_convert/planning_plan_c.h"
#include "interface/type_convert/struct_convert/prediction_c.h"
#include "interface/type_convert/struct_convert/vehicle_service_c.h"
// #include "interface/type_convert/struct_convert/adas_function_debug_c.h"
// #include "interface/type_convert/struct_convert/avm_output_image_info_c.h"
// #include
// "interface/type_convert/struct_convert/camera_perception_lane_lines_c.h"
// #include
// "interface/type_convert/struct_convert/camera_preception_deceler_c.h"
// #include
// "interface/type_convert/struct_convert/camera_preception_groundline_c.h"
// #include
// "interface/type_convert/struct_convert/camera_preception_objects_c.h"
// #include
// "interface/type_convert/struct_convert/camera_preception_parking_slot_c.h"
// #include "interface/type_convert/struct_convert/ehr_c.h"
// #include "interface/type_convert/struct_convert/hmi_hpp_inner_c.h"
// #include "interface/type_convert/struct_convert/hmi_hpp_outer_c.h"
// #include "interface/type_convert/struct_convert/hmi_soc_inner_c.h"
// #include "interface/type_convert/struct_convert/hmi_soc_outer_c.h"
// #include "interface/type_convert/struct_convert/ifly_mapping_status_c.h"
// #include "interface/type_convert/struct_convert/lidar_objects_c.h"
// #include "interface/type_convert/struct_convert/radar_perception_objects_c.h"
// #include "interface/type_convert/struct_convert/sensor_gnss_c.h"
// #include "interface/type_convert/struct_convert/sensor_image_c.h"
// #include "interface/type_convert/struct_convert/sensor_imu_c.h"
// #include "interface/type_convert/struct_convert/sensor_pbox_gnss_c.h"
// #include "interface/type_convert/struct_convert/sensor_pbox_imu_c.h"
// #include
// "interface/type_convert/struct_convert/uss_perception_debug_info_c.h"
// #include "interface/type_convert/struct_convert/uss_perception_info_c.h"
// #include "interface/type_convert/struct_convert/uss_wave_debug_info_c.h"
// #include "interface/type_convert/struct_convert/uss_wave_info_c.h"

// proto
// #include "proto/common.pb.h"
// #include "proto/ehr.pb.h"
// #include "proto/sensor_image.pb.h"
// #include "private/planning/planning_debug_info.pb.h"
// #include "private/localization/localization_debug_info.pb.h"
// #include "private/control/control_debug_info.pb.h"
// #include "private/prediction/prediction_debug_info.pb.h"
// #include "private/perception/around_view_camera_perception_debug_info.pb.h"
// #include "private/visualization/avm_output_image_info.pb.h"