#pragma once
#include "../common/common.h"

namespace planning {

enum MSDObjectType {
  MSD_OBJECT_TYPE_STOP_LINE = -1,
  MSD_OBJECT_TYPE_UNKNOWN = 0,
  MSD_OBJECT_TYPE_COUPE = 1,
  MSD_OBJECT_TYPE_TRANSPORT_TRUCK = 2,
  MSD_OBJECT_TYPE_BUS = 3,
  MSD_OBJECT_TYPE_ENGINEERING_TRUCK = 4,
  MSD_OBJECT_TYPE_TRICYCLE = 5,
  MSD_OBJECT_TYPE_CAR = 6,

  MSD_OBJECT_TYPE_PEDESTRIAN = 10001,
  MSD_OBJECT_TYPE_OFO = 10002,
  MSD_OBJECT_TYPE_CONE_BUCKET = 20001,
  MSD_OBJECT_TYPE_RADAR_ONLY = 30001,
};
}
