uint64 timestamp_us
activeLightSpots[15] active_lightSpots # REPEAT15
reflectiveSigns[12] reflective_signs   # REPEAT12
uint32 frameIndex
uint32 vehIndexUsed
uint16 imageIndex
uint8 ahbcAvailable
uint8 gridFrequency
uint8 numOfActiveLightSpots
uint8 numOfReflectiveSigns
uint8 clearFieldOfView
uint8 beamRequest
uint8 inTunnel
uint8 padding_1
uint16 events_Detected_byte
uint8 light_Sensor_Detections_byte
uint8[7] padding_2 # REPEAT7