uint64 timestamp_us
roadMarkerInfo road_marker_info
roadBorderInfo road_border_info
roadHppFusionInfo road_hppFusionInfo
roadTransitionPoints[12] road_transitionPoints # REPEAT12
uint32 frameIndex
uint32 vehIndexUsed
uint16 crc_16
uint16 imageIndex
uint16 road_Info_crc_16
uint8 rollingFrameCount
uint8 drivingSide
uint8 laneChange
bool hwExitLeft
bool hwExitRight
bool hwEntryLeft
bool hwEntryRight
uint8[3] padding # REPEAT3