// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uss_wave_info.proto

#ifndef PROTOBUF_INCLUDED_uss_5fwave_5finfo_2eproto
#define PROTOBUF_INCLUDED_uss_5fwave_5finfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_uss_5fwave_5finfo_2eproto 

namespace protobuf_uss_5fwave_5finfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[9];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_uss_5fwave_5finfo_2eproto
namespace UssWaveInfo {
class APASnsDisProcessType;
class APASnsDisProcessTypeDefaultTypeInternal;
extern APASnsDisProcessTypeDefaultTypeInternal _APASnsDisProcessType_default_instance_;
class APASnsDtdObjDisInfoType;
class APASnsDtdObjDisInfoTypeDefaultTypeInternal;
extern APASnsDtdObjDisInfoTypeDefaultTypeInternal _APASnsDtdObjDisInfoType_default_instance_;
class DtObjUPASnsDtObjDisInfoType;
class DtObjUPASnsDtObjDisInfoTypeDefaultTypeInternal;
extern DtObjUPASnsDtObjDisInfoTypeDefaultTypeInternal _DtObjUPASnsDtObjDisInfoType_default_instance_;
class DtObjUPASnsDtObjDisInfoType_wDisValueType;
class DtObjUPASnsDtObjDisInfoType_wDisValueTypeDefaultTypeInternal;
extern DtObjUPASnsDtObjDisInfoType_wDisValueTypeDefaultTypeInternal _DtObjUPASnsDtObjDisInfoType_wDisValueType_default_instance_;
class DtObjUPASnsDtObjDisInfoType_wTypeValueType;
class DtObjUPASnsDtObjDisInfoType_wTypeValueTypeDefaultTypeInternal;
extern DtObjUPASnsDtObjDisInfoType_wTypeValueTypeDefaultTypeInternal _DtObjUPASnsDtObjDisInfoType_wTypeValueType_default_instance_;
class DtObjUPASnsDtObjDisInfoType_wXValueType;
class DtObjUPASnsDtObjDisInfoType_wXValueTypeDefaultTypeInternal;
extern DtObjUPASnsDtObjDisInfoType_wXValueTypeDefaultTypeInternal _DtObjUPASnsDtObjDisInfoType_wXValueType_default_instance_;
class DtObjUPASnsDtObjDisInfoType_wYValueType;
class DtObjUPASnsDtObjDisInfoType_wYValueTypeDefaultTypeInternal;
extern DtObjUPASnsDtObjDisInfoType_wYValueTypeDefaultTypeInternal _DtObjUPASnsDtObjDisInfoType_wYValueType_default_instance_;
class UssWaveInfo;
class UssWaveInfoDefaultTypeInternal;
extern UssWaveInfoDefaultTypeInternal _UssWaveInfo_default_instance_;
class Uss_Data;
class Uss_DataDefaultTypeInternal;
extern Uss_DataDefaultTypeInternal _Uss_Data_default_instance_;
}  // namespace UssWaveInfo
namespace google {
namespace protobuf {
template<> ::UssWaveInfo::APASnsDisProcessType* Arena::CreateMaybeMessage<::UssWaveInfo::APASnsDisProcessType>(Arena*);
template<> ::UssWaveInfo::APASnsDtdObjDisInfoType* Arena::CreateMaybeMessage<::UssWaveInfo::APASnsDtdObjDisInfoType>(Arena*);
template<> ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType* Arena::CreateMaybeMessage<::UssWaveInfo::DtObjUPASnsDtObjDisInfoType>(Arena*);
template<> ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType* Arena::CreateMaybeMessage<::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType>(Arena*);
template<> ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType* Arena::CreateMaybeMessage<::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType>(Arena*);
template<> ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType* Arena::CreateMaybeMessage<::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType>(Arena*);
template<> ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType* Arena::CreateMaybeMessage<::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType>(Arena*);
template<> ::UssWaveInfo::UssWaveInfo* Arena::CreateMaybeMessage<::UssWaveInfo::UssWaveInfo>(Arena*);
template<> ::UssWaveInfo::Uss_Data* Arena::CreateMaybeMessage<::UssWaveInfo::Uss_Data>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace UssWaveInfo {

// ===================================================================

class APASnsDtdObjDisInfoType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.APASnsDtdObjDisInfoType) */ {
 public:
  APASnsDtdObjDisInfoType();
  virtual ~APASnsDtdObjDisInfoType();

  APASnsDtdObjDisInfoType(const APASnsDtdObjDisInfoType& from);

  inline APASnsDtdObjDisInfoType& operator=(const APASnsDtdObjDisInfoType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  APASnsDtdObjDisInfoType(APASnsDtdObjDisInfoType&& from) noexcept
    : APASnsDtdObjDisInfoType() {
    *this = ::std::move(from);
  }

  inline APASnsDtdObjDisInfoType& operator=(APASnsDtdObjDisInfoType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APASnsDtdObjDisInfoType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const APASnsDtdObjDisInfoType* internal_default_instance() {
    return reinterpret_cast<const APASnsDtdObjDisInfoType*>(
               &_APASnsDtdObjDisInfoType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(APASnsDtdObjDisInfoType* other);
  friend void swap(APASnsDtdObjDisInfoType& a, APASnsDtdObjDisInfoType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline APASnsDtdObjDisInfoType* New() const final {
    return CreateMaybeMessage<APASnsDtdObjDisInfoType>(NULL);
  }

  APASnsDtdObjDisInfoType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<APASnsDtdObjDisInfoType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const APASnsDtdObjDisInfoType& from);
  void MergeFrom(const APASnsDtdObjDisInfoType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(APASnsDtdObjDisInfoType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float apa_sns_dttd_obj_first = 1;
  bool has_apa_sns_dttd_obj_first() const;
  void clear_apa_sns_dttd_obj_first();
  static const int kApaSnsDttdObjFirstFieldNumber = 1;
  float apa_sns_dttd_obj_first() const;
  void set_apa_sns_dttd_obj_first(float value);

  // optional uint32 cobj1_type = 2;
  bool has_cobj1_type() const;
  void clear_cobj1_type();
  static const int kCobj1TypeFieldNumber = 2;
  ::google::protobuf::uint32 cobj1_type() const;
  void set_cobj1_type(::google::protobuf::uint32 value);

  // optional float apa_sns_dtd_obj_sencond = 3;
  bool has_apa_sns_dtd_obj_sencond() const;
  void clear_apa_sns_dtd_obj_sencond();
  static const int kApaSnsDtdObjSencondFieldNumber = 3;
  float apa_sns_dtd_obj_sencond() const;
  void set_apa_sns_dtd_obj_sencond(float value);

  // optional uint32 cobj2_type = 4;
  bool has_cobj2_type() const;
  void clear_cobj2_type();
  static const int kCobj2TypeFieldNumber = 4;
  ::google::protobuf::uint32 cobj2_type() const;
  void set_cobj2_type(::google::protobuf::uint32 value);

  // optional float apa_sns_dtd_obj_three = 5;
  bool has_apa_sns_dtd_obj_three() const;
  void clear_apa_sns_dtd_obj_three();
  static const int kApaSnsDtdObjThreeFieldNumber = 5;
  float apa_sns_dtd_obj_three() const;
  void set_apa_sns_dtd_obj_three(float value);

  // optional uint32 cobj3_type = 6;
  bool has_cobj3_type() const;
  void clear_cobj3_type();
  static const int kCobj3TypeFieldNumber = 6;
  ::google::protobuf::uint32 cobj3_type() const;
  void set_cobj3_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:UssWaveInfo.APASnsDtdObjDisInfoType)
 private:
  void set_has_apa_sns_dttd_obj_first();
  void clear_has_apa_sns_dttd_obj_first();
  void set_has_cobj1_type();
  void clear_has_cobj1_type();
  void set_has_apa_sns_dtd_obj_sencond();
  void clear_has_apa_sns_dtd_obj_sencond();
  void set_has_cobj2_type();
  void clear_has_cobj2_type();
  void set_has_apa_sns_dtd_obj_three();
  void clear_has_apa_sns_dtd_obj_three();
  void set_has_cobj3_type();
  void clear_has_cobj3_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float apa_sns_dttd_obj_first_;
  ::google::protobuf::uint32 cobj1_type_;
  float apa_sns_dtd_obj_sencond_;
  ::google::protobuf::uint32 cobj2_type_;
  float apa_sns_dtd_obj_three_;
  ::google::protobuf::uint32 cobj3_type_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class APASnsDisProcessType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.APASnsDisProcessType) */ {
 public:
  APASnsDisProcessType();
  virtual ~APASnsDisProcessType();

  APASnsDisProcessType(const APASnsDisProcessType& from);

  inline APASnsDisProcessType& operator=(const APASnsDisProcessType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  APASnsDisProcessType(APASnsDisProcessType&& from) noexcept
    : APASnsDisProcessType() {
    *this = ::std::move(from);
  }

  inline APASnsDisProcessType& operator=(APASnsDisProcessType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const APASnsDisProcessType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const APASnsDisProcessType* internal_default_instance() {
    return reinterpret_cast<const APASnsDisProcessType*>(
               &_APASnsDisProcessType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(APASnsDisProcessType* other);
  friend void swap(APASnsDisProcessType& a, APASnsDisProcessType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline APASnsDisProcessType* New() const final {
    return CreateMaybeMessage<APASnsDisProcessType>(NULL);
  }

  APASnsDisProcessType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<APASnsDisProcessType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const APASnsDisProcessType& from);
  void MergeFrom(const APASnsDisProcessType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(APASnsDisProcessType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UssWaveInfo.APASnsDtdObjDisInfoType apa_sns_dis_buf = 1;
  int apa_sns_dis_buf_size() const;
  void clear_apa_sns_dis_buf();
  static const int kApaSnsDisBufFieldNumber = 1;
  ::UssWaveInfo::APASnsDtdObjDisInfoType* mutable_apa_sns_dis_buf(int index);
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDtdObjDisInfoType >*
      mutable_apa_sns_dis_buf();
  const ::UssWaveInfo::APASnsDtdObjDisInfoType& apa_sns_dis_buf(int index) const;
  ::UssWaveInfo::APASnsDtdObjDisInfoType* add_apa_sns_dis_buf();
  const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDtdObjDisInfoType >&
      apa_sns_dis_buf() const;

  // optional uint32 apa_sns_dtd_obj_dis_info_buf_read_index = 2;
  bool has_apa_sns_dtd_obj_dis_info_buf_read_index() const;
  void clear_apa_sns_dtd_obj_dis_info_buf_read_index();
  static const int kApaSnsDtdObjDisInfoBufReadIndexFieldNumber = 2;
  ::google::protobuf::uint32 apa_sns_dtd_obj_dis_info_buf_read_index() const;
  void set_apa_sns_dtd_obj_dis_info_buf_read_index(::google::protobuf::uint32 value);

  // optional uint32 apa_sns_dtd_obj_dis_info_buf_write_index = 3;
  bool has_apa_sns_dtd_obj_dis_info_buf_write_index() const;
  void clear_apa_sns_dtd_obj_dis_info_buf_write_index();
  static const int kApaSnsDtdObjDisInfoBufWriteIndexFieldNumber = 3;
  ::google::protobuf::uint32 apa_sns_dtd_obj_dis_info_buf_write_index() const;
  void set_apa_sns_dtd_obj_dis_info_buf_write_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:UssWaveInfo.APASnsDisProcessType)
 private:
  void set_has_apa_sns_dtd_obj_dis_info_buf_read_index();
  void clear_has_apa_sns_dtd_obj_dis_info_buf_read_index();
  void set_has_apa_sns_dtd_obj_dis_info_buf_write_index();
  void clear_has_apa_sns_dtd_obj_dis_info_buf_write_index();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDtdObjDisInfoType > apa_sns_dis_buf_;
  ::google::protobuf::uint32 apa_sns_dtd_obj_dis_info_buf_read_index_;
  ::google::protobuf::uint32 apa_sns_dtd_obj_dis_info_buf_write_index_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DtObjUPASnsDtObjDisInfoType_wDisValueType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType) */ {
 public:
  DtObjUPASnsDtObjDisInfoType_wDisValueType();
  virtual ~DtObjUPASnsDtObjDisInfoType_wDisValueType();

  DtObjUPASnsDtObjDisInfoType_wDisValueType(const DtObjUPASnsDtObjDisInfoType_wDisValueType& from);

  inline DtObjUPASnsDtObjDisInfoType_wDisValueType& operator=(const DtObjUPASnsDtObjDisInfoType_wDisValueType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DtObjUPASnsDtObjDisInfoType_wDisValueType(DtObjUPASnsDtObjDisInfoType_wDisValueType&& from) noexcept
    : DtObjUPASnsDtObjDisInfoType_wDisValueType() {
    *this = ::std::move(from);
  }

  inline DtObjUPASnsDtObjDisInfoType_wDisValueType& operator=(DtObjUPASnsDtObjDisInfoType_wDisValueType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DtObjUPASnsDtObjDisInfoType_wDisValueType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DtObjUPASnsDtObjDisInfoType_wDisValueType* internal_default_instance() {
    return reinterpret_cast<const DtObjUPASnsDtObjDisInfoType_wDisValueType*>(
               &_DtObjUPASnsDtObjDisInfoType_wDisValueType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DtObjUPASnsDtObjDisInfoType_wDisValueType* other);
  friend void swap(DtObjUPASnsDtObjDisInfoType_wDisValueType& a, DtObjUPASnsDtObjDisInfoType_wDisValueType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DtObjUPASnsDtObjDisInfoType_wDisValueType* New() const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wDisValueType>(NULL);
  }

  DtObjUPASnsDtObjDisInfoType_wDisValueType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wDisValueType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DtObjUPASnsDtObjDisInfoType_wDisValueType& from);
  void MergeFrom(const DtObjUPASnsDtObjDisInfoType_wDisValueType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DtObjUPASnsDtObjDisInfoType_wDisValueType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float wdis_value = 1;
  int wdis_value_size() const;
  void clear_wdis_value();
  static const int kWdisValueFieldNumber = 1;
  float wdis_value(int index) const;
  void set_wdis_value(int index, float value);
  void add_wdis_value(float value);
  const ::google::protobuf::RepeatedField< float >&
      wdis_value() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_wdis_value();

  // @@protoc_insertion_point(class_scope:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< float > wdis_value_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DtObjUPASnsDtObjDisInfoType_wTypeValueType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType) */ {
 public:
  DtObjUPASnsDtObjDisInfoType_wTypeValueType();
  virtual ~DtObjUPASnsDtObjDisInfoType_wTypeValueType();

  DtObjUPASnsDtObjDisInfoType_wTypeValueType(const DtObjUPASnsDtObjDisInfoType_wTypeValueType& from);

  inline DtObjUPASnsDtObjDisInfoType_wTypeValueType& operator=(const DtObjUPASnsDtObjDisInfoType_wTypeValueType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DtObjUPASnsDtObjDisInfoType_wTypeValueType(DtObjUPASnsDtObjDisInfoType_wTypeValueType&& from) noexcept
    : DtObjUPASnsDtObjDisInfoType_wTypeValueType() {
    *this = ::std::move(from);
  }

  inline DtObjUPASnsDtObjDisInfoType_wTypeValueType& operator=(DtObjUPASnsDtObjDisInfoType_wTypeValueType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DtObjUPASnsDtObjDisInfoType_wTypeValueType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DtObjUPASnsDtObjDisInfoType_wTypeValueType* internal_default_instance() {
    return reinterpret_cast<const DtObjUPASnsDtObjDisInfoType_wTypeValueType*>(
               &_DtObjUPASnsDtObjDisInfoType_wTypeValueType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DtObjUPASnsDtObjDisInfoType_wTypeValueType* other);
  friend void swap(DtObjUPASnsDtObjDisInfoType_wTypeValueType& a, DtObjUPASnsDtObjDisInfoType_wTypeValueType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DtObjUPASnsDtObjDisInfoType_wTypeValueType* New() const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wTypeValueType>(NULL);
  }

  DtObjUPASnsDtObjDisInfoType_wTypeValueType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wTypeValueType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DtObjUPASnsDtObjDisInfoType_wTypeValueType& from);
  void MergeFrom(const DtObjUPASnsDtObjDisInfoType_wTypeValueType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DtObjUPASnsDtObjDisInfoType_wTypeValueType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 wtype_value = 1;
  int wtype_value_size() const;
  void clear_wtype_value();
  static const int kWtypeValueFieldNumber = 1;
  ::google::protobuf::uint32 wtype_value(int index) const;
  void set_wtype_value(int index, ::google::protobuf::uint32 value);
  void add_wtype_value(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      wtype_value() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_wtype_value();

  // @@protoc_insertion_point(class_scope:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > wtype_value_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DtObjUPASnsDtObjDisInfoType_wXValueType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType) */ {
 public:
  DtObjUPASnsDtObjDisInfoType_wXValueType();
  virtual ~DtObjUPASnsDtObjDisInfoType_wXValueType();

  DtObjUPASnsDtObjDisInfoType_wXValueType(const DtObjUPASnsDtObjDisInfoType_wXValueType& from);

  inline DtObjUPASnsDtObjDisInfoType_wXValueType& operator=(const DtObjUPASnsDtObjDisInfoType_wXValueType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DtObjUPASnsDtObjDisInfoType_wXValueType(DtObjUPASnsDtObjDisInfoType_wXValueType&& from) noexcept
    : DtObjUPASnsDtObjDisInfoType_wXValueType() {
    *this = ::std::move(from);
  }

  inline DtObjUPASnsDtObjDisInfoType_wXValueType& operator=(DtObjUPASnsDtObjDisInfoType_wXValueType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DtObjUPASnsDtObjDisInfoType_wXValueType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DtObjUPASnsDtObjDisInfoType_wXValueType* internal_default_instance() {
    return reinterpret_cast<const DtObjUPASnsDtObjDisInfoType_wXValueType*>(
               &_DtObjUPASnsDtObjDisInfoType_wXValueType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(DtObjUPASnsDtObjDisInfoType_wXValueType* other);
  friend void swap(DtObjUPASnsDtObjDisInfoType_wXValueType& a, DtObjUPASnsDtObjDisInfoType_wXValueType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DtObjUPASnsDtObjDisInfoType_wXValueType* New() const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wXValueType>(NULL);
  }

  DtObjUPASnsDtObjDisInfoType_wXValueType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wXValueType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DtObjUPASnsDtObjDisInfoType_wXValueType& from);
  void MergeFrom(const DtObjUPASnsDtObjDisInfoType_wXValueType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DtObjUPASnsDtObjDisInfoType_wXValueType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float wx_value = 1;
  int wx_value_size() const;
  void clear_wx_value();
  static const int kWxValueFieldNumber = 1;
  float wx_value(int index) const;
  void set_wx_value(int index, float value);
  void add_wx_value(float value);
  const ::google::protobuf::RepeatedField< float >&
      wx_value() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_wx_value();

  // @@protoc_insertion_point(class_scope:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< float > wx_value_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DtObjUPASnsDtObjDisInfoType_wYValueType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType) */ {
 public:
  DtObjUPASnsDtObjDisInfoType_wYValueType();
  virtual ~DtObjUPASnsDtObjDisInfoType_wYValueType();

  DtObjUPASnsDtObjDisInfoType_wYValueType(const DtObjUPASnsDtObjDisInfoType_wYValueType& from);

  inline DtObjUPASnsDtObjDisInfoType_wYValueType& operator=(const DtObjUPASnsDtObjDisInfoType_wYValueType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DtObjUPASnsDtObjDisInfoType_wYValueType(DtObjUPASnsDtObjDisInfoType_wYValueType&& from) noexcept
    : DtObjUPASnsDtObjDisInfoType_wYValueType() {
    *this = ::std::move(from);
  }

  inline DtObjUPASnsDtObjDisInfoType_wYValueType& operator=(DtObjUPASnsDtObjDisInfoType_wYValueType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DtObjUPASnsDtObjDisInfoType_wYValueType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DtObjUPASnsDtObjDisInfoType_wYValueType* internal_default_instance() {
    return reinterpret_cast<const DtObjUPASnsDtObjDisInfoType_wYValueType*>(
               &_DtObjUPASnsDtObjDisInfoType_wYValueType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(DtObjUPASnsDtObjDisInfoType_wYValueType* other);
  friend void swap(DtObjUPASnsDtObjDisInfoType_wYValueType& a, DtObjUPASnsDtObjDisInfoType_wYValueType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DtObjUPASnsDtObjDisInfoType_wYValueType* New() const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wYValueType>(NULL);
  }

  DtObjUPASnsDtObjDisInfoType_wYValueType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType_wYValueType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DtObjUPASnsDtObjDisInfoType_wYValueType& from);
  void MergeFrom(const DtObjUPASnsDtObjDisInfoType_wYValueType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DtObjUPASnsDtObjDisInfoType_wYValueType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float wy_value = 1;
  int wy_value_size() const;
  void clear_wy_value();
  static const int kWyValueFieldNumber = 1;
  float wy_value(int index) const;
  void set_wy_value(int index, float value);
  void add_wy_value(float value);
  const ::google::protobuf::RepeatedField< float >&
      wy_value() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_wy_value();

  // @@protoc_insertion_point(class_scope:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< float > wy_value_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DtObjUPASnsDtObjDisInfoType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.DtObjUPASnsDtObjDisInfoType) */ {
 public:
  DtObjUPASnsDtObjDisInfoType();
  virtual ~DtObjUPASnsDtObjDisInfoType();

  DtObjUPASnsDtObjDisInfoType(const DtObjUPASnsDtObjDisInfoType& from);

  inline DtObjUPASnsDtObjDisInfoType& operator=(const DtObjUPASnsDtObjDisInfoType& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DtObjUPASnsDtObjDisInfoType(DtObjUPASnsDtObjDisInfoType&& from) noexcept
    : DtObjUPASnsDtObjDisInfoType() {
    *this = ::std::move(from);
  }

  inline DtObjUPASnsDtObjDisInfoType& operator=(DtObjUPASnsDtObjDisInfoType&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DtObjUPASnsDtObjDisInfoType& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DtObjUPASnsDtObjDisInfoType* internal_default_instance() {
    return reinterpret_cast<const DtObjUPASnsDtObjDisInfoType*>(
               &_DtObjUPASnsDtObjDisInfoType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(DtObjUPASnsDtObjDisInfoType* other);
  friend void swap(DtObjUPASnsDtObjDisInfoType& a, DtObjUPASnsDtObjDisInfoType& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DtObjUPASnsDtObjDisInfoType* New() const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType>(NULL);
  }

  DtObjUPASnsDtObjDisInfoType* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DtObjUPASnsDtObjDisInfoType>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DtObjUPASnsDtObjDisInfoType& from);
  void MergeFrom(const DtObjUPASnsDtObjDisInfoType& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DtObjUPASnsDtObjDisInfoType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef DtObjUPASnsDtObjDisInfoType_wDisValueType wDisValueType;
  typedef DtObjUPASnsDtObjDisInfoType_wTypeValueType wTypeValueType;
  typedef DtObjUPASnsDtObjDisInfoType_wXValueType wXValueType;
  typedef DtObjUPASnsDtObjDisInfoType_wYValueType wYValueType;

  // accessors -------------------------------------------------------

  // repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType wdis = 1;
  int wdis_size() const;
  void clear_wdis();
  static const int kWdisFieldNumber = 1;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType* mutable_wdis(int index);
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType >*
      mutable_wdis();
  const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType& wdis(int index) const;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType* add_wdis();
  const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType >&
      wdis() const;

  // repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType wtype = 2;
  int wtype_size() const;
  void clear_wtype();
  static const int kWtypeFieldNumber = 2;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType* mutable_wtype(int index);
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType >*
      mutable_wtype();
  const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType& wtype(int index) const;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType* add_wtype();
  const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType >&
      wtype() const;

  // repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType wx = 3;
  int wx_size() const;
  void clear_wx();
  static const int kWxFieldNumber = 3;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType* mutable_wx(int index);
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType >*
      mutable_wx();
  const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType& wx(int index) const;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType* add_wx();
  const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType >&
      wx() const;

  // repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType wy = 4;
  int wy_size() const;
  void clear_wy();
  static const int kWyFieldNumber = 4;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType* mutable_wy(int index);
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType >*
      mutable_wy();
  const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType& wy(int index) const;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType* add_wy();
  const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType >&
      wy() const;

  // @@protoc_insertion_point(class_scope:UssWaveInfo.DtObjUPASnsDtObjDisInfoType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType > wdis_;
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType > wtype_;
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType > wx_;
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType > wy_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Uss_Data : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.Uss_Data) */ {
 public:
  Uss_Data();
  virtual ~Uss_Data();

  Uss_Data(const Uss_Data& from);

  inline Uss_Data& operator=(const Uss_Data& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Uss_Data(Uss_Data&& from) noexcept
    : Uss_Data() {
    *this = ::std::move(from);
  }

  inline Uss_Data& operator=(Uss_Data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Uss_Data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Uss_Data* internal_default_instance() {
    return reinterpret_cast<const Uss_Data*>(
               &_Uss_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(Uss_Data* other);
  friend void swap(Uss_Data& a, Uss_Data& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Uss_Data* New() const final {
    return CreateMaybeMessage<Uss_Data>(NULL);
  }

  Uss_Data* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Uss_Data>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Uss_Data& from);
  void MergeFrom(const Uss_Data& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Uss_Data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float front0 = 1;
  bool has_front0() const;
  void clear_front0();
  static const int kFront0FieldNumber = 1;
  float front0() const;
  void set_front0(float value);

  // optional float front1 = 2;
  bool has_front1() const;
  void clear_front1();
  static const int kFront1FieldNumber = 2;
  float front1() const;
  void set_front1(float value);

  // optional float front2 = 3;
  bool has_front2() const;
  void clear_front2();
  static const int kFront2FieldNumber = 3;
  float front2() const;
  void set_front2(float value);

  // optional float front3 = 4;
  bool has_front3() const;
  void clear_front3();
  static const int kFront3FieldNumber = 4;
  float front3() const;
  void set_front3(float value);

  // optional float rear0 = 5;
  bool has_rear0() const;
  void clear_rear0();
  static const int kRear0FieldNumber = 5;
  float rear0() const;
  void set_rear0(float value);

  // optional float rear1 = 6;
  bool has_rear1() const;
  void clear_rear1();
  static const int kRear1FieldNumber = 6;
  float rear1() const;
  void set_rear1(float value);

  // optional float rear2 = 7;
  bool has_rear2() const;
  void clear_rear2();
  static const int kRear2FieldNumber = 7;
  float rear2() const;
  void set_rear2(float value);

  // optional float rear3 = 8;
  bool has_rear3() const;
  void clear_rear3();
  static const int kRear3FieldNumber = 8;
  float rear3() const;
  void set_rear3(float value);

  // optional float left_side0 = 9;
  bool has_left_side0() const;
  void clear_left_side0();
  static const int kLeftSide0FieldNumber = 9;
  float left_side0() const;
  void set_left_side0(float value);

  // optional float left_side1 = 10;
  bool has_left_side1() const;
  void clear_left_side1();
  static const int kLeftSide1FieldNumber = 10;
  float left_side1() const;
  void set_left_side1(float value);

  // optional float right_side0 = 11;
  bool has_right_side0() const;
  void clear_right_side0();
  static const int kRightSide0FieldNumber = 11;
  float right_side0() const;
  void set_right_side0(float value);

  // optional float right_side1 = 12;
  bool has_right_side1() const;
  void clear_right_side1();
  static const int kRightSide1FieldNumber = 12;
  float right_side1() const;
  void set_right_side1(float value);

  // @@protoc_insertion_point(class_scope:UssWaveInfo.Uss_Data)
 private:
  void set_has_front0();
  void clear_has_front0();
  void set_has_front1();
  void clear_has_front1();
  void set_has_front2();
  void clear_has_front2();
  void set_has_front3();
  void clear_has_front3();
  void set_has_rear0();
  void clear_has_rear0();
  void set_has_rear1();
  void clear_has_rear1();
  void set_has_rear2();
  void clear_has_rear2();
  void set_has_rear3();
  void clear_has_rear3();
  void set_has_left_side0();
  void clear_has_left_side0();
  void set_has_left_side1();
  void clear_has_left_side1();
  void set_has_right_side0();
  void clear_has_right_side0();
  void set_has_right_side1();
  void clear_has_right_side1();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float front0_;
  float front1_;
  float front2_;
  float front3_;
  float rear0_;
  float rear1_;
  float rear2_;
  float rear3_;
  float left_side0_;
  float left_side1_;
  float right_side0_;
  float right_side1_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UssWaveInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UssWaveInfo.UssWaveInfo) */ {
 public:
  UssWaveInfo();
  virtual ~UssWaveInfo();

  UssWaveInfo(const UssWaveInfo& from);

  inline UssWaveInfo& operator=(const UssWaveInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UssWaveInfo(UssWaveInfo&& from) noexcept
    : UssWaveInfo() {
    *this = ::std::move(from);
  }

  inline UssWaveInfo& operator=(UssWaveInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UssWaveInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UssWaveInfo* internal_default_instance() {
    return reinterpret_cast<const UssWaveInfo*>(
               &_UssWaveInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(UssWaveInfo* other);
  friend void swap(UssWaveInfo& a, UssWaveInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UssWaveInfo* New() const final {
    return CreateMaybeMessage<UssWaveInfo>(NULL);
  }

  UssWaveInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UssWaveInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UssWaveInfo& from);
  void MergeFrom(const UssWaveInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UssWaveInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bool uss_State = 2;
  int uss_state_size() const;
  void clear_uss_state();
  static const int kUssStateFieldNumber = 2;
  bool uss_state(int index) const;
  void set_uss_state(int index, bool value);
  void add_uss_state(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      uss_state() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_uss_state();

  // repeated float upa_Ori_Dis_Buffer = 3;
  int upa_ori_dis_buffer_size() const;
  void clear_upa_ori_dis_buffer();
  static const int kUpaOriDisBufferFieldNumber = 3;
  float upa_ori_dis_buffer(int index) const;
  void set_upa_ori_dis_buffer(int index, float value);
  void add_upa_ori_dis_buffer(float value);
  const ::google::protobuf::RepeatedField< float >&
      upa_ori_dis_buffer() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_upa_ori_dis_buffer();

  // repeated float apa_Ori_Dis_Buffer = 4;
  int apa_ori_dis_buffer_size() const;
  void clear_apa_ori_dis_buffer();
  static const int kApaOriDisBufferFieldNumber = 4;
  float apa_ori_dis_buffer(int index) const;
  void set_apa_ori_dis_buffer(int index, float value);
  void add_apa_ori_dis_buffer(float value);
  const ::google::protobuf::RepeatedField< float >&
      apa_ori_dis_buffer() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_apa_ori_dis_buffer();

  // repeated .UssWaveInfo.APASnsDisProcessType apa_Dis_Info_Buf = 5;
  int apa_dis_info_buf_size() const;
  void clear_apa_dis_info_buf();
  static const int kApaDisInfoBufFieldNumber = 5;
  ::UssWaveInfo::APASnsDisProcessType* mutable_apa_dis_info_buf(int index);
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDisProcessType >*
      mutable_apa_dis_info_buf();
  const ::UssWaveInfo::APASnsDisProcessType& apa_dis_info_buf(int index) const;
  ::UssWaveInfo::APASnsDisProcessType* add_apa_dis_info_buf();
  const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDisProcessType >&
      apa_dis_info_buf() const;

  // repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType upa_Dis_Info_Buf = 6;
  int upa_dis_info_buf_size() const;
  void clear_upa_dis_info_buf();
  static const int kUpaDisInfoBufFieldNumber = 6;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType* mutable_upa_dis_info_buf(int index);
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType >*
      mutable_upa_dis_info_buf();
  const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType& upa_dis_info_buf(int index) const;
  ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType* add_upa_dis_info_buf();
  const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType >&
      upa_dis_info_buf() const;

  // optional .Common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::Common::Header& _internal_header() const;
  public:
  const ::Common::Header& header() const;
  ::Common::Header* release_header();
  ::Common::Header* mutable_header();
  void set_allocated_header(::Common::Header* header);

  // optional .UssWaveInfo.Uss_Data uss_dis = 7;
  bool has_uss_dis() const;
  void clear_uss_dis();
  static const int kUssDisFieldNumber = 7;
  private:
  const ::UssWaveInfo::Uss_Data& _internal_uss_dis() const;
  public:
  const ::UssWaveInfo::Uss_Data& uss_dis() const;
  ::UssWaveInfo::Uss_Data* release_uss_dis();
  ::UssWaveInfo::Uss_Data* mutable_uss_dis();
  void set_allocated_uss_dis(::UssWaveInfo::Uss_Data* uss_dis);

  // @@protoc_insertion_point(class_scope:UssWaveInfo.UssWaveInfo)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_uss_dis();
  void clear_has_uss_dis();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< bool > uss_state_;
  ::google::protobuf::RepeatedField< float > upa_ori_dis_buffer_;
  ::google::protobuf::RepeatedField< float > apa_ori_dis_buffer_;
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDisProcessType > apa_dis_info_buf_;
  ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType > upa_dis_info_buf_;
  ::Common::Header* header_;
  ::UssWaveInfo::Uss_Data* uss_dis_;
  friend struct ::protobuf_uss_5fwave_5finfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// APASnsDtdObjDisInfoType

// optional float apa_sns_dttd_obj_first = 1;
inline bool APASnsDtdObjDisInfoType::has_apa_sns_dttd_obj_first() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void APASnsDtdObjDisInfoType::set_has_apa_sns_dttd_obj_first() {
  _has_bits_[0] |= 0x00000001u;
}
inline void APASnsDtdObjDisInfoType::clear_has_apa_sns_dttd_obj_first() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void APASnsDtdObjDisInfoType::clear_apa_sns_dttd_obj_first() {
  apa_sns_dttd_obj_first_ = 0;
  clear_has_apa_sns_dttd_obj_first();
}
inline float APASnsDtdObjDisInfoType::apa_sns_dttd_obj_first() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDtdObjDisInfoType.apa_sns_dttd_obj_first)
  return apa_sns_dttd_obj_first_;
}
inline void APASnsDtdObjDisInfoType::set_apa_sns_dttd_obj_first(float value) {
  set_has_apa_sns_dttd_obj_first();
  apa_sns_dttd_obj_first_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDtdObjDisInfoType.apa_sns_dttd_obj_first)
}

// optional uint32 cobj1_type = 2;
inline bool APASnsDtdObjDisInfoType::has_cobj1_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void APASnsDtdObjDisInfoType::set_has_cobj1_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void APASnsDtdObjDisInfoType::clear_has_cobj1_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void APASnsDtdObjDisInfoType::clear_cobj1_type() {
  cobj1_type_ = 0u;
  clear_has_cobj1_type();
}
inline ::google::protobuf::uint32 APASnsDtdObjDisInfoType::cobj1_type() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDtdObjDisInfoType.cobj1_type)
  return cobj1_type_;
}
inline void APASnsDtdObjDisInfoType::set_cobj1_type(::google::protobuf::uint32 value) {
  set_has_cobj1_type();
  cobj1_type_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDtdObjDisInfoType.cobj1_type)
}

// optional float apa_sns_dtd_obj_sencond = 3;
inline bool APASnsDtdObjDisInfoType::has_apa_sns_dtd_obj_sencond() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void APASnsDtdObjDisInfoType::set_has_apa_sns_dtd_obj_sencond() {
  _has_bits_[0] |= 0x00000004u;
}
inline void APASnsDtdObjDisInfoType::clear_has_apa_sns_dtd_obj_sencond() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void APASnsDtdObjDisInfoType::clear_apa_sns_dtd_obj_sencond() {
  apa_sns_dtd_obj_sencond_ = 0;
  clear_has_apa_sns_dtd_obj_sencond();
}
inline float APASnsDtdObjDisInfoType::apa_sns_dtd_obj_sencond() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDtdObjDisInfoType.apa_sns_dtd_obj_sencond)
  return apa_sns_dtd_obj_sencond_;
}
inline void APASnsDtdObjDisInfoType::set_apa_sns_dtd_obj_sencond(float value) {
  set_has_apa_sns_dtd_obj_sencond();
  apa_sns_dtd_obj_sencond_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDtdObjDisInfoType.apa_sns_dtd_obj_sencond)
}

// optional uint32 cobj2_type = 4;
inline bool APASnsDtdObjDisInfoType::has_cobj2_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void APASnsDtdObjDisInfoType::set_has_cobj2_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void APASnsDtdObjDisInfoType::clear_has_cobj2_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void APASnsDtdObjDisInfoType::clear_cobj2_type() {
  cobj2_type_ = 0u;
  clear_has_cobj2_type();
}
inline ::google::protobuf::uint32 APASnsDtdObjDisInfoType::cobj2_type() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDtdObjDisInfoType.cobj2_type)
  return cobj2_type_;
}
inline void APASnsDtdObjDisInfoType::set_cobj2_type(::google::protobuf::uint32 value) {
  set_has_cobj2_type();
  cobj2_type_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDtdObjDisInfoType.cobj2_type)
}

// optional float apa_sns_dtd_obj_three = 5;
inline bool APASnsDtdObjDisInfoType::has_apa_sns_dtd_obj_three() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void APASnsDtdObjDisInfoType::set_has_apa_sns_dtd_obj_three() {
  _has_bits_[0] |= 0x00000010u;
}
inline void APASnsDtdObjDisInfoType::clear_has_apa_sns_dtd_obj_three() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void APASnsDtdObjDisInfoType::clear_apa_sns_dtd_obj_three() {
  apa_sns_dtd_obj_three_ = 0;
  clear_has_apa_sns_dtd_obj_three();
}
inline float APASnsDtdObjDisInfoType::apa_sns_dtd_obj_three() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDtdObjDisInfoType.apa_sns_dtd_obj_three)
  return apa_sns_dtd_obj_three_;
}
inline void APASnsDtdObjDisInfoType::set_apa_sns_dtd_obj_three(float value) {
  set_has_apa_sns_dtd_obj_three();
  apa_sns_dtd_obj_three_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDtdObjDisInfoType.apa_sns_dtd_obj_three)
}

// optional uint32 cobj3_type = 6;
inline bool APASnsDtdObjDisInfoType::has_cobj3_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void APASnsDtdObjDisInfoType::set_has_cobj3_type() {
  _has_bits_[0] |= 0x00000020u;
}
inline void APASnsDtdObjDisInfoType::clear_has_cobj3_type() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void APASnsDtdObjDisInfoType::clear_cobj3_type() {
  cobj3_type_ = 0u;
  clear_has_cobj3_type();
}
inline ::google::protobuf::uint32 APASnsDtdObjDisInfoType::cobj3_type() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDtdObjDisInfoType.cobj3_type)
  return cobj3_type_;
}
inline void APASnsDtdObjDisInfoType::set_cobj3_type(::google::protobuf::uint32 value) {
  set_has_cobj3_type();
  cobj3_type_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDtdObjDisInfoType.cobj3_type)
}

// -------------------------------------------------------------------

// APASnsDisProcessType

// repeated .UssWaveInfo.APASnsDtdObjDisInfoType apa_sns_dis_buf = 1;
inline int APASnsDisProcessType::apa_sns_dis_buf_size() const {
  return apa_sns_dis_buf_.size();
}
inline void APASnsDisProcessType::clear_apa_sns_dis_buf() {
  apa_sns_dis_buf_.Clear();
}
inline ::UssWaveInfo::APASnsDtdObjDisInfoType* APASnsDisProcessType::mutable_apa_sns_dis_buf(int index) {
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.APASnsDisProcessType.apa_sns_dis_buf)
  return apa_sns_dis_buf_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDtdObjDisInfoType >*
APASnsDisProcessType::mutable_apa_sns_dis_buf() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.APASnsDisProcessType.apa_sns_dis_buf)
  return &apa_sns_dis_buf_;
}
inline const ::UssWaveInfo::APASnsDtdObjDisInfoType& APASnsDisProcessType::apa_sns_dis_buf(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDisProcessType.apa_sns_dis_buf)
  return apa_sns_dis_buf_.Get(index);
}
inline ::UssWaveInfo::APASnsDtdObjDisInfoType* APASnsDisProcessType::add_apa_sns_dis_buf() {
  // @@protoc_insertion_point(field_add:UssWaveInfo.APASnsDisProcessType.apa_sns_dis_buf)
  return apa_sns_dis_buf_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDtdObjDisInfoType >&
APASnsDisProcessType::apa_sns_dis_buf() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.APASnsDisProcessType.apa_sns_dis_buf)
  return apa_sns_dis_buf_;
}

// optional uint32 apa_sns_dtd_obj_dis_info_buf_read_index = 2;
inline bool APASnsDisProcessType::has_apa_sns_dtd_obj_dis_info_buf_read_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void APASnsDisProcessType::set_has_apa_sns_dtd_obj_dis_info_buf_read_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void APASnsDisProcessType::clear_has_apa_sns_dtd_obj_dis_info_buf_read_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void APASnsDisProcessType::clear_apa_sns_dtd_obj_dis_info_buf_read_index() {
  apa_sns_dtd_obj_dis_info_buf_read_index_ = 0u;
  clear_has_apa_sns_dtd_obj_dis_info_buf_read_index();
}
inline ::google::protobuf::uint32 APASnsDisProcessType::apa_sns_dtd_obj_dis_info_buf_read_index() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDisProcessType.apa_sns_dtd_obj_dis_info_buf_read_index)
  return apa_sns_dtd_obj_dis_info_buf_read_index_;
}
inline void APASnsDisProcessType::set_apa_sns_dtd_obj_dis_info_buf_read_index(::google::protobuf::uint32 value) {
  set_has_apa_sns_dtd_obj_dis_info_buf_read_index();
  apa_sns_dtd_obj_dis_info_buf_read_index_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDisProcessType.apa_sns_dtd_obj_dis_info_buf_read_index)
}

// optional uint32 apa_sns_dtd_obj_dis_info_buf_write_index = 3;
inline bool APASnsDisProcessType::has_apa_sns_dtd_obj_dis_info_buf_write_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void APASnsDisProcessType::set_has_apa_sns_dtd_obj_dis_info_buf_write_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void APASnsDisProcessType::clear_has_apa_sns_dtd_obj_dis_info_buf_write_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void APASnsDisProcessType::clear_apa_sns_dtd_obj_dis_info_buf_write_index() {
  apa_sns_dtd_obj_dis_info_buf_write_index_ = 0u;
  clear_has_apa_sns_dtd_obj_dis_info_buf_write_index();
}
inline ::google::protobuf::uint32 APASnsDisProcessType::apa_sns_dtd_obj_dis_info_buf_write_index() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.APASnsDisProcessType.apa_sns_dtd_obj_dis_info_buf_write_index)
  return apa_sns_dtd_obj_dis_info_buf_write_index_;
}
inline void APASnsDisProcessType::set_apa_sns_dtd_obj_dis_info_buf_write_index(::google::protobuf::uint32 value) {
  set_has_apa_sns_dtd_obj_dis_info_buf_write_index();
  apa_sns_dtd_obj_dis_info_buf_write_index_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.APASnsDisProcessType.apa_sns_dtd_obj_dis_info_buf_write_index)
}

// -------------------------------------------------------------------

// DtObjUPASnsDtObjDisInfoType_wDisValueType

// repeated float wdis_value = 1;
inline int DtObjUPASnsDtObjDisInfoType_wDisValueType::wdis_value_size() const {
  return wdis_value_.size();
}
inline void DtObjUPASnsDtObjDisInfoType_wDisValueType::clear_wdis_value() {
  wdis_value_.Clear();
}
inline float DtObjUPASnsDtObjDisInfoType_wDisValueType::wdis_value(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType.wdis_value)
  return wdis_value_.Get(index);
}
inline void DtObjUPASnsDtObjDisInfoType_wDisValueType::set_wdis_value(int index, float value) {
  wdis_value_.Set(index, value);
  // @@protoc_insertion_point(field_set:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType.wdis_value)
}
inline void DtObjUPASnsDtObjDisInfoType_wDisValueType::add_wdis_value(float value) {
  wdis_value_.Add(value);
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType.wdis_value)
}
inline const ::google::protobuf::RepeatedField< float >&
DtObjUPASnsDtObjDisInfoType_wDisValueType::wdis_value() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType.wdis_value)
  return wdis_value_;
}
inline ::google::protobuf::RepeatedField< float >*
DtObjUPASnsDtObjDisInfoType_wDisValueType::mutable_wdis_value() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType.wdis_value)
  return &wdis_value_;
}

// -------------------------------------------------------------------

// DtObjUPASnsDtObjDisInfoType_wTypeValueType

// repeated uint32 wtype_value = 1;
inline int DtObjUPASnsDtObjDisInfoType_wTypeValueType::wtype_value_size() const {
  return wtype_value_.size();
}
inline void DtObjUPASnsDtObjDisInfoType_wTypeValueType::clear_wtype_value() {
  wtype_value_.Clear();
}
inline ::google::protobuf::uint32 DtObjUPASnsDtObjDisInfoType_wTypeValueType::wtype_value(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType.wtype_value)
  return wtype_value_.Get(index);
}
inline void DtObjUPASnsDtObjDisInfoType_wTypeValueType::set_wtype_value(int index, ::google::protobuf::uint32 value) {
  wtype_value_.Set(index, value);
  // @@protoc_insertion_point(field_set:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType.wtype_value)
}
inline void DtObjUPASnsDtObjDisInfoType_wTypeValueType::add_wtype_value(::google::protobuf::uint32 value) {
  wtype_value_.Add(value);
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType.wtype_value)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
DtObjUPASnsDtObjDisInfoType_wTypeValueType::wtype_value() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType.wtype_value)
  return wtype_value_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
DtObjUPASnsDtObjDisInfoType_wTypeValueType::mutable_wtype_value() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType.wtype_value)
  return &wtype_value_;
}

// -------------------------------------------------------------------

// DtObjUPASnsDtObjDisInfoType_wXValueType

// repeated float wx_value = 1;
inline int DtObjUPASnsDtObjDisInfoType_wXValueType::wx_value_size() const {
  return wx_value_.size();
}
inline void DtObjUPASnsDtObjDisInfoType_wXValueType::clear_wx_value() {
  wx_value_.Clear();
}
inline float DtObjUPASnsDtObjDisInfoType_wXValueType::wx_value(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType.wx_value)
  return wx_value_.Get(index);
}
inline void DtObjUPASnsDtObjDisInfoType_wXValueType::set_wx_value(int index, float value) {
  wx_value_.Set(index, value);
  // @@protoc_insertion_point(field_set:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType.wx_value)
}
inline void DtObjUPASnsDtObjDisInfoType_wXValueType::add_wx_value(float value) {
  wx_value_.Add(value);
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType.wx_value)
}
inline const ::google::protobuf::RepeatedField< float >&
DtObjUPASnsDtObjDisInfoType_wXValueType::wx_value() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType.wx_value)
  return wx_value_;
}
inline ::google::protobuf::RepeatedField< float >*
DtObjUPASnsDtObjDisInfoType_wXValueType::mutable_wx_value() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType.wx_value)
  return &wx_value_;
}

// -------------------------------------------------------------------

// DtObjUPASnsDtObjDisInfoType_wYValueType

// repeated float wy_value = 1;
inline int DtObjUPASnsDtObjDisInfoType_wYValueType::wy_value_size() const {
  return wy_value_.size();
}
inline void DtObjUPASnsDtObjDisInfoType_wYValueType::clear_wy_value() {
  wy_value_.Clear();
}
inline float DtObjUPASnsDtObjDisInfoType_wYValueType::wy_value(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType.wy_value)
  return wy_value_.Get(index);
}
inline void DtObjUPASnsDtObjDisInfoType_wYValueType::set_wy_value(int index, float value) {
  wy_value_.Set(index, value);
  // @@protoc_insertion_point(field_set:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType.wy_value)
}
inline void DtObjUPASnsDtObjDisInfoType_wYValueType::add_wy_value(float value) {
  wy_value_.Add(value);
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType.wy_value)
}
inline const ::google::protobuf::RepeatedField< float >&
DtObjUPASnsDtObjDisInfoType_wYValueType::wy_value() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType.wy_value)
  return wy_value_;
}
inline ::google::protobuf::RepeatedField< float >*
DtObjUPASnsDtObjDisInfoType_wYValueType::mutable_wy_value() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType.wy_value)
  return &wy_value_;
}

// -------------------------------------------------------------------

// DtObjUPASnsDtObjDisInfoType

// repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wDisValueType wdis = 1;
inline int DtObjUPASnsDtObjDisInfoType::wdis_size() const {
  return wdis_.size();
}
inline void DtObjUPASnsDtObjDisInfoType::clear_wdis() {
  wdis_.Clear();
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType* DtObjUPASnsDtObjDisInfoType::mutable_wdis(int index) {
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wdis)
  return wdis_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType >*
DtObjUPASnsDtObjDisInfoType::mutable_wdis() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wdis)
  return &wdis_;
}
inline const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType& DtObjUPASnsDtObjDisInfoType::wdis(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wdis)
  return wdis_.Get(index);
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType* DtObjUPASnsDtObjDisInfoType::add_wdis() {
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wdis)
  return wdis_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wDisValueType >&
DtObjUPASnsDtObjDisInfoType::wdis() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wdis)
  return wdis_;
}

// repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wTypeValueType wtype = 2;
inline int DtObjUPASnsDtObjDisInfoType::wtype_size() const {
  return wtype_.size();
}
inline void DtObjUPASnsDtObjDisInfoType::clear_wtype() {
  wtype_.Clear();
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType* DtObjUPASnsDtObjDisInfoType::mutable_wtype(int index) {
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wtype)
  return wtype_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType >*
DtObjUPASnsDtObjDisInfoType::mutable_wtype() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wtype)
  return &wtype_;
}
inline const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType& DtObjUPASnsDtObjDisInfoType::wtype(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wtype)
  return wtype_.Get(index);
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType* DtObjUPASnsDtObjDisInfoType::add_wtype() {
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wtype)
  return wtype_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wTypeValueType >&
DtObjUPASnsDtObjDisInfoType::wtype() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wtype)
  return wtype_;
}

// repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wXValueType wx = 3;
inline int DtObjUPASnsDtObjDisInfoType::wx_size() const {
  return wx_.size();
}
inline void DtObjUPASnsDtObjDisInfoType::clear_wx() {
  wx_.Clear();
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType* DtObjUPASnsDtObjDisInfoType::mutable_wx(int index) {
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wx)
  return wx_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType >*
DtObjUPASnsDtObjDisInfoType::mutable_wx() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wx)
  return &wx_;
}
inline const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType& DtObjUPASnsDtObjDisInfoType::wx(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wx)
  return wx_.Get(index);
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType* DtObjUPASnsDtObjDisInfoType::add_wx() {
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wx)
  return wx_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wXValueType >&
DtObjUPASnsDtObjDisInfoType::wx() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wx)
  return wx_;
}

// repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wYValueType wy = 4;
inline int DtObjUPASnsDtObjDisInfoType::wy_size() const {
  return wy_.size();
}
inline void DtObjUPASnsDtObjDisInfoType::clear_wy() {
  wy_.Clear();
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType* DtObjUPASnsDtObjDisInfoType::mutable_wy(int index) {
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wy)
  return wy_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType >*
DtObjUPASnsDtObjDisInfoType::mutable_wy() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wy)
  return &wy_;
}
inline const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType& DtObjUPASnsDtObjDisInfoType::wy(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wy)
  return wy_.Get(index);
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType* DtObjUPASnsDtObjDisInfoType::add_wy() {
  // @@protoc_insertion_point(field_add:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wy)
  return wy_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType_wYValueType >&
DtObjUPASnsDtObjDisInfoType::wy() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.DtObjUPASnsDtObjDisInfoType.wy)
  return wy_;
}

// -------------------------------------------------------------------

// Uss_Data

// optional float front0 = 1;
inline bool Uss_Data::has_front0() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Uss_Data::set_has_front0() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Uss_Data::clear_has_front0() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Uss_Data::clear_front0() {
  front0_ = 0;
  clear_has_front0();
}
inline float Uss_Data::front0() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.front0)
  return front0_;
}
inline void Uss_Data::set_front0(float value) {
  set_has_front0();
  front0_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.front0)
}

// optional float front1 = 2;
inline bool Uss_Data::has_front1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Uss_Data::set_has_front1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Uss_Data::clear_has_front1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Uss_Data::clear_front1() {
  front1_ = 0;
  clear_has_front1();
}
inline float Uss_Data::front1() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.front1)
  return front1_;
}
inline void Uss_Data::set_front1(float value) {
  set_has_front1();
  front1_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.front1)
}

// optional float front2 = 3;
inline bool Uss_Data::has_front2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Uss_Data::set_has_front2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Uss_Data::clear_has_front2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Uss_Data::clear_front2() {
  front2_ = 0;
  clear_has_front2();
}
inline float Uss_Data::front2() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.front2)
  return front2_;
}
inline void Uss_Data::set_front2(float value) {
  set_has_front2();
  front2_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.front2)
}

// optional float front3 = 4;
inline bool Uss_Data::has_front3() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Uss_Data::set_has_front3() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Uss_Data::clear_has_front3() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Uss_Data::clear_front3() {
  front3_ = 0;
  clear_has_front3();
}
inline float Uss_Data::front3() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.front3)
  return front3_;
}
inline void Uss_Data::set_front3(float value) {
  set_has_front3();
  front3_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.front3)
}

// optional float rear0 = 5;
inline bool Uss_Data::has_rear0() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Uss_Data::set_has_rear0() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Uss_Data::clear_has_rear0() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Uss_Data::clear_rear0() {
  rear0_ = 0;
  clear_has_rear0();
}
inline float Uss_Data::rear0() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.rear0)
  return rear0_;
}
inline void Uss_Data::set_rear0(float value) {
  set_has_rear0();
  rear0_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.rear0)
}

// optional float rear1 = 6;
inline bool Uss_Data::has_rear1() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Uss_Data::set_has_rear1() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Uss_Data::clear_has_rear1() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Uss_Data::clear_rear1() {
  rear1_ = 0;
  clear_has_rear1();
}
inline float Uss_Data::rear1() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.rear1)
  return rear1_;
}
inline void Uss_Data::set_rear1(float value) {
  set_has_rear1();
  rear1_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.rear1)
}

// optional float rear2 = 7;
inline bool Uss_Data::has_rear2() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Uss_Data::set_has_rear2() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Uss_Data::clear_has_rear2() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Uss_Data::clear_rear2() {
  rear2_ = 0;
  clear_has_rear2();
}
inline float Uss_Data::rear2() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.rear2)
  return rear2_;
}
inline void Uss_Data::set_rear2(float value) {
  set_has_rear2();
  rear2_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.rear2)
}

// optional float rear3 = 8;
inline bool Uss_Data::has_rear3() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Uss_Data::set_has_rear3() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Uss_Data::clear_has_rear3() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Uss_Data::clear_rear3() {
  rear3_ = 0;
  clear_has_rear3();
}
inline float Uss_Data::rear3() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.rear3)
  return rear3_;
}
inline void Uss_Data::set_rear3(float value) {
  set_has_rear3();
  rear3_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.rear3)
}

// optional float left_side0 = 9;
inline bool Uss_Data::has_left_side0() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Uss_Data::set_has_left_side0() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Uss_Data::clear_has_left_side0() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Uss_Data::clear_left_side0() {
  left_side0_ = 0;
  clear_has_left_side0();
}
inline float Uss_Data::left_side0() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.left_side0)
  return left_side0_;
}
inline void Uss_Data::set_left_side0(float value) {
  set_has_left_side0();
  left_side0_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.left_side0)
}

// optional float left_side1 = 10;
inline bool Uss_Data::has_left_side1() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Uss_Data::set_has_left_side1() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Uss_Data::clear_has_left_side1() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Uss_Data::clear_left_side1() {
  left_side1_ = 0;
  clear_has_left_side1();
}
inline float Uss_Data::left_side1() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.left_side1)
  return left_side1_;
}
inline void Uss_Data::set_left_side1(float value) {
  set_has_left_side1();
  left_side1_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.left_side1)
}

// optional float right_side0 = 11;
inline bool Uss_Data::has_right_side0() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Uss_Data::set_has_right_side0() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Uss_Data::clear_has_right_side0() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Uss_Data::clear_right_side0() {
  right_side0_ = 0;
  clear_has_right_side0();
}
inline float Uss_Data::right_side0() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.right_side0)
  return right_side0_;
}
inline void Uss_Data::set_right_side0(float value) {
  set_has_right_side0();
  right_side0_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.right_side0)
}

// optional float right_side1 = 12;
inline bool Uss_Data::has_right_side1() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Uss_Data::set_has_right_side1() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Uss_Data::clear_has_right_side1() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Uss_Data::clear_right_side1() {
  right_side1_ = 0;
  clear_has_right_side1();
}
inline float Uss_Data::right_side1() const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.Uss_Data.right_side1)
  return right_side1_;
}
inline void Uss_Data::set_right_side1(float value) {
  set_has_right_side1();
  right_side1_ = value;
  // @@protoc_insertion_point(field_set:UssWaveInfo.Uss_Data.right_side1)
}

// -------------------------------------------------------------------

// UssWaveInfo

// optional .Common.Header header = 1;
inline bool UssWaveInfo::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UssWaveInfo::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UssWaveInfo::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::Common::Header& UssWaveInfo::_internal_header() const {
  return *header_;
}
inline const ::Common::Header& UssWaveInfo::header() const {
  const ::Common::Header* p = header_;
  // @@protoc_insertion_point(field_get:UssWaveInfo.UssWaveInfo.header)
  return p != NULL ? *p : *reinterpret_cast<const ::Common::Header*>(
      &::Common::_Header_default_instance_);
}
inline ::Common::Header* UssWaveInfo::release_header() {
  // @@protoc_insertion_point(field_release:UssWaveInfo.UssWaveInfo.header)
  clear_has_header();
  ::Common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::Common::Header* UssWaveInfo::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::Common::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.UssWaveInfo.header)
  return header_;
}
inline void UssWaveInfo::set_allocated_header(::Common::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:UssWaveInfo.UssWaveInfo.header)
}

// repeated bool uss_State = 2;
inline int UssWaveInfo::uss_state_size() const {
  return uss_state_.size();
}
inline void UssWaveInfo::clear_uss_state() {
  uss_state_.Clear();
}
inline bool UssWaveInfo::uss_state(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.UssWaveInfo.uss_State)
  return uss_state_.Get(index);
}
inline void UssWaveInfo::set_uss_state(int index, bool value) {
  uss_state_.Set(index, value);
  // @@protoc_insertion_point(field_set:UssWaveInfo.UssWaveInfo.uss_State)
}
inline void UssWaveInfo::add_uss_state(bool value) {
  uss_state_.Add(value);
  // @@protoc_insertion_point(field_add:UssWaveInfo.UssWaveInfo.uss_State)
}
inline const ::google::protobuf::RepeatedField< bool >&
UssWaveInfo::uss_state() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.UssWaveInfo.uss_State)
  return uss_state_;
}
inline ::google::protobuf::RepeatedField< bool >*
UssWaveInfo::mutable_uss_state() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.UssWaveInfo.uss_State)
  return &uss_state_;
}

// repeated float upa_Ori_Dis_Buffer = 3;
inline int UssWaveInfo::upa_ori_dis_buffer_size() const {
  return upa_ori_dis_buffer_.size();
}
inline void UssWaveInfo::clear_upa_ori_dis_buffer() {
  upa_ori_dis_buffer_.Clear();
}
inline float UssWaveInfo::upa_ori_dis_buffer(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.UssWaveInfo.upa_Ori_Dis_Buffer)
  return upa_ori_dis_buffer_.Get(index);
}
inline void UssWaveInfo::set_upa_ori_dis_buffer(int index, float value) {
  upa_ori_dis_buffer_.Set(index, value);
  // @@protoc_insertion_point(field_set:UssWaveInfo.UssWaveInfo.upa_Ori_Dis_Buffer)
}
inline void UssWaveInfo::add_upa_ori_dis_buffer(float value) {
  upa_ori_dis_buffer_.Add(value);
  // @@protoc_insertion_point(field_add:UssWaveInfo.UssWaveInfo.upa_Ori_Dis_Buffer)
}
inline const ::google::protobuf::RepeatedField< float >&
UssWaveInfo::upa_ori_dis_buffer() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.UssWaveInfo.upa_Ori_Dis_Buffer)
  return upa_ori_dis_buffer_;
}
inline ::google::protobuf::RepeatedField< float >*
UssWaveInfo::mutable_upa_ori_dis_buffer() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.UssWaveInfo.upa_Ori_Dis_Buffer)
  return &upa_ori_dis_buffer_;
}

// repeated float apa_Ori_Dis_Buffer = 4;
inline int UssWaveInfo::apa_ori_dis_buffer_size() const {
  return apa_ori_dis_buffer_.size();
}
inline void UssWaveInfo::clear_apa_ori_dis_buffer() {
  apa_ori_dis_buffer_.Clear();
}
inline float UssWaveInfo::apa_ori_dis_buffer(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.UssWaveInfo.apa_Ori_Dis_Buffer)
  return apa_ori_dis_buffer_.Get(index);
}
inline void UssWaveInfo::set_apa_ori_dis_buffer(int index, float value) {
  apa_ori_dis_buffer_.Set(index, value);
  // @@protoc_insertion_point(field_set:UssWaveInfo.UssWaveInfo.apa_Ori_Dis_Buffer)
}
inline void UssWaveInfo::add_apa_ori_dis_buffer(float value) {
  apa_ori_dis_buffer_.Add(value);
  // @@protoc_insertion_point(field_add:UssWaveInfo.UssWaveInfo.apa_Ori_Dis_Buffer)
}
inline const ::google::protobuf::RepeatedField< float >&
UssWaveInfo::apa_ori_dis_buffer() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.UssWaveInfo.apa_Ori_Dis_Buffer)
  return apa_ori_dis_buffer_;
}
inline ::google::protobuf::RepeatedField< float >*
UssWaveInfo::mutable_apa_ori_dis_buffer() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.UssWaveInfo.apa_Ori_Dis_Buffer)
  return &apa_ori_dis_buffer_;
}

// repeated .UssWaveInfo.APASnsDisProcessType apa_Dis_Info_Buf = 5;
inline int UssWaveInfo::apa_dis_info_buf_size() const {
  return apa_dis_info_buf_.size();
}
inline void UssWaveInfo::clear_apa_dis_info_buf() {
  apa_dis_info_buf_.Clear();
}
inline ::UssWaveInfo::APASnsDisProcessType* UssWaveInfo::mutable_apa_dis_info_buf(int index) {
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.UssWaveInfo.apa_Dis_Info_Buf)
  return apa_dis_info_buf_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDisProcessType >*
UssWaveInfo::mutable_apa_dis_info_buf() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.UssWaveInfo.apa_Dis_Info_Buf)
  return &apa_dis_info_buf_;
}
inline const ::UssWaveInfo::APASnsDisProcessType& UssWaveInfo::apa_dis_info_buf(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.UssWaveInfo.apa_Dis_Info_Buf)
  return apa_dis_info_buf_.Get(index);
}
inline ::UssWaveInfo::APASnsDisProcessType* UssWaveInfo::add_apa_dis_info_buf() {
  // @@protoc_insertion_point(field_add:UssWaveInfo.UssWaveInfo.apa_Dis_Info_Buf)
  return apa_dis_info_buf_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::APASnsDisProcessType >&
UssWaveInfo::apa_dis_info_buf() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.UssWaveInfo.apa_Dis_Info_Buf)
  return apa_dis_info_buf_;
}

// repeated .UssWaveInfo.DtObjUPASnsDtObjDisInfoType upa_Dis_Info_Buf = 6;
inline int UssWaveInfo::upa_dis_info_buf_size() const {
  return upa_dis_info_buf_.size();
}
inline void UssWaveInfo::clear_upa_dis_info_buf() {
  upa_dis_info_buf_.Clear();
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType* UssWaveInfo::mutable_upa_dis_info_buf(int index) {
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.UssWaveInfo.upa_Dis_Info_Buf)
  return upa_dis_info_buf_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType >*
UssWaveInfo::mutable_upa_dis_info_buf() {
  // @@protoc_insertion_point(field_mutable_list:UssWaveInfo.UssWaveInfo.upa_Dis_Info_Buf)
  return &upa_dis_info_buf_;
}
inline const ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType& UssWaveInfo::upa_dis_info_buf(int index) const {
  // @@protoc_insertion_point(field_get:UssWaveInfo.UssWaveInfo.upa_Dis_Info_Buf)
  return upa_dis_info_buf_.Get(index);
}
inline ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType* UssWaveInfo::add_upa_dis_info_buf() {
  // @@protoc_insertion_point(field_add:UssWaveInfo.UssWaveInfo.upa_Dis_Info_Buf)
  return upa_dis_info_buf_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UssWaveInfo::DtObjUPASnsDtObjDisInfoType >&
UssWaveInfo::upa_dis_info_buf() const {
  // @@protoc_insertion_point(field_list:UssWaveInfo.UssWaveInfo.upa_Dis_Info_Buf)
  return upa_dis_info_buf_;
}

// optional .UssWaveInfo.Uss_Data uss_dis = 7;
inline bool UssWaveInfo::has_uss_dis() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UssWaveInfo::set_has_uss_dis() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UssWaveInfo::clear_has_uss_dis() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UssWaveInfo::clear_uss_dis() {
  if (uss_dis_ != NULL) uss_dis_->Clear();
  clear_has_uss_dis();
}
inline const ::UssWaveInfo::Uss_Data& UssWaveInfo::_internal_uss_dis() const {
  return *uss_dis_;
}
inline const ::UssWaveInfo::Uss_Data& UssWaveInfo::uss_dis() const {
  const ::UssWaveInfo::Uss_Data* p = uss_dis_;
  // @@protoc_insertion_point(field_get:UssWaveInfo.UssWaveInfo.uss_dis)
  return p != NULL ? *p : *reinterpret_cast<const ::UssWaveInfo::Uss_Data*>(
      &::UssWaveInfo::_Uss_Data_default_instance_);
}
inline ::UssWaveInfo::Uss_Data* UssWaveInfo::release_uss_dis() {
  // @@protoc_insertion_point(field_release:UssWaveInfo.UssWaveInfo.uss_dis)
  clear_has_uss_dis();
  ::UssWaveInfo::Uss_Data* temp = uss_dis_;
  uss_dis_ = NULL;
  return temp;
}
inline ::UssWaveInfo::Uss_Data* UssWaveInfo::mutable_uss_dis() {
  set_has_uss_dis();
  if (uss_dis_ == NULL) {
    auto* p = CreateMaybeMessage<::UssWaveInfo::Uss_Data>(GetArenaNoVirtual());
    uss_dis_ = p;
  }
  // @@protoc_insertion_point(field_mutable:UssWaveInfo.UssWaveInfo.uss_dis)
  return uss_dis_;
}
inline void UssWaveInfo::set_allocated_uss_dis(::UssWaveInfo::Uss_Data* uss_dis) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete uss_dis_;
  }
  if (uss_dis) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      uss_dis = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, uss_dis, submessage_arena);
    }
    set_has_uss_dis();
  } else {
    clear_has_uss_dis();
  }
  uss_dis_ = uss_dis;
  // @@protoc_insertion_point(field_set_allocated:UssWaveInfo.UssWaveInfo.uss_dis)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace UssWaveInfo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_uss_5fwave_5finfo_2eproto
