uint64 lane_id
int32 sequence_id
Point3d[] points_on_central_line
float64[] central_points_offset
float64[] width
float64[] curvature 
float64[] heading
int32 lane_direction
int32 lane_type
int64 left_lane_boundary_id
int64 right_lane_boundary_id
int64 left_road_boundary_id
int64 right_road_boundary_id
float64 min_speed_limit
float64 max_speed_limit 
uint64[] predecessor_lane_id
uint64[] successor_lane_id
uint64 left_neighbor_forward_lane_id
uint64 right_neighbor_forward_lane_id
uint64 left_neighbor_reverse_lane_id
uint64 right_neighbor_reverse_lane_id
uint64 lane_group_id
OverLap[] overlaps


