int32 fix_lane_virtual_id 
int32 origin_lane_virtual_id 
int32 target_lane_virtual_id 
bool is_lc_valid 
int32 lc_valid_cnt 
int32 lc_invalid_obj_id 
string lc_invalid_reason 
bool lc_valid_back 
int32 lc_back_obj_id 
int32 lc_back_cnt 
string lc_back_reason 
int32[] near_car_ids_origin 
int32[] near_car_ids_target 

float32 v_relative_left_lane 
bool is_faster_left_lane 
int32 faster_left_lane_cnt 
float32 v_relative_right_lane 
bool is_faster_right_lane 
int32 faster_right_lane_cnt 

int32[] left_alc_car_ids 
int32[] right_alc_car_ids 
bool is_forbid_left_alc_car 
bool is_forbid_right_alc_car 
bool is_side_borrow_bicycle_lane 
bool is_side_borrow_lane 

bool has_origin_lane 
bool has_target_lane 
bool enable_left_lc 
bool enable_right_lc 

int32 turn_light 
int32 map_turn_light 
int32 lc_request 
int32 lc_request_source 
int32 lc_turn_light 
string act_request_source 
string lc_back_invalid_reason 
int32 current_state 