LateralPathOptimizerInitState init_state
float64[] ref_x_vec
float64[] ref_y_vec
float64[] ref_theta_vec 

float64 last_theta
float64 last_y
float64 last_x

float64[] k_max_vec
float64[] k_min_vec
float64[] u_min_vec
float64[] u_max_vec

float64 r_min
float64 curv_factor
float64 delta_max
float64 ref_vel

float64 q_ref_x
float64 q_ref_y
float64 q_ref_theta
float64 q_terminal_theta
float64 q_terminal_x
float64 q_terminal_y
float64 q_k
float64 q_u
float64 q_k_bound
float64 q_u_bound


float64[] control_vec
float64 ref_s

float64[] last_x_vec
float64[] last_y_vec
float64[] last_theta_vec
float64[] last_k_vec

uint32 terminal_point_num