LateralInitState init_state 

float64[] ref_x_vec 
float64[] ref_y_vec 
float64[] ref_theta_vec 

float64[] last_x_vec 
float64[] last_y_vec 
float64[] last_theta_vec 

float64 ref_vel 
float64 curv_factor 

float64[] soft_upper_bound_x0_vec 
float64[] soft_upper_bound_y0_vec 
float64[] soft_upper_bound_x1_vec 
float64[] soft_upper_bound_y1_vec 

float64[] soft_lower_bound_x0_vec 
float64[] soft_lower_bound_y0_vec 
float64[] soft_lower_bound_x1_vec 
float64[] soft_lower_bound_y1_vec 

float64[] hard_upper_bound_x0_vec 
float64[] hard_upper_bound_y0_vec 
float64[] hard_upper_bound_x1_vec 
float64[] hard_upper_bound_y1_vec 

float64[] hard_lower_bound_x0_vec 
float64[] hard_lower_bound_y0_vec 
float64[] hard_lower_bound_x1_vec 
float64[] hard_lower_bound_y1_vec 

float64 acc_bound 
float64 jerk_bound 

float64 q_ref_x 
float64 q_ref_y 
float64 q_ref_theta 

float64 q_continuity 
float64 q_acc 
float64 q_jerk 
float64 q_snap 

float64 q_acc_bound 
float64 q_jerk_bound 

float64 q_soft_corridor 
float64 q_hard_corridor 

float64[] control_vec 
bool complete_follow 
uint32 motion_plan_concerned_index 