LongitudinalInitState init_state 

float64[] ref_pos_vec 
float64[] ref_vel_vec 

float64[] soft_pos_max_vec 
float64[] soft_pos_min_vec 
float64[] hard_pos_max_vec 
float64[] hard_pos_min_vec 
float64[] vel_max_vec 
float64[] vel_min_vec 

float64[] acc_max_vec 
float64[] acc_min_vec 
float64[] jerk_max_vec 
float64[] jerk_min_vec 

float64 s_stop 

float64 q_ref_pos 
float64 q_ref_vel 
float64 q_acc 
float64 q_jerk 
float64 q_snap 
float64 q_soft_pos_bound 
float64 q_hard_pos_bound 
float64 q_vel_bound 
float64 q_acc_bound 
float64 q_jerk_bound 
float64 q_stop_s 
float64 q_sv_bound 

float64[] sv_bound_s_0
float64[] sv_bound_s_1
float64[] sv_bound_s_2
float64[] sv_bound_s_3
float64[] sv_bound_s_4
float64[] sv_bound_s_5
float64[] sv_bound_v_0
float64[] sv_bound_v_1
float64[] sv_bound_v_2
float64[] sv_bound_v_3
float64[] sv_bound_v_4
float64[] sv_bound_v_5