#include "st_graph.h"

#include <math.h>
#include <sys/param.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <iomanip>
#include <iostream>
#include <limits>
#include <memory>
#include <ostream>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

#include "agent/agent.h"
#include "common_c.h"
#include "math/line_segment2d.h"
#include "math/math_utils.h"
#include "math/vec2d.h"
#include "planning_context.h"
#include "speed/st_point.h"
#include "st_boundary.h"
#include "st_graph/st_graph_input.h"
#include "st_graph/st_point.h"
#include "st_graph_utils.h"
#include "utils/kd_path.h"
#include "utils/path_point.h"
#include "virtual_lane.h"

namespace planning {
namespace speed {

namespace {

using namespace planning_math;

// constexpr double kSearchBuffer = 5.0;
constexpr double kMathEpsilon = 1e-10;
constexpr double kTimeResolution = 0.2;
constexpr double kConsideredReverseVruTime = 2.0;
}  // namespace

bool STGraph::Init(const std::shared_ptr<StGraphInput>& st_graph_input) {
  st_graph_input_ = st_graph_input;
  Reset();
  MakeAgentStBoundaries();

  // TODO: Cutout Cutin(trajectory generated by AgentTrajectoryCalculator) need
  // backward extend st boundaries
  if (st_graph_input_->enable_backward_extend_st_boundary()) {
    BackwardExtendStBoundaries();
  }

  // TODO: add cautin yield and cross agent decision first
  StGraphUtils::DetermineCautionYieldDecision(
      st_graph_input_, st_graph_input->lane_change_status(),
      st_graph_input->lane_change_request(), agent_id_st_boundaries_map_,
      boundary_id_st_boundaries_map_, caution_yield_agent_ids_);
  // StGraphUtils::SetCrossingAgentCautionYieldDecision(
  //     st_graph_input_, agent_id_st_boundaries_map_,
  //     boundary_id_st_boundaries_map_);

  MakeStPointsTable();

  ConstructDefaultStPassCorridor();

  AddStGraphDataToProto();

  return true;
}

bool STGraph::InsertAgent(const agent::Agent& agent,
                          const StBoundaryType type) {
  if (agent.agent_id() < 0) {
    return false;
  }

  if (neighbor_agent_id_st_boundaries_map_.find(agent.agent_id()) !=
      neighbor_agent_id_st_boundaries_map_.end()) {
    // already exist, do not insert again
    return false;
  }

  const bool is_static = StGraphUtils::IsStaticAgent(agent);
  if (is_static) {
    MakeStaticAgentStBoundary(agent, type);
  } else {
    MakeDynamicAgentStBoundary(agent, type);
  }
  return true;
}

void STGraph::MakeAgentStBoundaries() {
  ignore_agent_ids_.clear();
  neighbor_corridor_yield_info_map_.clear();
  neighbor_corridor_overtake_info_map_.clear();
  const auto& agents = st_graph_input_->filtered_agents();
  for (const auto agent : agents) {
    if (nullptr == agent) {
      continue;
    }
    const bool is_static = StGraphUtils::IsStaticAgent(*agent);
    if (is_static) {
      MakeStaticAgentStBoundary(*agent, StBoundaryType::NORMAL);
    } else {
      MakeDynamicAgentStBoundary(*agent, StBoundaryType::NORMAL);
    }
  }

  // for (const auto agent : agents) {
  //   if (nullptr == agent) {
  //     continue;
  //   }
  //   const int32_t agent_id = agent->agent_id();
  //   auto iter_static = static_close_pass_candicate_agent_ids_.find(agent_id);
  //   auto iter_dynamic =
  //   dynamic_close_pass_candicate_agent_ids_.find(agent_id); if (iter_static
  //   == static_close_pass_candicate_agent_ids_.end() &&
  //       iter_dynamic == dynamic_close_pass_candicate_agent_ids_.end()) {
  //     continue;
  //   }
  //   const bool is_static = StGraphUtils::IsStaticAgent(*agent);
  //   const bool reuse_for_close_pass = true;
  //   // TODO:different buffer for vru,truck and normal agent
  //   const double extra_lateral_buffer_for_close_pass =
  //       agent->is_vru() ? 1.0 : 0.5;
  //   if (is_static) {
  //     MakeStaticAgentStBoundary(*agent, StBoundaryType::NORMAL,
  //                               reuse_for_close_pass,
  //                               extra_lateral_buffer_for_close_pass);
  //   } else {
  //     MakeDynamicAgentStBoundary(*agent, StBoundaryType::NORMAL,
  //                                reuse_for_close_pass,
  //                                extra_lateral_buffer_for_close_pass);
  //   }
  // }

  // debug

  // update st_boundary for lane change
  const auto* front_agent_of_target = st_graph_input_->front_agent_of_target();
  const auto* rear_agent_of_target = st_graph_input_->rear_agent_of_target();
  const double safety_buffer_m =
      st_graph_input_->front_agent_lower_s_safety_buffer_for_lane_change();

  StGraphUtils::PreUpdateStBoundaryForLaneChange(
      agent_id_st_boundaries_map_, front_agent_of_target, rear_agent_of_target,
      safety_buffer_m, &boundary_id_st_boundaries_map_);

  StGraphUtils::UpdateStBoundaryForLaneChange(
      agent_id_st_boundaries_map_, front_agent_of_target, rear_agent_of_target,
      safety_buffer_m, &boundary_id_st_boundaries_map_);
  // Crop rear car st boundary in need during lane changing.
  StGraphUtils::UpdateStBoundaryForOvertaking(
      st_graph_input_, agent_id_st_boundaries_map_, rear_agent_of_target,
      &boundary_id_st_boundaries_map_);
}

void STGraph::MakeStaticAgentStBoundary(
    const agent::Agent& agent, const StBoundaryType type,
    const bool reuse_for_close_pass,
    const double extra_lateral_buffer_for_close_pass) {
  const bool is_large_agent =
      StGraphUtils::IsLargeAgent(agent) && type == StBoundaryType::NORMAL;
  const int32_t reserve_num = st_graph_input_->reserve_num();
  const bool is_lane_keeping = st_graph_input_->is_lane_keeping();
  const auto& init_point = st_graph_input_->planning_init_point();
  const auto& planned_kd_path = st_graph_input_->processed_path();
  const auto ptr_ego_lane = st_graph_input_->ego_lane();
  const auto ptr_virtual_lane_manager =
      st_graph_input_->ptr_virtual_lane_manager();
  const auto* path_border_querier = st_graph_input_->path_border_querier();
  auto mutable_agent_manager = st_graph_input_->mutable_agent_manager();
  const double expand_buffer =
      st_graph_input_->large_agent_expand_param_for_consistency();
  const double small_expand_buffer =
      st_graph_input_->large_agent_small_expand_param_for_consistency();
  const auto& planning_init_point_box =
      st_graph_input_->planning_init_point_box();
  const bool is_rads_scene = st_graph_input_->is_rads_scene();
  if (nullptr == planned_kd_path || reserve_num <= 0 ||
      nullptr == mutable_agent_manager || nullptr == ptr_ego_lane ||
      nullptr == path_border_querier || nullptr == ptr_virtual_lane_manager ||
      nullptr == mutable_agent_manager->mutable_agent(agent.agent_id())) {
    return;
  }
  auto* mutable_agent = mutable_agent_manager->mutable_agent(agent.agent_id());
  auto* mutable_agent_st_info = mutable_agent->mutable_agent_st_info();

  // const std::shared_ptr<VirtualLane> ptr_obj_lane = nullptr;
  double nearest_s = 0.0;
  double nearest_l = 0.0;
  const auto& ptr_obj_lane = ptr_virtual_lane_manager->GetNearestLane(
      {agent.x(), agent.y()}, &nearest_s, &nearest_l);

  // check whether is candicate for close pass
  bool is_candicate_for_close_pass =
      (!reuse_for_close_pass) && (nullptr != ptr_obj_lane) &&
      StGraphUtils::CheckCandicateAgentForClosePass(
          is_lane_keeping, init_point, planned_kd_path, ptr_ego_lane,
          ptr_obj_lane, agent, type, is_rads_scene);

  const bool consider_virtual_time_range =
      (agent.type() == agent::AgentType::VIRTUAL ||
       type == StBoundaryType::EXPAND) &&
      agent.is_time_range_valid();
  const auto& time_range = consider_virtual_time_range
                               ? agent.time_range()
                               : st_graph_input_->time_range();
  const auto& path_range = st_graph_input_->path_range();

  double lon_buffer = st_graph_input_->GetSuitableLonBuffer(agent);

  double lat_buffer = st_graph_input_->GetSuitableLateralBuffer(agent);
  int32_t prev_st_count = 0;
  bool is_in_st_graph = false;
  lat_buffer = StGraphUtils::RecalculateLateralBufferForLargeAgent(
      init_point, *mutable_agent_manager, agent, expand_buffer,
      small_expand_buffer, lat_buffer, &prev_st_count);

  lat_buffer = reuse_for_close_pass
                   ? lat_buffer + extra_lateral_buffer_for_close_pass
                   : lat_buffer;

  auto obs_box = agent.box();
  obs_box.LateralExtend(lat_buffer * 2.0);
  obs_box.LongitudinalExtend(lon_buffer * 2.0);
  // max_s min_s max_l min_l
  std::vector<double> agent_sl_boundary(4);
  std::vector<std::pair<int32_t, Vec2d>> considered_corners;

  StGraphUtils::CalculateAgentSLBoundary(planned_kd_path, obs_box, path_range,
                                         type, &agent_sl_boundary,
                                         &considered_corners);
  std::vector<std::pair<STPoint, STPoint>> st_point_pairs;
  st_point_pairs.reserve(reserve_num);
  double lower_s = std::numeric_limits<double>::max();
  double upper_s = std::numeric_limits<double>::lowest();
  const int64_t boundary_id = (agent.agent_id() << 8) + 0;
  double min_t = std::numeric_limits<double>::max();
  const double max_l = agent_sl_boundary[2];
  const double min_l = agent_sl_boundary[3];
  if (StGraphUtils::CalculateSRange(
          planned_kd_path, *path_border_querier, obs_box, type, path_range,
          agent_sl_boundary, considered_corners, planning_init_point_box,
          &lower_s, &upper_s, is_rads_scene)) {
    for (double t = time_range.first; t < time_range.second;
         t += kTimeResolution) {
      min_t = std::fmin(min_t, t);
      st_point_pairs.emplace_back(
          STPoint(lower_s, t, agent.agent_id(), boundary_id, 0.0, 0.0, min_l),
          STPoint(upper_s, t, agent.agent_id(), boundary_id, 0.0, 0.0, max_l));
    }
  }
  std::vector<int64_t> st_boundaries;
  if (!st_point_pairs.empty()) {
    std::unique_ptr<STBoundary> st_boundary(new STBoundary(st_point_pairs));
    st_boundary->set_id(boundary_id);
    if (type == StBoundaryType::NEIGHBOR) {
      neighbor_boundary_id_st_boundaries_map_.insert(
          std::make_pair(boundary_id, std::move(st_boundary)));
    } else if (type == StBoundaryType::NORMAL) {
      reuse_for_close_pass
          ? close_pass_boundary_id_st_boundaries_map_.insert(
                std::make_pair(boundary_id, std::move(st_boundary)))
          : boundary_id_st_boundaries_map_.insert(
                std::make_pair(boundary_id, std::move(st_boundary)));
    } else if (type == StBoundaryType::EXPAND) {
      expand_boundary_id_st_boundaries_map_.insert(
          std::make_pair(boundary_id, std::move(st_boundary)));
    }
    st_boundaries.emplace_back(boundary_id);
  }
  if (!st_boundaries.empty()) {
    if (type == StBoundaryType::NEIGHBOR) {
      neighbor_agent_id_st_boundaries_map_[agent.agent_id()] = st_boundaries;
    } else if (type == StBoundaryType::NORMAL) {
      reuse_for_close_pass
          ? close_pass_agent_id_st_boundaries_map_[agent.agent_id()] =
                st_boundaries
          : agent_id_st_boundaries_map_[agent.agent_id()] = st_boundaries;
      is_in_st_graph = true && !reuse_for_close_pass;
    } else if (type == StBoundaryType::EXPAND) {
      expand_agent_id_st_boundaries_map_[agent.agent_id()] = st_boundaries;
    }
  } else if (is_candicate_for_close_pass) {
    // the agent has no original st boundary and is candicate for close pass
    static_close_pass_candicate_agent_ids_.insert(agent.agent_id());
  }
  if (is_large_agent && !reuse_for_close_pass) {
    mutable_agent_st_info->is_in_st_graph_ = is_in_st_graph;
    mutable_agent_st_info->lateral_buffer_ = lat_buffer;
    mutable_agent_st_info->st_graph_count_ =
        is_in_st_graph ? ++prev_st_count : 0;
    mutable_agent_st_info->min_t_ = min_t;
  }
}

void STGraph::MakeDynamicAgentStBoundary(
    const agent::Agent& agent, const StBoundaryType type,
    const bool reuse_for_close_pass,
    const double extra_lateral_buffer_for_close_pass) {
  const bool is_large_agent =
      StGraphUtils::IsLargeAgent(agent) && type == StBoundaryType::NORMAL;
  const auto& init_point = st_graph_input_->planning_init_point();
  const auto ptr_virtual_lane_manager =
      st_graph_input_->ptr_virtual_lane_manager();
  const bool is_lane_keeping = st_graph_input_->is_lane_keeping();
  const bool is_in_lane_borrow_status =
      st_graph_input_->is_in_lane_borrow_status();
  const auto ptr_ego_lane = st_graph_input_->ego_lane();
  const int32_t reserve_num = st_graph_input_->reserve_num();
  const auto planned_kd_path = st_graph_input_->processed_path();
  const std::shared_ptr<planning_math::KDPath> ego_motion_simulation_path =
      st_graph_input_->ego_motion_simulation_result()
          ? st_graph_input_->ego_motion_simulation_result()
                ->lat_lon_vehicle_motion_path_ptr
          : nullptr;
  const auto path_border_querier = st_graph_input_->path_border_querier();
  auto mutable_agent_manager = st_graph_input_->mutable_agent_manager();
  const double expand_buffer =
      st_graph_input_->large_agent_expand_param_for_consistency();
  const double small_expand_buffer =
      st_graph_input_->large_agent_small_expand_param_for_consistency();
  const auto& planning_init_point_box =
      st_graph_input_->planning_init_point_box();
  const bool is_rads_scene = st_graph_input_->is_rads_scene();
  if (nullptr == planned_kd_path || nullptr == path_border_querier ||
      reserve_num <= 0 || nullptr == mutable_agent_manager ||
      nullptr == ptr_virtual_lane_manager || nullptr == ptr_ego_lane ||
      nullptr == mutable_agent_manager->mutable_agent(agent.agent_id())) {
    return;
  }
  auto* mutable_agent = mutable_agent_manager->mutable_agent(agent.agent_id());
  auto* mutable_agent_st_info = mutable_agent->mutable_agent_st_info();

  double lon_buffer = st_graph_input_->GetSuitableLonBuffer(agent);

  double lat_buffer = st_graph_input_->GetSuitableLateralBuffer(agent);
  int32_t prev_st_count = 0;
  bool is_in_st_graph = false;
  lat_buffer = StGraphUtils::RecalculateLateralBufferForLargeAgent(
      init_point, *mutable_agent_manager, agent, expand_buffer,
      small_expand_buffer, lat_buffer, &prev_st_count);

  // check whether need adjust buffer by t
  bool need_adjust_buffer_by_t = false;
  bool is_parallel = false;
  bool is_within_ego_lane = false;
  double nearest_s = 0.0;
  double nearest_l = 0.0;
  const auto& ptr_obj_lane = ptr_virtual_lane_manager->GetNearestLane(
      {agent.x(), agent.y()}, &nearest_s, &nearest_l);
  const double half_ego_lane_width = 0.5 * ptr_ego_lane->width_by_s(nearest_s);
  if (nullptr != ptr_obj_lane) {
    is_within_ego_lane =
        ptr_ego_lane->get_virtual_id() == ptr_obj_lane->get_virtual_id() &&
        nearest_l < half_ego_lane_width;
    is_parallel =
        st_graph_input_->IsParallelToEgoLane(ptr_obj_lane->get_virtual_id());
    need_adjust_buffer_by_t = StGraphUtils::CheckAdjustLateralBufferByT(
        init_point, ptr_virtual_lane_manager, ptr_ego_lane, ptr_obj_lane, agent,
        is_parallel, is_lane_keeping, is_rads_scene);
  }

  const bool need_dynamic_buffer =
      StGraphUtils::NeedDynamicBufferForTimeRange(agent) &&
      type == StBoundaryType::NORMAL;
  // check whether is candicate for close pass
  bool is_candicate_for_close_pass =
      (!reuse_for_close_pass) && (nullptr != ptr_obj_lane) &&
      StGraphUtils::CheckCandicateAgentForClosePass(
          is_lane_keeping, init_point, planned_kd_path, ptr_ego_lane,
          ptr_obj_lane, agent, type, is_rads_scene);

  const double start_absolute_time = st_graph_input_->start_absolute_time();
  const auto& time_range =
      type == StBoundaryType::EXPAND && agent.is_time_range_valid()
          ? agent.time_range()
          : st_graph_input_->time_range();
  const auto& path_range = st_graph_input_->path_range();
  // const double obs_diagonal = agent.box().diagonal();
  // const double search_distance = obs_diagonal * 0.5 + kSearchBuffer;

  const auto& trajectories = agent.trajectories();
  // only consider 2s traj to reverse vru within ego_lane
  const bool is_need_truncate_traj =
      agent.is_vru() && agent.is_reverse() && is_within_ego_lane;

  std::vector<int64_t> st_boundaries;
  st_boundaries.reserve(trajectories.size());
  std::vector<int64_t> st_boundaries_ego;
  const double time_horizon = time_range.second;
  double min_t = std::numeric_limits<double>::max();
  constexpr double kDynamicLowerT = 2.0;
  constexpr double kDynamicUpperT = 4.0;
  for (int i = 0; i < trajectories.size(); ++i) {
    if (trajectories[i].empty()) {
      continue;
    }

    const double agent_pred_end_time = trajectories[i].back().absolute_time();
    std::vector<std::pair<STPoint, STPoint>> st_point_pairs;
    st_point_pairs.reserve(reserve_num);
    const int64_t boundary_id =
        (agent.agent_id() << 8) + i + agent.trajectories().size();
    for (double relative_time = time_range.first; relative_time <= time_horizon;
         relative_time += kTimeResolution) {
      // find path_border_segments which have collison risk
      trajectory::TrajectoryPoint point;
      if (start_absolute_time + relative_time < agent_pred_end_time) {
        if (is_need_truncate_traj) {
          point = trajectories[i].Evaluate(std::fmin(
              start_absolute_time + relative_time, kConsideredReverseVruTime));
        } else {
          point = trajectories[i].Evaluate(start_absolute_time + relative_time);
        }
      } else {
        if (is_need_truncate_traj) {
          point = trajectories[i].Evaluate(kConsideredReverseVruTime);
        } else {
          StGraphUtils::LinearExtendTrajectory(
              trajectories[i], start_absolute_time + relative_time, &point);
        }
      }
      double specific_lat_buffer = need_adjust_buffer_by_t
                                       ? StGraphUtils::AdjustLateralBufferByT(
                                             point, lat_buffer, ptr_obj_lane)
                                       : lat_buffer;

      specific_lat_buffer =
          need_dynamic_buffer
              ? StGraphUtils::CalculateLateralBufferForTimeRange(
                    0.0, specific_lat_buffer, kDynamicLowerT, kDynamicUpperT,
                    relative_time)
              : specific_lat_buffer;
      specific_lat_buffer =
          reuse_for_close_pass
              ? specific_lat_buffer + extra_lateral_buffer_for_close_pass
              : specific_lat_buffer;

      Box2d obs_box(Vec2d(point.x(), point.y()), point.theta(),
                    agent.length() + 2.0 * lon_buffer,
                    agent.width() + 2.0 * specific_lat_buffer);

      // max_s min_s max_l min_l
      std::vector<double> agent_sl_boundary(4);
      std::vector<std::pair<int32_t, Vec2d>> considered_corners;

      StGraphUtils::CalculateAgentSLBoundary(
          planned_kd_path, obs_box, path_range, type, &agent_sl_boundary,
          &considered_corners);
      const double max_l = agent_sl_boundary[2];
      const double min_l = agent_sl_boundary[3];
      double lower_s = std::numeric_limits<double>::max();
      double upper_s = std::numeric_limits<double>::lowest();
      if (StGraphUtils::CalculateSRange(
              planned_kd_path, *path_border_querier, obs_box, type, path_range,
              agent_sl_boundary, considered_corners, planning_init_point_box,
              &lower_s, &upper_s, is_rads_scene)) {
        min_t = std::fmin(min_t, relative_time);
        st_point_pairs.emplace_back(
            STPoint(lower_s, relative_time, agent.agent_id(), boundary_id,
                    point.vel(), point.acc(), min_l),
            STPoint(upper_s, relative_time, agent.agent_id(), boundary_id,
                    point.vel(), point.acc(), max_l));
      }
    }

    if (!st_point_pairs.empty()) {
      std::unique_ptr<STBoundary> st_boundary(new STBoundary(st_point_pairs));
      st_boundary->set_id(boundary_id);
      st_boundaries.emplace_back(boundary_id);
      if (type == StBoundaryType::NEIGHBOR) {
        neighbor_boundary_id_st_boundaries_map_.insert(
            std::make_pair(boundary_id, std::move(st_boundary)));
      } else if (type == StBoundaryType::NORMAL) {
        reuse_for_close_pass
            ? close_pass_boundary_id_st_boundaries_map_.insert(
                  std::make_pair(boundary_id, std::move(st_boundary)))
            : boundary_id_st_boundaries_map_.insert(
                  std::make_pair(boundary_id, std::move(st_boundary)));
      } else if (type == StBoundaryType::EXPAND) {
        expand_boundary_id_st_boundaries_map_.insert(
            std::make_pair(boundary_id, std::move(st_boundary)));
      }
    }
  }

  if (!st_boundaries.empty()) {
    if (type == StBoundaryType::NEIGHBOR) {
      neighbor_agent_id_st_boundaries_map_[agent.agent_id()] = st_boundaries;
    } else if (type == StBoundaryType::NORMAL) {
      reuse_for_close_pass
          ? close_pass_agent_id_st_boundaries_map_[agent.agent_id()] =
                st_boundaries
          : agent_id_st_boundaries_map_[agent.agent_id()] = st_boundaries;
      is_in_st_graph = true && !reuse_for_close_pass;
    } else if (type == StBoundaryType::EXPAND) {
      expand_agent_id_st_boundaries_map_[agent.agent_id()] = st_boundaries;
    }
  } else if (is_candicate_for_close_pass) {
    // the agent has no original st boundary and is candicate for close pass
    dynamic_close_pass_candicate_agent_ids_.insert(agent.agent_id());
  }

  for (int i = 0; i < trajectories.size(); ++i) {
    if (!ego_motion_simulation_path) {
      break;
    }

    if (trajectories[i].empty()) {
      continue;
    }

    if (!is_lane_keeping) {
      break;
    }

    if (is_in_lane_borrow_status) {
      break;
    }

    if (agent.is_static()) {
      break;
    }

    const double agent_pred_end_time = trajectories[i].back().absolute_time();
    std::vector<std::pair<STPoint, STPoint>> st_point_pairs;
    st_point_pairs.reserve(reserve_num);
    const int64_t boundary_id =
        (agent.agent_id() << 8) + i + agent.trajectories().size();
    if (boundary_id_st_boundaries_map_.find(boundary_id) !=
        boundary_id_st_boundaries_map_.end()) {
      continue;
    }
    for (double relative_time = time_range.first; relative_time <= time_horizon;
         relative_time += kTimeResolution) {
      // find path_border_segments which have collison risk
      trajectory::TrajectoryPoint point;
      if (start_absolute_time + relative_time < agent_pred_end_time) {
        if (is_need_truncate_traj) {
          point = trajectories[i].Evaluate(std::fmin(
              start_absolute_time + relative_time, kConsideredReverseVruTime));
        } else {
          point = trajectories[i].Evaluate(start_absolute_time + relative_time);
        }
      } else {
        if (is_need_truncate_traj) {
          point = trajectories[i].Evaluate(kConsideredReverseVruTime);
        } else {
          StGraphUtils::LinearExtendTrajectory(
              trajectories[i], start_absolute_time + relative_time, &point);
        }
      }
      double specific_lat_buffer = need_adjust_buffer_by_t
                                       ? StGraphUtils::AdjustLateralBufferByT(
                                             point, lat_buffer, ptr_obj_lane)
                                       : lat_buffer;

      specific_lat_buffer =
          need_dynamic_buffer
              ? StGraphUtils::CalculateLateralBufferForTimeRange(
                    0.0, specific_lat_buffer, kDynamicLowerT, kDynamicUpperT,
                    relative_time)
              : specific_lat_buffer;

      Box2d obs_box(Vec2d(point.x(), point.y()), point.theta(),
                    agent.length() + 2.0 * lon_buffer,
                    agent.width() + 2.0 * specific_lat_buffer);

      // max_s min_s max_l min_l
      std::vector<double> agent_sl_boundary(4);
      std::vector<std::pair<int32_t, Vec2d>> considered_corners;

      bool is_success = StGraphUtils::CalculateAgentSLBoundary(
          ego_motion_simulation_path, obs_box, &agent_sl_boundary,
          &considered_corners);
      if (!is_success) {
        continue;
      }
      const double max_l = agent_sl_boundary[2];
      const double min_l = agent_sl_boundary[3];
      double lower_s = std::numeric_limits<double>::max();
      double upper_s = std::numeric_limits<double>::lowest();
      if (StGraphUtils::CalculateSRange(
              ego_motion_simulation_path, *path_border_querier, obs_box, type,
              path_range, agent_sl_boundary, considered_corners,
              planning_init_point_box, &lower_s, &upper_s, is_rads_scene)) {
        min_t = std::fmin(min_t, relative_time);
        st_point_pairs.emplace_back(
            STPoint(lower_s, relative_time, agent.agent_id(), boundary_id,
                    point.vel(), point.acc(), min_l),
            STPoint(upper_s, relative_time, agent.agent_id(), boundary_id,
                    point.vel(), point.acc(), max_l));
      }
    }

    if (!st_point_pairs.empty()) {
      std::unique_ptr<STBoundary> st_boundary(new STBoundary(st_point_pairs));
      st_boundary->set_id(boundary_id);
      // st_boundary->set_decision_type(STBoundary::DecisionType::NEIGHBOR_YIELD);
      st_boundaries_ego.emplace_back(boundary_id);
      neighbor_boundary_id_st_boundaries_map_.insert(
          std::make_pair(boundary_id, std::move(st_boundary)));
    }
  }

  if (!st_boundaries_ego.empty()) {
    neighbor_agent_id_st_boundaries_map_[agent.agent_id()] = st_boundaries_ego;
  }

  if (is_large_agent && !reuse_for_close_pass) {
    mutable_agent_st_info->is_in_st_graph_ = is_in_st_graph;
    mutable_agent_st_info->lateral_buffer_ = lat_buffer;
    mutable_agent_st_info->st_graph_count_ =
        is_in_st_graph ? ++prev_st_count : 0;
    mutable_agent_st_info->min_t_ = min_t;
  }
}

void STGraph::MakeStPointsTable() {
  const int32_t reserve_num = st_graph_input_->reserve_num();
  if (reserve_num <= 0) {
    return;
  }
  const auto& time_range = st_graph_input_->time_range();
  st_points_table_.resize(reserve_num);
  for (auto it = boundary_id_st_boundaries_map_.begin();
       it != boundary_id_st_boundaries_map_.end(); ++it) {
    auto st_boundary = it->second.get();
    if (st_boundary->decision_type() ==
        STBoundary::DecisionType::CAUTION_YIELD) {
      continue;
    }
    const auto& lower_points = st_boundary->lower_points();
    const auto& upper_points = st_boundary->upper_points();
    for (int i = 0; i < lower_points.size(); ++i) {
      if (lower_points[i].valid() && upper_points[i].valid()) {
        int index = std::round((lower_points[i].t() - time_range.first) /
                               kTimeResolution);
        st_points_table_[index].emplace_back(lower_points[i], upper_points[i]);
      }
    }
  }

  auto cmp = [](const std::pair<STPoint, STPoint> ele1,
                const std::pair<STPoint, STPoint> ele2) {
    return ele1.first.s() < ele2.first.s();
  };

  for (auto& intervals : st_points_table_) {
    if (intervals.empty()) {
      continue;
    }

    // sort intervals
    std::sort(intervals.begin(), intervals.end(), cmp);

    // merge intervals
    std::vector<std::pair<STPoint, STPoint>> merged_intervals;
    for (int i = 0; i < intervals.size(); ++i) {
      double L = intervals[i].first.s(), R = intervals[i].second.s();
      if (merged_intervals.empty() || merged_intervals.back().second.s() < L) {
        merged_intervals.emplace_back(intervals[i]);
      } else {
        if (merged_intervals.back().second.s() < R) {
          merged_intervals.back().second = intervals[i].second;
        }
      }
    }
    intervals = merged_intervals;
  }
}

void STGraph::ConstructDefaultStPassCorridor() {
  const auto& time_range = st_graph_input_->time_range();
  int32_t total_size =
      int32_t((time_range.second - time_range.first) / kTimeResolution) + 1;
  st_pass_corridor_.reserve(total_size);
  neighbor_corridor_.reserve(total_size);

  STPoint init_upper_point;
  init_upper_point.set_agent_id(kNoAgentId);
  init_upper_point.set_s(std::numeric_limits<double>::max());
  init_upper_point.set_velocity(std::numeric_limits<double>::max());
  init_upper_point.set_acceleration(std::numeric_limits<double>::max());

  STPoint init_lower_point;
  init_lower_point.set_agent_id(kNoAgentId);
  init_lower_point.set_s(std::numeric_limits<double>::lowest());
  init_lower_point.set_velocity(std::numeric_limits<double>::lowest());
  init_lower_point.set_acceleration(std::numeric_limits<double>::lowest());

  for (double t = time_range.first; t < time_range.second + kMathEpsilon;
       t += kTimeResolution) {
    init_upper_point.set_t(t);
    init_lower_point.set_t(t);
    st_pass_corridor_.emplace_back(init_upper_point, init_lower_point);
    neighbor_corridor_.emplace_back(init_upper_point, init_lower_point);
  }
}

void STGraph::ResetNeighborCorridor() {
  const auto& time_range = st_graph_input_->time_range();
  int32_t total_size =
      int32_t((time_range.second - time_range.first) / kTimeResolution) + 1;
  STPoint init_upper_point;
  init_upper_point.set_agent_id(kNoAgentId);
  init_upper_point.set_s(std::numeric_limits<double>::max());
  init_upper_point.set_velocity(std::numeric_limits<double>::max());
  init_upper_point.set_acceleration(std::numeric_limits<double>::max());

  STPoint init_lower_point;
  init_lower_point.set_agent_id(kNoAgentId);
  init_lower_point.set_s(std::numeric_limits<double>::lowest());
  init_lower_point.set_velocity(std::numeric_limits<double>::lowest());
  init_lower_point.set_acceleration(std::numeric_limits<double>::lowest());

  auto default_value = std::vector<std::pair<STPoint, STPoint>>(
      total_size, std::make_pair(init_upper_point, init_lower_point));
  neighbor_corridor_.swap(default_value);

  first_neighbor_yield_index_ = std::numeric_limits<int32_t>::max();
  first_neighbor_yield_agent_id_ = agent::AgentDefaultInfo::kNoAgentId;
  first_neighbor_overtake_index_ = std::numeric_limits<int32_t>::max();
  first_neighbor_overtake_agent_id_ = agent::AgentDefaultInfo::kNoAgentId;
}

void STGraph::BackwardExtendStBoundaries() {
  const auto& agents = st_graph_input_->filtered_agents();
  for (const auto& agent : agents) {
    if (nullptr == agent) {
      continue;
    }
    if (!agent->need_backward_extend()) {
      continue;
    }
    // get trajectories which need extend
    const auto it = agent_id_st_boundaries_map_.find(agent->agent_id());
    if (it == agent_id_st_boundaries_map_.end()) {
      continue;
    }
    const auto& st_boundary_ids = it->second;
    const size_t st_boundary_ids_num = st_boundary_ids.size();
    for (size_t i = 0; i < st_boundary_ids_num; ++i) {
      const auto boundary_id = st_boundary_ids[i];
      const auto& it = boundary_id_st_boundaries_map_.find(boundary_id);
      if (it == boundary_id_st_boundaries_map_.end()) {
        continue;
      }
      const auto& st_boundary = it->second;
      if (nullptr == st_boundary) {
        continue;
      }
      const auto idx = boundary_id & 0XFF;
      if (idx < 0) {
        continue;
      }
      std::vector<trajectory::Trajectory> trajectories;
      const auto origin_trajectories_num = agent->trajectories().size();
      const bool use_origin_trajectories = idx < origin_trajectories_num;
      // if (use_origin_trajectories) {
      //   trajectories = agent->trajectories();
      // } else {
      //   trajectories = agent->trajectories();
      // }
      trajectories = agent->trajectories();
      if (trajectories.empty()) {
        continue;
      }
      // const auto& trajectory =
      //     use_origin_trajectories ? trajectories[idx]
      //                             : trajectories[idx -
      //                             origin_trajectories_num];

      const auto& trajectory = trajectories.front();
      if (trajectory.empty()) {
        continue;
      }
      BackwardExtendSingleStBoundary(*agent, trajectory, *st_boundary.get(),
                                     idx);
    }
  }
}

void STGraph::BackwardExtendSingleStBoundary(
    const agent::Agent& agent, const trajectory::Trajectory& trajectory,
    const STBoundary& st_boundary, const size_t idx) {
  const auto time_range = st_graph_input_->time_range();
  const auto path_range = st_graph_input_->path_range();
  const auto& init_point = st_graph_input_->planning_init_point();
  const auto ptr_virtual_lane_manager =
      st_graph_input_->ptr_virtual_lane_manager();
  const bool is_lane_keeping = st_graph_input_->is_lane_keeping();
  const auto ptr_ego_lane = st_graph_input_->ego_lane();
  const auto planned_kd_path = st_graph_input_->processed_path();
  const auto* path_border_querier = st_graph_input_->path_border_querier();
  const double start_absolute_time = st_graph_input_->start_absolute_time();
  const StBoundaryType type = StBoundaryType::EXPAND;
  const double backward_extend_time_s =
      st_graph_input_->backward_extend_time_s();
  const auto& planning_init_point_box =
      st_graph_input_->planning_init_point_box();
  const bool is_rads_scene = st_graph_input_->is_rads_scene();
  const double start_time = std::fmax(st_boundary.max_t(), time_range.first);
  const double end_time =
      std::fmin(start_time + backward_extend_time_s, time_range.second);
  if (start_time > end_time - kMathEpsilon) {
    return;
  }
  const double agent_pred_end_time = trajectory.back().absolute_time();
  double lon_buffer = st_graph_input_->GetSuitableLonBuffer(agent);
  double lat_buffer = st_graph_input_->GetSuitableLateralBuffer(agent);

  // check whether need adjust buffer by t
  bool need_adjust_buffer_by_t = false;
  bool is_parallel = false;
  double nearest_s = 0.0;
  double nearest_l = 0.0;
  const auto& ptr_obj_lane = ptr_virtual_lane_manager->GetNearestLane(
      {agent.x(), agent.y()}, &nearest_s, &nearest_l);
  if (nullptr != ptr_obj_lane) {
    is_parallel =
        st_graph_input_->IsParallelToEgoLane(ptr_obj_lane->get_virtual_id());
    need_adjust_buffer_by_t = StGraphUtils::CheckAdjustLateralBufferByT(
        init_point, ptr_virtual_lane_manager, ptr_ego_lane, ptr_obj_lane, agent,
        is_parallel, is_lane_keeping, is_rads_scene);
  }
  std::vector<std::pair<STPoint, STPoint>> st_point_pairs;
  st_point_pairs.reserve((end_time - start_time) / kTimeResolution);
  constexpr int32_t KBackwardExtendStboundaryStartIdx = 100;
  const int64_t target_boundary_id =
      (agent.agent_id() << 8) + KBackwardExtendStboundaryStartIdx + idx;
  for (double relative_time = start_time; relative_time < end_time;
       relative_time += kTimeResolution) {
    trajectory::TrajectoryPoint point;
    if (start_absolute_time + relative_time < agent_pred_end_time) {
      point = trajectory.Evaluate(start_absolute_time + relative_time);
    } else {
      StGraphUtils::LinearExtendTrajectory(
          trajectory, start_absolute_time + relative_time, &point);
    }
    double specific_lat_buffer = need_adjust_buffer_by_t
                                     ? StGraphUtils::AdjustLateralBufferByT(
                                           point, lat_buffer, ptr_obj_lane)
                                     : lat_buffer;
    Box2d obs_box({point.x(), point.y()}, point.theta(),
                  agent.length() + 2.0 * lon_buffer,
                  agent.width() + 2.0 * specific_lat_buffer);
    // max_s min_s max_l min_l
    std::vector<double> agent_sl_boundary(4);
    std::vector<std::pair<int32_t, Vec2d>> considered_corners;

    StGraphUtils::CalculateAgentSLBoundary(planned_kd_path, obs_box, path_range,
                                           type, &agent_sl_boundary,
                                           &considered_corners);
    double lower_s = std::numeric_limits<double>::max();
    double upper_s = std::numeric_limits<double>::lowest();
    if (StGraphUtils::CalculateSRange(
            planned_kd_path, *path_border_querier, obs_box, type, path_range,
            agent_sl_boundary, considered_corners, planning_init_point_box,
            &lower_s, &upper_s, is_rads_scene)) {
      constexpr double kDistThr = 1e-3;
      if (std::fabs(lower_s - upper_s) < kDistThr) {
        continue;
      }
      st_point_pairs.emplace_back(
          STPoint(lower_s, relative_time, agent.agent_id(), target_boundary_id,
                  point.vel(), point.acc()),
          STPoint(upper_s, relative_time, agent.agent_id(), target_boundary_id,
                  point.vel(), point.acc()));
    }
  }
  if (!st_point_pairs.empty()) {
    std::unique_ptr<STBoundary> st_boundary(new STBoundary(st_point_pairs));
    st_boundary->set_id(target_boundary_id);
    boundary_id_st_boundaries_map_.insert(
        std::make_pair(target_boundary_id, std::move(st_boundary)));
    agent_id_st_boundaries_map_[agent.agent_id()].emplace_back(
        target_boundary_id);
  }
}

bool STGraph::UpdateStBoundaryDecisionResults(
    const std::unordered_map<int64_t, STBoundary::DecisionType>&
        decision_table) {
  if (decision_table.empty()) {
    return true;
  }
  for (const auto& decision_entry : decision_table) {
    auto id = decision_entry.first;
    auto iter = boundary_id_st_boundaries_map_.find(id);
    if (iter == boundary_id_st_boundaries_map_.end()) {
      // TODO: return false; ?
      continue;
    }
    auto* st_boundary = iter->second.get();
    if (st_boundary == nullptr) {
      // TODO: return false; ?
      continue;
    }
    st_boundary->set_decision_type(decision_entry.second);
  }
  const bool is_success = CalculateStPassCorridor();
  return is_success;
}

bool STGraph::CalculateStPassCorridor() {
  if (boundary_id_st_boundaries_map_.empty()) {
    return false;
  }

  const auto& time_range = st_graph_input_->time_range();
  for (size_t i = 0; i < st_pass_corridor_.size(); i++) {
    double t = time_range.first + i * kTimeResolution;
    STPoint upper_point = STPoint::HighestSTPoint();
    STPoint lower_point = STPoint::LowestSTPoint();
    bool find_upper = false;
    bool find_lower = false;
    for (const auto& st_boundary_entry : boundary_id_st_boundaries_map_) {
      const auto& st_boundary = st_boundary_entry.second;
      if (st_boundary == nullptr) {
        continue;
      }
      if (st_boundary->decision_type() ==
          STBoundary::DecisionType::CAUTION_YIELD) {
        continue;
      }
      const auto& decision_type = st_boundary->decision_type();
      if (decision_type == STBoundary::DecisionType::YIELD) {
        STPoint cur_upper_pt, cur_lower_pt;
        if (!st_boundary->GetBoundaryBounds(t, &cur_lower_pt, &cur_upper_pt)) {
          continue;
        }
        if (cur_lower_pt.s() < upper_point.s()) {
          find_upper = true;
          upper_point = cur_lower_pt;
        }
      } else if (decision_type == STBoundary::DecisionType::OVERTAKE) {
        STPoint cur_upper_pt, cur_lower_pt;
        if (!st_boundary->GetBoundaryBounds(t, &cur_lower_pt, &cur_upper_pt)) {
          continue;
        }
        if (cur_upper_pt.s() > lower_point.s()) {
          find_lower = true;
          lower_point = cur_upper_pt;
        }
      }
    }
    if (find_upper) {
      st_pass_corridor_[i].first = upper_point;
    }
    if (find_lower) {
      st_pass_corridor_[i].second = lower_point;
    }
  }
  return true;
}

const std::shared_ptr<StGraphInput>& STGraph::st_graph_input() const {
  return st_graph_input_;
}

const std::pair<double, double> STGraph::path_range() const {
  return st_graph_input_->path_range();
}

const std::pair<double, double> STGraph::time_range() const {
  return st_graph_input_->time_range();
}

const int32_t STGraph::reserve_num() const {
  return st_graph_input_->reserve_num();
}

const std::unordered_map<int64_t, std::unique_ptr<STBoundary>>&
STGraph::boundary_id_st_boundaries_map() const {
  return boundary_id_st_boundaries_map_;
}

const std::unordered_map<int64_t, std::unique_ptr<STBoundary>>&
STGraph::neighbor_boundary_id_st_boundaries_map() const {
  return neighbor_boundary_id_st_boundaries_map_;
}

const std::unordered_map<int32_t, std::vector<int64_t>>&
STGraph::neighbor_agent_id_st_boundaries_map() const {
  return neighbor_agent_id_st_boundaries_map_;
}

const int32_t STGraph::first_neighbor_yield_agent_id() const {
  return first_neighbor_yield_agent_id_;
}

const std::unordered_map<int64_t, std::unique_ptr<STBoundary>>&
STGraph::expand_boundary_id_st_boundaries_map() const {
  return expand_boundary_id_st_boundaries_map_;
}

const std::unordered_map<int32_t, std::vector<int64_t>>&
STGraph::expand_agent_id_st_boundaries_map() const {
  return expand_agent_id_st_boundaries_map_;
}

const std::unordered_map<int64_t, std::unique_ptr<STBoundary>>&
STGraph::close_pass_boundary_id_st_boundaries_map() const {
  return close_pass_boundary_id_st_boundaries_map_;
}

const std::unordered_map<int32_t, std::vector<int64_t>>&
STGraph::close_pass_agent_id_st_boundaries_map() const {
  return close_pass_agent_id_st_boundaries_map_;
}

const std::vector<std::vector<std::pair<STPoint, STPoint>>>&
STGraph::st_points_table() const {
  return st_points_table_;
}

const std::unordered_map<int32_t, std::vector<int64_t>>&
STGraph::agent_id_st_boundaries_map() const {
  return agent_id_st_boundaries_map_;
}

const std::vector<int32_t>& STGraph::caution_yield_agent_ids() const {
  return caution_yield_agent_ids_;
}

const std::vector<std::pair<STPoint, STPoint>>& STGraph::st_pass_corridor()
    const {
  return st_pass_corridor_;
}

const std::vector<std::pair<STPoint, STPoint>>& STGraph::neighbor_corridor()
    const {
  return neighbor_corridor_;
}

const int32_t STGraph::first_neighbor_yield_index() const {
  return first_neighbor_yield_index_;
}

const int32_t STGraph::first_neighbor_overtake_index() const {
  return first_neighbor_overtake_index_;
}

bool STGraph::UpdateNeighborAgentResults(
    const std::unordered_map<int32_t, STBoundary::DecisionType>&
        neighbor_agent_decision_table) {
  if (neighbor_agent_decision_table.empty()) {
    return true;
  }
  for (const auto& neighbor_decision_entry : neighbor_agent_decision_table) {
    auto agent_id = neighbor_decision_entry.first;
    auto decision = neighbor_decision_entry.second;
    auto id_iter = neighbor_agent_id_st_boundaries_map_.find(agent_id);
    if (id_iter == neighbor_agent_id_st_boundaries_map_.end()) {
      continue;
    }
    auto agent_st_boundary_ids = id_iter->second;
    if (agent_st_boundary_ids.empty()) {
      continue;
    }
    for (const auto boundary_id : agent_st_boundary_ids) {
      auto boundary_iter =
          neighbor_boundary_id_st_boundaries_map_.find(boundary_id);
      if (boundary_iter == neighbor_boundary_id_st_boundaries_map_.end()) {
        continue;
      }
      auto* st_boundary = boundary_iter->second.get();
      if (st_boundary == nullptr) {
        continue;
      }
      st_boundary->set_decision_type(decision);
    }
  }

  const bool is_success = CalculateNeighborCorridor();
  return is_success;
}

bool STGraph::UpdateNeighborAgentResultsForEgoMotionSimPath() {
  const bool is_success = CalculateNeighborCorridor();
  return is_success;
}

bool STGraph::CalculateNeighborCorridor() {
  if (neighbor_boundary_id_st_boundaries_map_.empty()) {
    return false;
  }

  ResetNeighborCorridor();

  NeighborCorridorYieldInfo neighbor_corridor_yield_info;
  NeighborCorridorOvertakeInfo neighbor_corridor_overtake_info;
  const auto& time_range = st_graph_input_->time_range();
  for (size_t i = 0; i < neighbor_corridor_.size(); i++) {
    double t = time_range.first + i * kTimeResolution;
    STPoint upper_point = STPoint::HighestSTPoint();
    STPoint lower_point = STPoint::LowestSTPoint();
    bool find_upper = false;
    bool find_lower = false;

    for (const auto& st_boundary_entry :
         neighbor_boundary_id_st_boundaries_map_) {
      const auto& st_boundary = st_boundary_entry.second;
      if (st_boundary == nullptr) {
        continue;
      }
      const auto& decision_type = st_boundary->decision_type();
      if (decision_type == STBoundary::DecisionType::NEIGHBOR_YIELD) {
        STPoint cur_upper_pt, cur_lower_pt;
        if (!st_boundary->GetBoundaryBounds(t, &cur_lower_pt, &cur_upper_pt)) {
          continue;
        }
        if (cur_lower_pt.s() < upper_point.s()) {
          find_upper = true;
          upper_point = cur_lower_pt;
        }
      } else if (decision_type == STBoundary::DecisionType::NEIGHBOR_OVERTAKE) {
        STPoint cur_upper_pt, cur_lower_pt;
        if (!st_boundary->GetBoundaryBounds(t, &cur_lower_pt, &cur_upper_pt)) {
          continue;
        }
        if (cur_upper_pt.s() > lower_point.s()) {
          find_lower = true;
          lower_point = cur_upper_pt;
        }
      }
    }
    if (find_upper) {
      neighbor_corridor_[i].first = upper_point;
      if (i < neighbor_corridor_yield_info.first_yield_index) {
        neighbor_corridor_yield_info.first_yield_index = i;
        neighbor_corridor_yield_info.first_yield_agent_id =
            upper_point.agent_id();
        neighbor_corridor_yield_info.first_yield_st_point = upper_point;
      }
    }
    if (find_lower) {
      neighbor_corridor_[i].second = lower_point;
      if (i < neighbor_corridor_overtake_info.first_overtake_index) {
        neighbor_corridor_overtake_info.first_overtake_index = i;
        neighbor_corridor_overtake_info.first_overtake_agent_id =
            lower_point.agent_id();
        neighbor_corridor_overtake_info.first_overtake_st_point = lower_point;
      }
    }
  }

  if (neighbor_corridor_yield_info.first_yield_agent_id !=
      agent::AgentDefaultInfo::kNoAgentId) {
    const auto& first_yield_st_point =
        neighbor_corridor_yield_info.first_yield_st_point;
    neighbor_corridor_yield_info_map_[first_yield_st_point.s()] =
        neighbor_corridor_yield_info;
  }

  if (neighbor_corridor_overtake_info.first_overtake_agent_id !=
      agent::AgentDefaultInfo::kNoAgentId) {
    const auto& first_overtake_st_point =
        neighbor_corridor_overtake_info.first_overtake_st_point;
    neighbor_corridor_overtake_info_map_[first_overtake_st_point.s()] =
        neighbor_corridor_overtake_info;
  }

  // refresh final yield or overtake index and agent id
  if (!neighbor_corridor_yield_info_map_.empty()) {
    const auto [closet_s_to_ego, neighbor_corridor_yield_info] =
        *neighbor_corridor_yield_info_map_.begin();
    neighbor_corridor_[neighbor_corridor_yield_info.first_yield_index].first =
        neighbor_corridor_yield_info.first_yield_st_point;
    first_neighbor_yield_index_ =
        neighbor_corridor_yield_info.first_yield_index;
    first_neighbor_yield_agent_id_ =
        neighbor_corridor_yield_info.first_yield_agent_id;
  }

  if (!neighbor_corridor_overtake_info_map_.empty()) {
    const auto [closet_s_to_ego, neighbor_corridor_overtake_info] =
        *neighbor_corridor_overtake_info_map_.begin();
    neighbor_corridor_[neighbor_corridor_overtake_info.first_overtake_index]
        .first = neighbor_corridor_overtake_info.first_overtake_st_point;
    first_neighbor_overtake_index_ =
        neighbor_corridor_overtake_info.first_overtake_index;
    first_neighbor_overtake_agent_id_ =
        neighbor_corridor_overtake_info.first_overtake_agent_id;
  }

  return true;
}

void STGraph::AddStGraphDataToProto() {
  auto& debug_info_pb = DebugInfoManager::GetInstance().GetDebugInfoPb();
  const auto& path_range = st_graph_input_->path_range();
  const auto& time_range = st_graph_input_->time_range();
  const auto& boundary_id_st_boundaries_map = boundary_id_st_boundaries_map_;
  const auto& neighbor_boundary_id_st_boundaries_map =
      neighbor_boundary_id_st_boundaries_map_;

  auto mutable_st_graph_data = debug_info_pb->mutable_st_graph_data();

  st_graph_data_pb_.set_start_path(path_range.first);
  st_graph_data_pb_.set_end_path(path_range.second);
  st_graph_data_pb_.set_start_time(time_range.first);
  st_graph_data_pb_.set_end_time(time_range.second);

  for (auto it = boundary_id_st_boundaries_map.begin();
       it != boundary_id_st_boundaries_map.end(); ++it) {
    auto* boundary = st_graph_data_pb_.add_st_boundaries();
    boundary->set_boundary_id(it->first);
    auto lower_points = it->second->lower_points();
    auto upper_points = it->second->upper_points();
    for (int i = 0; i < lower_points.size(); ++i) {
      auto* point = boundary->add_lower_points();
      point->set_s(lower_points.at(i).s());
      point->set_t(lower_points.at(i).t());
      point->set_vel(lower_points.at(i).velocity());
      point->set_acc(lower_points.at(i).acceleration());
      point->set_valid(lower_points.at(i).valid());
      point->set_agent_id(lower_points.at(i).agent_id());
    }
    for (int i = 0; i < upper_points.size(); ++i) {
      auto* point = boundary->add_upper_points();
      point->set_s(upper_points.at(i).s());
      point->set_t(upper_points.at(i).t());
      point->set_vel(upper_points.at(i).velocity());
      point->set_acc(upper_points.at(i).acceleration());
      point->set_valid(upper_points.at(i).valid());
      point->set_agent_id(upper_points.at(i).agent_id());
    }
  }

  for (auto it = neighbor_boundary_id_st_boundaries_map.begin();
       it != neighbor_boundary_id_st_boundaries_map.end(); ++it) {
    auto* boundary = st_graph_data_pb_.add_neighbor_st_boundaries();
    boundary->set_boundary_id(it->first);
    auto lower_points = it->second->lower_points();
    auto upper_points = it->second->upper_points();
    for (int i = 0; i < lower_points.size(); ++i) {
      auto* point = boundary->add_lower_points();
      point->set_s(lower_points.at(i).s());
      point->set_t(lower_points.at(i).t());
      point->set_vel(lower_points.at(i).velocity());
      point->set_acc(lower_points.at(i).acceleration());
      point->set_valid(lower_points.at(i).valid());
      point->set_agent_id(lower_points.at(i).agent_id());
    }
    for (int i = 0; i < upper_points.size(); ++i) {
      auto* point = boundary->add_upper_points();
      point->set_s(upper_points.at(i).s());
      point->set_t(upper_points.at(i).t());
      point->set_vel(upper_points.at(i).velocity());
      point->set_acc(upper_points.at(i).acceleration());
      point->set_valid(upper_points.at(i).valid());
      point->set_agent_id(upper_points.at(i).agent_id());
    }
  }

  const auto processed_path = st_graph_input_->processed_path();
  if (nullptr != processed_path) {
    const auto& path_points = processed_path->path_points();
    for (const auto& point : path_points) {
      auto* p = st_graph_data_pb_.add_planned_path();
      p->set_x(point.x());
      p->set_y(point.y());
    }
  }
  mutable_st_graph_data->CopyFrom(st_graph_data_pb_);
}

void STGraph::Reset() {
  st_graph_data_pb_.Clear();

  boundary_id_st_boundaries_map_.clear();
  agent_id_st_boundaries_map_.clear();
  neighbor_boundary_id_st_boundaries_map_.clear();
  neighbor_agent_id_st_boundaries_map_.clear();
  expand_boundary_id_st_boundaries_map_.clear();
  expand_agent_id_st_boundaries_map_.clear();
  st_points_table_.clear();
  st_pass_corridor_.clear();
  neighbor_corridor_.clear();
  caution_yield_agent_ids_.clear();
  ignore_agent_ids_.clear();
  static_close_pass_candicate_agent_ids_.clear();
  dynamic_close_pass_candicate_agent_ids_.clear();
  close_pass_boundary_id_st_boundaries_map_.clear();
  close_pass_agent_id_st_boundaries_map_.clear();
}

}  // namespace speed
}  // namespace planning